### ISSUE TITLE
Service Environment Parameter Missing in Remote Config Fetch API

### ISSUE THREAD

**Issue by HimanshuLakra** [elastic/apm-agent-ruby#1011]
## Describe the bug
We have added Agent Remote Configuration with Service Environment and Elastic APM agent is not able to fetch the config because service.environment parameter is missing in GET API call ('/config/v1/agents') in central_config.rb file.

Kibana Log:
log   [15:32:59.040] [info][apm][plugins] Config was not found for VanillaApp/undefined
undefined is because of absence of service.environment parameter.

## Expected behavior
Support for service.environment should be there to fetch correct agent remote configuration.

## Environment
Ruby: 2.6.2
Elastic Apm Gem Version: 3.15.1
Rails: 5.1.4

**Comment by mikker** [comment]
This sounds weird. Are you setting the `environment` config option manually? Within Rails, it should default to Rails' environment.

**Comment by HimanshuLakra** [comment]
Yes, the environment config is defined in the elastic_apm.yml file.

```
enabled: <%= Settings.ELASTIC_APM.ENABLE %>
server_url: <%= Settings.ELASTIC_APM.SERVER_URL %>`
secret_token: <%= Settings.ELASTIC_APM.SECRET_TOKEN %>
environment: <%= Settings.ELASTIC_APM.ENVIRONMENT %>
transaction_sample_rate: <%= Settings.ELASTIC_APM.TRANSACTION_SAMPLE_RATE %>
span_frames_min_duration: <%= Settings.ELASTIC_APM.SPAN_FRAMES_MIN_DURATION %>
```

@mikker https://github.com/elastic/apm-agent-ruby/blob/3.x/lib/elastic_apm/central_config.rb#L159
The environment is not passed in the API called from the perform_request function. 

Also, I have checked the python elastic APM agent they use POST API(https://www.elastic.co/guide/en/apm/server/master/agent-configuration-api.html) to get the remote config and pass "service.environment" in the API call.
Code Reference: https://github.com/elastic/apm-agent-python/blob/b080438903e99352a833fb2cefe1b950111ac196/elasticapm/transport/http.py#L117

**Comment by mikker** [comment]
You're right. That's a clear oversigt, sorry about that. And thanks for the investigation. I've pushed a PR. Should be green shortly.

There's no difference between GET and POST, confirmed with the server team, so that'll probably stay as is.

**Comment by HimanshuLakra** [comment]
@mikker I have tested the above changes and the remote config is now reflected on the APM agent. But on the Kibana side, the indicator(whether the config is applied by the agent or not) is still in grey color, it is not changing to green.

![Screen Shot 2021-05-26 at 3 15 39 PM](https://user-images.githubusercontent.com/7153301/119639493-4976d200-be35-11eb-97be-54f606f8c0b2.png)

**Comment by mikker** [comment]
@HimanshuLakra Weird. Is this still the case?

**Comment by HimanshuLakra** [comment]
Yes, @mikker. Remote config is reflected on the Agent but the indicator is not changing on Kibana.
Below are the details of the environment
Elasticsearch, Kibana, APM Server: 7.12.0
Ruby: 2.6.2
Elastic APM Gem Version: 3.15.1 (+ Merge of https://github.com/elastic/apm-agent-ruby/pull/1015)
Rails: 5.1.4
If you need any more information do let me know. 

Also, Can this be related to the use of GET API (for config fetch) instead of POST? because the indicator is turned to green for the python APM agent.

**Comment by HimanshuLakra** [comment]
@mikker any update?

**Comment by mikker** [comment]
Yes, sorry, this should be fixed in `4.1.0`, https://github.com/elastic/apm-agent-ruby/pull/1014.

**Comment by mikker** [comment]
It should turn green after an agent successfully fetches a config. Are you seeing your remote config options being applied? Is the agent logging a `[INFO] Updated config from Kibana` message?

**Comment by HimanshuLakra** [comment]
Yes 
```
I, [2021-06-16T15:52:25.627918 #10170]  INFO -- : [ElasticAPM] Updated config from Kibana
I, [2021-06-16T15:52:55.676893 #10170]  INFO -- : [ElasticAPM] Updated config from Kibana
I, [2021-06-16T15:53:25.723852 #10170]  INFO -- : [ElasticAPM] Updated config from Kibana
```

**Comment by estolfo** [comment]
@HimanshuLakra We figured out what the issue was. You should see the grey dot turn to green for the Ruby agent configuration with the next release of the agent.
