### ISSUE TITLE
SpanHelpers span_method doesnt work anymore with functions taking blocks

### ISSUE THREAD

**Issue by MarkusSintonen** [elastic/apm-agent-ruby#1013]
## Describe the bug

After this PR https://github.com/elastic/apm-agent-ruby/pull/890 `span_method` doesnt anymore work with functions taking blocks.

## Steps to reproduce
```ruby
class Test
  include ElasticAPM::SpanHelpers

  def foo
    yield
  end
  span_method :foo

  def bar
    foo {}
  end
end

Test.new.bar # Raises LocalJumpError
```

## Expected behavior

Above shouldnt raise `LocalJumpError`.

## Environment
- **OS**: OSX 11.2.3
- **Ruby version**: 2.7.2
- **Framework and version**: Rails 6.0.3.5
- **Agent version**: 4.0.0

**Comment by mikker** [comment]
Thanks for reporting this. Sounds plausible, I'll take a look!

**Comment by MarkusSintonen** [comment]
Thanks @mikker to me the fix would seem rather easy, right:
https://github.com/elastic/apm-agent-ruby/blob/c4f34ce0b1f03b9d2c2160f08bd24e74d6ba948a/lib/elastic_apm/span_helpers.rb#L40-L48

To be:
```ruby
 define_method(method) do |*args, &block| 
   unless ElasticAPM.current_transaction 
     return super(*args, &block) 
   end 
  
   ElasticAPM.with_span name.to_s, type.to_s do 
     super(*args, &block) 
   end 
 end 
```

**Comment by mikker** [comment]
I've merged the fix. Will push a release tomorrow. Thank you for finding and diagnosing this! 💙💚💛💜❤️

**Comment by MarkusSintonen** [comment]
@mikker I see that the Changelog and version tag was updated but the newest version is not yet available

**Comment by mikker** [comment]
Something went wrong with our automated release script, sorry. Just pushed it manually!
