### ISSUE TITLE
"Vanilla" installation can cause webmock warnings

### ISSUE THREAD

**Issue by jgrau** [elastic/apm-agent-ruby#1041]
## Describe the bug

I'm installing the ruby agent for the first time so I apologise in advance if this is non-issue and I've just missed a configuration option :) 

I am following the setup instructions (`https://<my-deployment>.kb.europe-west3.gcp.cloud.es.io:9243/app/home#/tutorial/apm`). I've installed and configured the agent. 

When running my specs I get these warnings from webmock:

```
Real HTTP connections are disabled. Unregistered request: GET http://169.254.169.254/latest/dynamic/instance-identity/document with headers {'Connection'=>'close', 'Host'=>'169.254.169.254', 'User-Agent'=>'http.rb/5.0.1'} (WebMock::NetConnectNotAllowedError)

You can stub this request with the following snippet:

stub_request(:get, "http://169.254.169.254/latest/dynamic/instance-identity/document").
  with(
    headers: {
          'Connection'=>'close',
          'Host'=>'169.254.169.254',
          'User-Agent'=>'http.rb/5.0.1'
    }).
  to_return(status: 200, body: "", headers: {})
```

## Steps to reproduce

1. `gem 'elastic-apm'`
2. Add agent configuration (see my config below)
3. With a spec/test suite that uses webmock and that is triggering the agent - run test suite :)

## Expected behavior

Since the agent is not configured to run in the `test` environment I would have expected no changes in how my specs behaves.

## Environment

- **OS**: OSX
- **Ruby version**: 3.0.0p0
- **Framework and version**: Rails 6.1.4
- **APM Server version**:  Not sure :)
- **Agent version**: 4.2.0

## Additional context

My config:

```
        # Set the service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
        # Defaults to the name of your Rails app
        service_name: 'landfolk-api'
        
        # Use if APM Server requires a secret token
        secret_token: Rails.application.config.x.elastic.fetch(:app_secret)
        
        # Set the custom APM Server URL (default: http://localhost:8200)
        server_url: 'https://<redacted>.apm.europe-west3.gcp.cloud.es.io:443'
        
        # Set the service environment
        environment: 'production'
```

**Comment by estolfo** [comment]
HI @jgrau Sorry for the trouble! The agent tries to detect what your cloud provider is to gather cloud provider metadata upon startup. You could set up a Webmock request stub for each of the requests the agent makes to gather cloud provider metadata but that would probably be tedious. So I would suggest instead using the config option `cloud_provider` and set it to `none`. The agent will then skip trying to gather cloud provider metadata.
Here is the place in the agent where that code is, in case you want to set up the request mocks and need to know the URLs to expect: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/metadata/cloud_info.rb#L28-L30

And [here](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-cloud-provider) is the documentation on the `cloud_provider` config option.

Let me know if that resolves the issue for you!

**Comment by jgrau** [comment]
Thanks for the reply!

> So I would suggest instead using the config option `cloud_provider` and set it to `none`

That works but then you wouldn't get that piece of functionality in production either, right? Not a problem for me as I'm not on one of the clouds that the agent is gathering metadata for but may be a problem for others.

I read the documentation more thoroughly and realised [the solution was right at the top](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#_ruby_on_rails). I ended up with

```
# config/environments/test.rb
config.elastic_apm = { enabled: false }

# config/environments/production.rb
  config.elastic_apm = {
    service_name: 'landfolk-api',
    secret_token:
      Rails.application.credentials.elastic.fetch(:apm_secret_token),
    server_url:
      'https://<redacted>.apm.europe-west3.gcp.cloud.es.io:443',
    environment: 'production',
  }
```

and that seems to work as I want. Thank you again for your help :)

**Comment by estolfo** [comment]
yes, that works too. Sorry, I thought you wanted to test the agent! But now I see that you are ok with disabling it in your test environment.
