### ISSUE TITLE
[CI] Master branch not passing

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-ruby#1047]
Hello Ruby folks. :)

We've finished [filtering the branches for this project](https://github.com/elastic/apm-agent-ruby/pull/1046) in the CI. 

However, upon re-scanning the branches, the master branch test was re-run and it appears [that the build is now failing](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/master/410/).

I'd assume that these are probably flaky tests but could somebody please investigate these failures? We're continuing in our effort to [improve the branch builds across APM](https://apm-pipeline-status.app.elstc.co/) so this would be very helpful. :) Thanks!

**Comment by estolfo** [comment]
Yes, we have some flaky tests on JRuby. Thanks for opening this issue, we'll work on getting them more stable.

**Comment by cachedout** [comment]
Thanks, @estolfo 

In looking at our flaky test analyzer, here's a list of tests that we've detected as possible flakes lately if it's helpful:

1. Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-8-jdk#rails-5.2 / Rails integration transactions when json validates the schema – when json
2. Tests / Tests / Ruby:jruby:9.2#rails-6.0 / Rails integration transactions when there are ignored url patterns defined does not create events for the patterns – when there are ignored url patterns defined
3. Tests / Tests / Ruby:jruby:9.2#rails-6.1 / Rails integration transactions when a simple request is made spans action and posts it – when a simple request is made
4. Tests / Tests / Ruby:jruby:9.2#rails-6.1 / Rails integration transactions when there is user information includes the info in transactions – when there is user information
5. Tests / Tests / Ruby:jruby:9.2#rails-6.0 / with breakdown metrics disabled.ElasticAPM::Instrumenter#end_transaction with breakdown metrics disabled skips breakdown but keeps transaction metrics
6. Tests / Tests / Ruby:jruby:9.2#grape-1.5 / #stop.ElasticAPM::Transport::Base#stop stops all workers

**Comment by estolfo** [comment]
oh, this is really helpful. Thanks!

**Comment by mdelapenya** [comment]
Adding more context on this issue, being the case it can be prioritised to keep the build green:

We are seeing this error in the master branch, starting Aug 5th: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp/detail/master/412/pipeline/311

>[2021-08-04T10:31:19.915Z]      NoMethodError:
[2021-08-04T10:31:19.915Z]        undefined method `dig’ for “”:String

@mikker commented on Slack that it seems the ES client has dropped support for an old version of Ruby that doesn’t have the `Hash#dig` method

**Comment by mikker** [comment]
It wasn't that I found out, but I think I've fixed that issue in #1054. Looking at the next errors.

**Comment by cachedout** [comment]
Hi again @mikker and @estolfo . Thank you very much for your recent work on this!

We now have what could be some actual regressions. A number of tests [related to GraphQL](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/master/415/testReport/) have started failing consistently across the past several builds. Here is one example:

https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/master/415/testReport/junit/(root)/a%20query%20with%20an%20Operation%20Name/Tests___Master_Tests_frameworks___Ruby_ruby_3_0_rails_main___GraphQL_a_query_with_an_Operation_Name_adds_spans_and_renames_transaction/history/

**Comment by mikker** [comment]
The GraphQL tests are only on `rails#master` and (should be) marked as allowed failures. Hence they have their own build step. I think it was @v1v who set it up.

There's still a failure in `instrumenter_spec.rb` on JRuby, but I think that's the only one that shouldn't be ignored.

**Comment by mikker** [comment]
As far as I can tell, the `master`/`main` framework branches run as part of the main _Tests_ stage. https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp/detail/master/417/pipeline

They were initially pulled out into their own stage so we could ignore failures in them. We only run them to be aware of upcoming changes in frameworks, but as they are dev branches in active development, they just fail for some periods, which is fine.
