### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by falm** [elastic/apm-agent-ruby#105]
We both used elastic-apm (0.5.1)  and newrelic_agent newrelic in our rails app ( rails 5.1.5, ruby 2.4.1)
and we got bad performance down here, newrelic shows use elastic-apm made 5~10 times slower than before.
![newrelic](https://user-images.githubusercontent.com/1430846/39045721-3c5581ac-44c6-11e8-8ee7-aee8c29d8414.png)

I know the agent status is in BETA , but we still hope someone can help find out what makes the performance down and offer a solution. thanks

**Comment by mikker** [comment]
Hi @falm! That looks pretty crazy. We haven't done much performance testing yet but the agent should of course not have that big of an impact.

For now you might get a quick performance gain by turning on sampling with eg `transaction_sample_rate: 0.5` in your config. Or maybe down to `0.1`. If you try that I'd love to hear your findings.

**Comment by mikker** [comment]
After looking a bit into the performance there seems to be some pretty easy, pretty wins in the stacktrace collection. I'll do that next week. Until then, sampling should help a lot if that really is what's consting you that much. Looking forward to hear how it goes!

**Comment by mikker** [comment]
I've pushed an experimental branch that you can try. It significantly reduces the time spent building the stacktraces for spans. With that and sampling I don't think you'll see such an effect on your response times:

https://github.com/elastic/apm-agent-ruby/tree/stacktrace-perf

Try it out with

```ruby
gem 'elastic-apm', git: 'https://github.com/elastic/apm-agent-ruby', branch: 'stacktrace-perf'
```

Thanks for reporting this!

**Comment by falm** [comment]
@mikker Thanks for your quickly rely. I'll try it next week.

**Comment by mikker** [comment]
I published a new release with these improvements, so you want to use `~> 0.6.2` instead of that branch.

**Comment by mikker** [comment]
Did you have a chance to try out the new version, @falm ?

**Comment by falm** [comment]
@mikker Sorry for delay reply
I tried v0.6.2 in our staging env and the newrelic shows:
![image](https://user-images.githubusercontent.com/1430846/39520681-2d6ff286-4e3e-11e8-942a-b271afbb7872.png)

and used the following settings:
```ruby
    config.elastic_apm.enabled_environments += %w[staging production]
    config.elastic_apm.service_name = 'cube-staging'
    config.elastic_apm.flush_interval = nil
    config.elastic_apm.debug_transactions = false
    config.transaction_sample_rate = 0.1
```
The fix releases although has some performance improve but still cause the requests slower than without using elastic_apm. so the agent still needs performance improve.
I will try that again when the agent ready for production.

**Comment by mikker** [comment]
`config.transaction_sample_rate` needs to be `config.elastic_apm.transaction_sample_rate`. You should also set `flush_interval` to at least a second, probably more.

**Comment by falm** [comment]
@mikker As you say using the following settings
```ruby
    config.elastic_apm.enabled_environments += %w[staging production]
    config.elastic_apm.service_name = 'cube-staging'
    config.elastic_apm.flush_interval = 10
    config.elastic_apm.debug_transactions = false
    config.elastic_apm.transaction_sample_rate = 0.1
```

![image](https://user-images.githubusercontent.com/1430846/39559456-e6518668-4ec8-11e8-931b-47eb88374aae.png)
As above benchmark shows performance got improved. anyway thanks.

**Comment by mikker** [comment]
Thanks for trying it out! Still a bit of overhead, I can see. Looks like it's mainly the purple part of that graph that's growing in size. What do the colors signify?

Thanks for helping out!

**Comment by falm** [comment]
@mikker The purple, orange, yellow part of that graph are both of MySQL select

**Comment by mikker** [comment]
Got it. Thank you again for helping out. I'll keep looking into general performance improvements. I hope this was enough for you for now.
