### ISSUE TITLE
Alpine Linux unsupported host OS 'linux-musl' after update to 4.3.0

### ISSUE THREAD

**Issue by dhagher** [elastic/apm-agent-ruby#1055]
## Describe the bug
After updating elastic_apm to 4.3.0 `CpuMemSet` metrics are disabled and following warning is generated
>WARN -- : [ElasticAPM] Disabling system metrics, unsupported host OS 'linux-musl'

## Steps to reproduce
1. Run the 4.3.0 agent on Alpine Linux
2. Observe generated warning

## Expected behavior
Cpu/mem stats are collected on Alpine Linux

## Environment
- **OS**: Alpine Linux 3.13
- **Ruby version**: 2.7.3
- **Framework and version**: Rails 6.1.4
- **APM Server version**:
- **Agent version**: 4.3.0

## Additional context

Even though `/proc/stat` format is campatible, `ElasticAPM::Metrics.os` is different on Alpine, it can be compared by running

```
$ docker run --rm ruby:2.7.3 ruby -e 'pp RbConfig::CONFIG.fetch("host_os")'
"linux"
```
vs
```
$ docker run --rm ruby:2.7.3-alpine3.13 ruby -e 'pp RbConfig::CONFIG.fetch("host_os")'
"linux-musl"
```

I also believe there is a small typo as `@platform` is written both from `.os` and `.platform` methods
https://github.com/elastic/apm-agent-ruby/pull/1040/files#diff-c860000c007d53325ef70bcb0327722d24de9773e86108b464f8113971bcd4ebR32

**Comment by mikker** [comment]
That's unfortunate. Sorry about that.

Do you think checking against `/^linux/` would fix it, like in my PR above? Is there a list somewhere of possible return values for this?

**Comment by dhagher** [comment]
Thank you for a quick reply,

> Do you think checking against `/^linux/` would fix it, like in my PR above?

It resolves this issue and looks like a reasonable solution however I'm not very familiar with this.
I think that `/proc/stat` is a kernel feature https://www.kernel.org/doc/html/latest/filesystems/proc.html#miscellaneous-kernel-statistics-in-proc-stat so it should work as long as it's running linux.

>Is there a list somewhere of possible return values for this?

To the best of my knowledge the value is taken from Autoconf `config.status` https://github.com/ruby/ruby/blob/ruby_2_7/tool/mkconfig.rb#L32 which in turn is a string provided during the build https://www.gnu.org/software/autoconf/manual/autoconf-2.63/autoconf.html#index-host_005fos-1544 without any fixed list.
As a random example Arch Linux uses `linux-gnu` https://gist.github.com/ignisf/4483735#file-gistfile1-rb-L137

**Comment by mikker** [comment]
```
$ docker run --rm ruby ruby -e "puts Gem::Platform.local.os.to_sym; puts RbConfig::CONFIG.fetch('host_os')"
