### ISSUE TITLE
Problem validating JSON document against schema

### ISSUE THREAD

**Issue by astropanic** [elastic/apm-agent-ruby#111]
~~~
2018-05-07T15:44:25.647+0200    ERROR    [request]    beater/handlers.go:384    error handling request    {"request_id": "f0472126-608a-41b8-81fb-1741d457e632", "error": "Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/transactions/0/spans/1/context/db/statement] S[#/properties/transactions/items/properties/spans/items/properties/context/properties/db/properties/statement/type] expected string or null, but got object"}
~~~

How I should proceed with debugging to find out what the issue is?
What information should I attach?

**Comment by mikker** [comment]
Hi @astropanic ! Thanks for reporting this. What ORM are you using? Is this a Rails app? Are you using Sequel/Mongo/something else? And what version?

**Comment by astropanic** [comment]
Hi @mikker,

Plain Rails with ActiveRecord

**Comment by mikker** [comment]
Can I make you try running `master`? It should be _fixed_. At least the statements should be converted to strings before sending.

I haven't heard of you problem with running both NewRelic and ElasticAPM before (from your support forum post). Is this maybe related?

**Comment by mikker** [comment]
Bump. How do the statements look like if you run master?

**Comment by astropanic** [comment]
I can't issue test runs against our production setup.

We don't run RPM on staging (to compare).

I can install only release gems from rubygems.org due to our rubygems
mirror implementation.

**Comment by mikker** [comment]
Hi again. There's a new version out you could try. Let me know how it works.

**Comment by steve21168** [comment]
I'm receiving this errors on  1.0.0.beta1 gem.

This is a Rails app using Active Record with Postgresql

From the app side the errors look like this:

`apm-server's response: {"error":"Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/transactions/0/spans/13/context/db/statement] S[#/properties/transactions/items/properties/spans/items/properties/context/properties/db/properties/statement/type] expected string or null, but got object"}`

From the APM server side:

`ERROR   [request]       beater/handlers.go:384  error handling request  {"request_id": "60e2fc39-c2f4-43e1-992b-e3fea1741122", "error": "Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/transactions/0/spans/13/context/db/statement] S[#/properties/transactions/items/properties/spans/items/properties/context/properties/db/properties/statement/type] expected string or null, but got object"}`

**Comment by sandrew** [comment]
Same for me
```
[ElasticAPM] POST returned an unsuccessful status code (400)
[ElasticAPM] apm-server's response: {"error":"data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/transactions/0/spans/10/context/db/statement] S[#/properties/transactions/items/properties/spans/items/properties/context/properties/db/properties/statement/type] expected string or null, but got object"}
```
apm-server 6.3.0 and agent 1.0.0.beta1

**Comment by mikker** [comment]
Weird. Are any of you using the Elasticsearch gem?

**Comment by steve21168** [comment]
@mikker Yes we're using the Elasticsearch gem.

**Comment by mikker** [comment]
@steve21168 I think that might be it. Can I make you try with `gem 'elastic-apm', git: 'https://github.com/elastic/apm-agent-ruby', branch: 'fix-es-spans'` ?

It's this one: https://github.com/elastic/apm-agent-ruby/pull/157

**Comment by steve21168** [comment]
@mikker Yeah I'll try that branch and get back to you.

**Comment by steve21168** [comment]
@mikker I think that did the trick. Thanks!

**Comment by mikker** [comment]
Perfect! Thank you for helping out – I'm merging it to master and releasing a beta2. And also making an issue for APM Server to accept objects as _"db"_ statements.
