### ISSUE TITLE
Failed converting event to JSON because of NaN values

### ISSUE THREAD

**Issue by dnasevic-godaddy** [elastic/apm-agent-ruby#1156]
## Describe the bug

I'm seeing some "Failed converting event to JSON" errors in APM logs in Kibana.

## Steps to reproduce

Sample message in the error logs (notice the `NaN` values that cannot be serialized with JSON):

```
"[ElasticAPM] {:metricset=>{:timestamp=>1630572097705853, :samples=>{:\"system.cpu.total.norm.pct\"=>{:value=>NaN}, :\"system.memory.actual.free\"=>{:value=>13053140992}, :\"system.memory.total\"=>{:value=>16509009920}, :\"system.process.cpu.total.norm.pct\"=>{:value=>NaN}, :\"system.process.memory.size\"=>{:value=>1940881408}, :\"system.process.memory.rss.bytes\"=>{:value=>207499264}}}}"
```

## Expected behavior

Don't see errors in Kibana APM logs.

## Environment

- **OS**: LInux
- **Ruby version**: 2.7.4
- **Framework and version**: Rails 6.1.4
- **APM Server version**: 7.13.4
- **Agent version**: 4.3.0

## Additional context

Not sure if you could prevent getting `NaN`s or just not send the request if it failed to get the correct values:

```ruby
>> nan = 0.0/0
=> NaN
>> { a: nan }.to_json
JSON::GeneratorError (865: NaN not allowed in JSON)
```

**Comment by dnasevic-godaddy** [comment]
@mikker I was expecting the latest release (4.4.0) would have the fix for this issue, but I'm still seeing it:

```
[ElasticAPM] Failed converting event to JSON: <ElasticAPM::Metricset timestamp:1636560644144434 transaction:nil span:nil tags:nil samples:{:"system.cpu.total.norm.pct"=>NaN, :"system.memory.actual.free"=>10083381248, :"system.memory.total"=>16185036800, :"system.process.cpu.total.norm.pct"=>NaN, :"system.process.memory.size"=>2008088576, :"system.process.memory.rss.bytes"=>208109568}>
```

From: `/usr/local/bundle/gems/elastic-apm-4.4.0/lib/elastic_apm/logging.rb`.

There is some change though, the value is changed from a hash to raw value:
```ruby
:"system.cpu.total.norm.pct" => {:value=>NaN}
# vs
:"system.cpu.total.norm.pct" => NaN
```

**Comment by mikker** [comment]
Ugh. I'll take a look 👍

**Comment by mikker** [comment]
I've tried again. Let me know if it's still not working.

**Comment by dnasevic-godaddy** [comment]
@mikker Thank you! I'll wait for the official release and will let you know if it's still not working. Thanks!

**Comment by dnasevic-godaddy** [comment]
@mikker This issue is resolved with the newest version. Thanks!

(I see some other errors that happen rarely but they're probably related to request encoding issues and that's fine.)
