### ISSUE TITLE
Segfaulting

### ISSUE THREAD

**Issue by Reinkaos** [elastic/apm-agent-ruby#1223]
## Describe the bug

Hey,

We are experiencing an issue on a few of our Rails apps where the application will segfault because of the elastic apm agent. We have found that the segfaults do not occur when we disable elastic apm. This is then causing our application to crash. 

## Expected behavior

If there is an error with the elastic agent it does not crash the application.

## Environment
- **OS**: Amazon Linux
- **Ruby version**: 2.7.2
- **Framework and version**: Rails 6.1.4
- **APM Server version**: 7.16.2
- **Agent version**: 4.5.0

**Comment by estolfo** [comment]
@Reinkaos I'm sorry to hear about this! Can you send a stack trace, logs and anything else that can show what happened leading up to the segfault?

**Comment by Reinkaos** [comment]
Hey @estolfo, thanks for getting back to me. Yeah sure thing!

Example 1:

```
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":30,"time":"2022-01-20T06:53:32.007+00:00","v":0,"msg":"Request","request":{"method":"GET","path":"/records/34940857","format":"html","controller":"RecordsController","action":"show","status":200,"duration":50.44,"view":4.29,"request_id":"de29361f518f91a5462f3a88b82755d2","params":"{\"locale\"=>\"en\", \"search\"=>{\"i\"=>{\"decade\"=>\"1940\", \"usage\"=>\"Share\", \"year\"=>\"1917\"}, \"page\"=>\"7\", \"recordset\"=>\"all\"}}","user_id":null,"time":4159255.14958669},"tags":["de29361f518f91a5462f3a88b82755d2"]}
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":30,"time":"2022-01-20T06:53:42.375+00:00","v":0,"msg":"Request","request":{"method":"GET","path":"/","format":"html","controller":"RecordsController","action":"home","status":200,"duration":7.6,"view":7.29,"request_id":"675e369106cd8b33d963d8be85911bf0","params":"{}","user_id":null,"time":4159265.56023172},"tags":["675e369106cd8b33d963d8be85911bf0"]}
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":30,"time":"2022-01-20T06:53:43.520+00:00","v":0,"msg":"Request","request":{"method":"GET","path":"/records/31218911","format":"html","controller":"RecordsController","action":"show","status":200,"duration":42.72,"view":4.44,"request_id":"cd8a5472b5e0cae1c41d12992ba29298","params":"{\"locale\"=>\"en\", \"search\"=>{\"i\"=>{\"century\"=>\"1900\", \"decade\"=>\"1960\", \"primary_collection\"=>\"findNZarticles\"}, \"page\"=>\"8\", \"recordset\"=>\"all\"}}","user_id":null,"time":4159266.67065697},"tags":["cd8a5472b5e0cae1c41d12992ba29298"]}
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":50,"time":"2022-01-20T06:54:37.514+00:00","v":0,"msg":"[ElasticAPM] APM Server responded with an error:\n\"{\\\"accepted\\\":0,\\\"errors\\\":[{\\\"message\\\":\\\"queue is full\\\"}]}\\n\""}
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":30,"time":"2022-01-20T06:55:29.427+00:00","v":0,"msg":"Request","request":{"method":"GET","path":"/records/47541051","format":"*/*","controller":"RecordsController","action":"show","status":200,"duration":43.85,"view":4.87,"request_id":"257f1a9711807aaa92eaa0f55f1b5728","params":"{}","user_id":null,"time":4159372.57628647},"tags":["257f1a9711807aaa92eaa0f55f1b5728"]}
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":50,"time":"2022-01-20T06:55:37.417+00:00","v":0,"msg":"[ElasticAPM] APM Server responded with an error:\n\"{\\\"accepted\\\":0,\\\"errors\\\":[{\\\"message\\\":\\\"queue is full\\\"}]}\\n\""}
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":30,"time":"2022-01-20T06:55:42.732+00:00","v":0,"msg":"Request","request":{"method":"GET","path":"/","format":"html","controller":"RecordsController","action":"home","status":200,"duration":7.54,"view":7.18,"request_id":"11c181b4c7a32a487280bcd285a07e49","params":"{}","user_id":null,"time":4159385.91740142},"tags":["11c181b4c7a32a487280bcd285a07e49"]}
{"name":"puma","hostname":"nzresearch-76f559859d-j8s7g","pid":1,"level":50,"time":"2022-01-20T06:55:43.139+00:00","v":0,"msg":"[ElasticAPM] APM Server responded with an error:\n\"{\\\"accepted\\\":0,\\\"errors\\\":[{\\\"message\\\":\\\"queue is full\\\"}]}\\n\""}
/app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/client.rb:46: [BUG] object allocation during garbage collection phase
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0055 e:000054 CFUNC  :new
c:0007 p:0076 s:0050 e:000049 METHOD /app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/client.rb:46
c:0006 p:0022 s:0040 e:000039 METHOD /app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/client.rb:30
c:0005 p:0013 s:0031 e:000030 METHOD /app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/chainable.rb:27
c:0004 p:0034 s:0025 e:000024 METHOD /app/vendor/cache/ruby/2.7.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/connection/http.rb:57
c:0003 p:0011 s:0016 e:000015 METHOD /app/vendor/cache/ruby/2.7.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/connection/http.rb:49
c:0002 p:0016 s:0008 e:000007 BLOCK  /app/vendor/cache/ruby/2.7.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/connection/http.rb:109 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/app/vendor/cache/ruby/2.7.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/connection/http.rb:109:in `block in open_request_in_thread'
/app/vendor/cache/ruby/2.7.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/connection/http.rb:49:in `post'
/app/vendor/cache/ruby/2.7.0/gems/elastic-apm-4.5.0/lib/elastic_apm/transport/connection/http.rb:57:in `request'
/app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/chainable.rb:27:in `post'
/app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/client.rb:30:in `request'
/app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/client.rb:46:in `build_request'
/app/vendor/cache/ruby/2.7.0/gems/http-5.0.4/lib/http/client.rb:46:in `new'

-- Other runtime information -----------------------------------------------

* Loaded script: /app/vendor/cache/ruby/2.7.0/bin/puma
* ```

Example 2:

```
2022-01-20 11:09:31 +0000 HTTP parse error, malformed request ("GET /many-answersyear_level=Senior" - (-)): #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
/app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:26: [BUG] object allocation during garbage collection phase
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0127 p:0033 s:0856 e:000851 RESCUE /app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:26
c:0126 p:0026 s:0848 e:000847 METHOD /app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:25
c:0125 p:0023 s:0840 e:000839 METHOD /app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203
c:0124 p:0024 s:0834 e:000833 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/template.rb:345
c:0123 p:0021 s:0829 e:000828 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/template.rb:152
c:0122 p:0014 s:0818 E:001150 BLOCK  /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/partial_renderer.rb:285
c:0121 p:0010 s:0813 e:000812 BLOCK  /app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203
c:0120 p:0022 s:0810 e:000809 METHOD /app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24
c:0119 p:0023 s:0802 e:000801 METHOD /app/vendor/cache/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203
c:0118 p:0032 s:0796 E:001b78 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/partial_renderer.rb:280
c:0117 p:0058 s:0787 e:000786 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/partial_renderer.rb:271
c:0116 p:0139 s:0778 e:000777 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:81
c:0115 p:0015 s:0768 e:000767 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:27
c:0114 p:0007 s:0762 e:000761 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:22
c:0113 p:0035 s:0756 e:000755 BLOCK  /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/rendering_helper.rb:38
c:0112 p:0089 s:0752 e:000751 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/base.rb:273
c:0111 p:0065 s:0744 e:000743 METHOD /app/vendor/cache/ruby/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/rendering_helper.rb:34
c:0110 p:0009 s:0737 e:000736 BLOCK  /app/vendor/cache/ruby/2.7.0/gems/haml-5.2.1/lib/haml/helpers/action_view_mods.rb:13
c:0109 p:0017 s:0734 e:000733 METHOD /app/vendor/cache/ruby/2.7.0/gems/haml-5.2.1/lib/haml/helpers.rb:93
c:0108 p:0049 s:0729 e:000728 METHOD /app/vendor/cache/ruby/2.7.0/gems/haml-5.2.1/lib/haml/helpers/action_view_mods.rb:13
c:0107 p:0473 s:0722 e:000719 METHOD /app/app/views/pages/index.html.haml:25 [FINISH]
c:0106 p:---- s:0711 e:000710 CFUNC  :public_send
```

Any help is much appreciated.

Thanks

**Comment by estolfo** [comment]
Thanks for this additional information! It appears that the segfault is actually originating in the `http` gem, which the agent uses.

Did something change recently in your application? Did you just start using the agent, have you just upgraded your Ruby version, etc?

**Comment by Reinkaos** [comment]
Hey @estolfo, thanks for your reply!

Nothing has changed recently, we have had this issue for several months and have had a few theories about what causes it but not been able to fix it properly. 

I have had a wider look and it doesn't appear to be happening on our applications that are running ruby 3. Most of our apps are running 2.7.2 and they are the ones that are affected.

Any help is much appreciated!

**Comment by estolfo** [comment]
Hi @Reinkaos thanks for the additional information. How often does this segfault happen?
I checked out the http gem and I didn't see that they have a c extension, so I don't think that their code is the cause of the seg fault. 
Puma, which it seems you use, does have a c extension but it's not possible to tell from the backtrace info which code causes the segfault.
Because the backtraces show the segfault happening in two very different places, it might be caused by the ruby interpreter itself, especially since you say that it doesn't seem to happen on a newer Ruby version.

The only thing I can suggest is that you try opening an issue with puma or with MRI itself. I'm sorry I can't help much more from my side!

**Comment by Reinkaos** [comment]
Hi @estolfo, it's happening reasonably frequently. We have upgraded an app that was running Ruby 2.7 to Ruby 3 and the problem appears to be resolved so we will continue to upgrade our other applications. 

Thanks for your help!
