### ISSUE TITLE
Racecar instrumentation

### ISSUE THREAD

**Issue by ErvalhouS** [elastic/apm-agent-ruby#1228]
[Racecar](https://github.com/zendesk/racecar) works as framework for Kafka consumers, much like Sidekiq for asynchronous jobs.

Basic APM functionality on it makes it less of a black box.

**Comment by estolfo** [comment]
Thanks for the request, @ErvalhouS!

**Comment by jaggederest** [comment]
@ErvalhouS Hi Fernando, I have a draft PR open that I would appreciate some feedback on #1284 - I think it's in a state where it is worth your time to review, if you like.

**Comment by ErvalhouS** [comment]
@jaggederest Great news, I'll have a chance to actually test it tomorrow. Thanks a lot for the effort 😄

**Comment by jaggederest** [comment]
Hey @ErvalhouS any feedback? I believe it should be fully working at this point 👍 Need to fix a test but for your purposes it should be ready to use. Let me know if you have any issues.

**Comment by ErvalhouS** [comment]
@jaggederest Sorry about the delay. I've got that setup in a test and it seems to report the transactions out of the box. Great work you guys 😄

**Comment by jaggederest** [comment]
Woo hoo, that's fabulous to hear, thank you for the feature request and the follow up - it's an underrated part of the open source ecosystem! 🎉
