### ISSUE TITLE
Pin gem dependency versions and use dependabot to update them

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-agent-ruby#1269]
The agent gem (`elastic-apm`) depends on two gems: `concurrent-ruby` and `http`. We need to pin them to a specific version and use dependabot to notify ourselves of newer versions. This is part of our [SLSA](https://slsa.dev/spec/v0.1/levels) compliance effort.

Here is where the changes should be made: https://github.com/elastic/apm-agent-ruby/blob/main/elastic-apm.gemspec#L38-L39

**Comment by jaggederest** [comment]
This is a tricky one. My PR doing this change is failing because the latest version of `http` requires ruby >=2.5 - so we can't pin that version for older versions of ruby e.g. 2.3 and 2.4

The latest version of `http` that supports ruby 2.3 has a CVE in the `addressable` gem 🤔

**Comment by estolfo** [comment]
Good question, I'll look into how to handle this for SLSA and get back to you.
