### ISSUE TITLE
Webmock 3.16.x includes Addressable validation for URLs - breaking nil url handling in agent tests

### ISSUE THREAD

**Issue by jaggederest** [elastic/apm-agent-ruby#1299]
Relevant PR #1298

We need to adjust the tests so that this new behavior from Webmock does not cause issues, and we still can achieve our testing goals. This probably involves changing the tests to either avoid using Webmock in situations where the url will be Nil or changing what is tested (e.g. going deeper into the Agent code to test nil handling, rather than "integration" testing the entire Net::Http instrumentation)

Relevant changes in Webmock: https://github.com/bblimke/webmock/compare/v3.15.2...v3.16.2#diff-99d09d8e9c633be1c28a1f63bfb3277d3b7a6cf62f382cb2e0e8500b6732fb8aR137-R139

Relevant specs that fail when the newer version is used:

rspec ./spec/elastic_apm/spies/net_http_spec.rb:231 # Spy: NetHTTP defaults missing host to localhost
rspec ./spec/elastic_apm/spies/net_http_spec.rb:246 # Spy: NetHTTP supports path being a uri
rspec ./spec/elastic_apm/spies/faraday_spec.rb:167 # Spy: Faraday falls back to localhost when hostname not provided

**Comment by estolfo** [comment]
This is no longer relevant, with this PR https://github.com/elastic/apm-agent-ruby/pull/1303
