### ISSUE TITLE
Logging not working 

### ISSUE THREAD

**Issue by astropanic** [elastic/apm-agent-ruby#133]
With a `config/elastic_apm.yml`

    ---
    server_url: 'http://monitoring.apm:8200'
    log_path: 'log/elastic_apm.log'

I don't see any logs.

Expected behaviour: 

There should be a file named `elastic_apm.log` under `RAILS_ROOT/log` containing the log information for the apm agent.

Used gem is version 0.7.1

**Comment by mikker** [comment]
Hi again @astropanic! Thanks for reporting this. I'll take a look today or tomorrow 👍🏼

**Comment by astropanic** [comment]
@mikker please release a new gem version, I will than give You feedback.

**Comment by mikker** [comment]
Done!

**Comment by mikker** [comment]
Did you try with an absolute path to the log file?

**Comment by astropanic** [comment]
Absolute Path is an bad idea, when the project is moved within the host,
You have to adapt the config file, what is bad, therefore we have
`RAILS_ROOT`

**Comment by astropanic** [comment]
Hi, any follow up how to get it working?

**Comment by mikker** [comment]
Today is a holiday here in Denmark. Will take a look tomorrow 😊

**Comment by mikker** [comment]
There's a new version on Rubygems just for you.

**Comment by astropanic** [comment]
Sorry @mikker , but still no luck.
Can You please reopen this ticket?

With 0.7.3 and a `config/elastic_apm.yml` like:

~~~
---
server_url: 'http://monitoring.apm:8200'
log_path: 'log/elastic_apm.log'
~~~

I don't see the log file being generated.

**Comment by mikker** [comment]
This is Rails?

**Comment by astropanic** [comment]
this is Rails 5.1.4

**Comment by mikker** [comment]
Can you start a console? What do you get if you call `ElasticAPM.agent.config.logger` inside of a Rails console?

**Comment by astropanic** [comment]
sure,

~~~
pp ElasticAPM.agent.config.logger
#<ActiveSupport::Logger:0x0000000005290360
 @default_formatter=
  #<Logger::Formatter:0x00000000052902c0 @datetime_format=nil>,
 @formatter=
  #<Logger::Formatter:0x0000000005291b70
   @datetime_format=nil,
   @thread_key="activesupport_tagged_logging_tags:43290040">,
 @level=1,
 @local_levels=#<Concurrent::Map:0x00000005290158 entries=0 default_proc=nil>,
 @logdev=
  #<Logger::LogDevice:0x0000000005290270
   @dev=#<File:/daten/appsse/serp/releases/20180607073218/log/production.log>,
   @filename=nil,
   @mon_count=0,
   @mon_mutex=#<Thread::Mutex:0x00000000052901f8>,
   @mon_owner=nil,
   @shift_age=nil,
   @shift_period_suffix=nil,
   @shift_size=nil>,
 @progname=nil>
~~~

**Comment by mikker** [comment]
It seems we're overwriting the separate logger with Rails'. I'll take a look.

**Comment by mikker** [comment]
New version for you on Rubygems to try. 🤞

**Comment by astropanic** [comment]
thx @mikker , looks better now, I see the file, and even some content:

~~~
E, [2018-06-07T13:39:44.675549 #63099] ERROR -- : [ElasticAPM] apm-server's response: {"error":"Queue is full"}
E, [2018-06-07T13:39:44.693682 #63121] ERROR -- : [ElasticAPM] POST returned an unsuccessful status code (503)
E, [2018-06-07T13:39:44.693727 #63121] ERROR -- : [ElasticAPM] apm-server's response: {"error":"Queue is full"}
E, [2018-06-07T13:39:49.461785 #63054] ERROR -- : [ElasticAPM] POST returned an unsuccessful status code (503)
~~~

Can be closed ;)

**Comment by mikker** [comment]
Great news! Thank you for helping me debug 😄
