### ISSUE TITLE
[META 739] Add "s3/"-prefix to S3 destination.service.resource

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-ruby#1337]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/739

**Comment by picandocodigo** [comment]
I believe this was completed [here](https://github.com/elastic/apm-agent-ruby/pull/999/files#diff-97ef069fb435aa766e893ce632f5cf8b38f7cc53bbeb2ba3f0215d17287eab3f)?

Resource is defined as:
```ruby
resource = "#{SUBTYPE}/#{bucket_name || 'unknown-bucket'}"
```
And `SUBTYPE` is `s3` in [lib/elastic_apm/spies/s3.rb](https://github.com/elastic/apm-agent-ruby/blob/main/lib/elastic_apm/spies/s3.rb)

**Comment by estolfo** [comment]
@picandocodigo yeah it looks like it
