### ISSUE TITLE
Timeouts from APM server causes a file descriptor leak when HTTP compression is enabled

### ISSUE THREAD

**Issue by matheussilvasantos** [elastic/apm-agent-ruby#1350]
## Describe the bug

After the HTTP request to the APM server gets a time-out, `ElasticAPM::Transport::Connection` cannot close the _write_ pipe because it silently raises `Errno::EPIPE Exception: Broken pipe`.

## Steps to reproduce

1. Configure `ELASTIC_APM_SERVER_URL` so that you can get time-outs
2. Watch file descriptors to grow

## Expected behaviour

The number of file descriptors stays constant and does not grow continuously.

## Environment

- **OS**: Linux
- **Ruby version**: 3.2.0
- **Agent version**: 4.6.0

**Comment by matheussilvasantos** [comment]
I think we have to move the closing of the read pipe on https://github.com/elastic/apm-agent-ruby/blob/main/lib/elastic_apm/transport/connection/http.rb#L121 to `#close` below https://github.com/elastic/apm-agent-ruby/blob/main/lib/elastic_apm/transport/connection/http.rb#L77. I made some tests today, but I'll try to confirm it better tomorrow.

**Comment by estolfo** [comment]
Hi @matheussilvasantos thank you for reporting this and for opening the PR. We'll take a look and get back to you soon!

**Comment by estolfo** [comment]
Hi @matheussilvasantos I'm still trying to wrap my head around why the code is the way it is. I see that you contributed this change a few years go https://github.com/elastic/apm-agent-ruby/commit/6a11c0fe38b63b9d785e8adc718953329c2366b0
Do you remember why you didn't close both the read and write pipes in the ensure block?

**Comment by matheussilvasantos** [comment]
At that time, I should have closed the read pipe where the open PR #1351 is closing now. We need to close the write side before we start to read the pipe; that's why we close it before we join the thread. And we can't close the read inside the thread because we're not sure if the thread will ever execute.

My commit description has some more details - I should have added it to the PR. Here it is:
> We can't close the read pipe inside the child thread because it won't
always be executed, so in cases where some exception happens and prevent
the child thread from being executed, there would be a file descriptor
leak. We shall close the read side of the pipe whether we executed the
child thread or not.

**Comment by estolfo** [comment]
Thanks for explaining 👍
