### ISSUE TITLE
v4.6.1 causes 'Faraday::RackBuilder::StackLocked: can't modify middleware stack after making a request' on reused Faraday::Connection instance

### ISSUE THREAD

**Issue by dmwtf** [elastic/apm-agent-ruby#1376]
## Describe the bug

Upgrade from version 4.6.0 to 4.6.1 causes all our autogenerated OpenAPI clients to fail with 'Faraday::RackBuilder::StackLocked: can't modify middleware stack after making a request' exception.

Further investigation showed that in version 4.6.1 following line of code  

```
   self.response :elastic_apm_middleware, span # middleware
```

was added. (https://github.com/elastic/apm-agent-ruby/compare/v4.6.0...v4.6.1#diff-4b5630a4907f497d4416de76c8dd5a162f4a525222dc3c11bdcef2182a9cdbcdR105)

It adds newly created middleware to the Faraday middleware stack. According to Faraday code the operation is only possible as long as the stack not locked yet.

For first request it's not a problem. Unfortunately our autogenerated clients reuses Faraday::Connection object. It seems like used connection does not unlock the middleware stack after request, so the second usage does not accept (re-?)adding of `elastic_apm_middleware` and raises exception.

## Steps to reproduce

1. Make any HTTP request with active elastic-apm 
2. Make another request using the same Faraday::Connection instance

## Expected behavior

I would expect that usage of already used Faraday::Connection instance does not raise any exception when we activate elastic-apm

## Environment

- **OS**: Linux
- **Ruby version**: 3.1.2
- **Framework and version**: Rails 7.0.4.3 / Sidekiq 7.0.6
- **APM Server version**:
- **Agent version**: 4.6.1

## Additional context

Backtrace:

```
/usr/local/bundle/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:220:in `raise_if_locked'
/usr/local/bundle/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:96:in `use'
/usr/local/bundle/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:242:in `use_symbol'
/usr/local/bundle/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:107:in `response'
/usr/local/lib/ruby/3.1.0/forwardable.rb:238:in `response'
/usr/local/bundle/gems/elastic-apm-4.6.1/lib/elastic_apm/spies/faraday.rb:105:in `block (2 levels) in run_request'
/usr/local/bundle/gems/elastic-apm-4.6.1/lib/elastic_apm/spies.rb:74:in `block in without_net_http'
/usr/local/bundle/gems/elastic-apm-4.6.1/lib/elastic_apm/spies/net_http.rb:42:in `disable_in'
/usr/local/bundle/gems/elastic-apm-4.6.1/lib/elastic_apm/spies.rb:73:in `without_net_http'
/usr/local/bundle/gems/elastic-apm-4.6.1/lib/elastic_apm/spies/faraday.rb:103:in `block in run_request'
/usr/local/bundle/gems/elastic-apm-4.6.1/lib/elastic_apm.rb:302:in `with_span'
/usr/local/bundle/gems/elastic-apm-4.6.1/lib/elastic_apm/spies/faraday.rb:97:in `run_request'
/usr/local/bundle/gems/faraday-2.7.4/lib/faraday/connection.rb:280:in `post'
```

**Comment by krugerman007** [comment]
Same same, please fix!

**Comment by estolfo** [comment]
Closing this issue as v4.6.2, which includes a fix for this, has been released
