### ISSUE TITLE
Faraday Spy causes NoMethodError on timeout

### ISSUE THREAD

**Issue by Haniyya** [elastic/apm-agent-ruby#1386]
## Describe the bug

When a faraday request times out, a `Faraday::ServerError` is raised. Usually these `ServerError`s have a `#response`, but that response is `nil` when a timeout happens. The faraday spy assumes the existence of said response here

```ruby
  # In lib/elastic_apm/spies/faraday.rb:106
              begin
                result = super(method, url, body, headers) do |req|
                  trace_context.apply_headers { |k, v| req[k] = v }
                  yield req if block
                end
              rescue Faraday::ClientError, Faraday::ServerError => e # Faraday::Response::RaiseError
                status = e.response[:status] # NoMethodError here since response is nil
                http = span&.context&.http
```

## Steps to reproduce
1. Setup a client script
```rb
require 'faraday'
require 'elastic-apm'

ElasticAPM.start(service_name: 'Example', logger: Logger.new(STDOUT))

conn = Faraday.new do |conn|
  conn.options.timeout = 2
  conn.response :raise_error
end
response = conn.get('http://localhost:4567/timeout')
```
2. Setup and start a server that times out
```rb
require 'sinatra'

get '/timeout' do
  sleep(5000)
  'Finally!'
end
```
3.  Run client script to see the error

## Expected behavior
The Faraday::ServerError should propagate through the call stack after logging to elastic-apm happened.

## Environment

- OS: linux
- Ruby-version: ruby-3.1.2
- **APM Server version**: 8.7.1
- **Agent version**:  elastic-apm (4.6.2)

**Comment by estolfo** [comment]
Hi @Haniyya thanks for reporting this. I believe it was fixed in [this PR](https://github.com/elastic/apm-agent-ruby/pull/1382). If you are able to test against main and let me know if that fixes the error for you, that'd be great. Thanks!

**Comment by Haniyya** [comment]
Hi @estolfo ! Thanks for the quick response. Looks like the PR you posted fixes the issue. Thanks for the quick response :+1:

**Comment by estolfo** [comment]
Glad to hear it!
