### ISSUE TITLE
http.request.cookies is redacted but Cookie header is not

### ISSUE THREAD

**Issue by fisherking** [elastic/apm-agent-ruby#1402]
## Describe the bug
From the [spec](https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-http.md#http-transactions):

> Captured request and response headers, cookies, and form bodies MUST be sanitised (i.e. secrets removed) according to data sanitization rules.

However, this only happens for the `http.request.cookies` property, not the `Cookie` header.

It's possible to mitigate the issue just by extending `ELASTIC_APM_SANITIZE_FIELD_NAMES` with `cookie` wildcard, but that's different from the default agent behaviour

## Steps to reproduce
It is enough just to inspect any transaction containing `Cookie` header with `session`, or any other sensitive key

## Expected behaviour
One of the following behaviours needs to be implemented:
- removing the `Cookie` header after adding the `cookie` property (like it's done in java agent - [link](https://github.com/elastic/apm-agent-java/blob/main/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/context/SanitizingWebProcessor.java#L63))
- sanitizing Cookie header (like it's done in nodejs agent) 

## Environment

- **OS**: linux
- **Ruby version**: 3.1.2
- **Framework and version**:  6.1.7.3
- **APM Server version**: 7.16.3
- **Agent version**: 4.6.2

**Comment by estolfo** [comment]
Hi @fisherking thanks for opening this issue. Would you mind testing the PR opened here and letting me know if that's a sufficient solution? https://github.com/elastic/apm-agent-ruby/pull/1405
As a workaround, you could also set the [sanitize field names config value](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-sanitize-field-names) to include "cookie" so the cookie in the header will be redacted.

**Comment by radeno** [comment]
I have opposite experience. everything in `http.request.headers.Cookie` is filtered, but I see everything parsed in `http.request.cookies.*`

My configuration part looks like this:
```
sanitize_field_names: "*ookie*,*uth*tion"
```

**Comment by radeno** [comment]
I tried that brach, but i still see parsed cookies. Raw cookie header is filtered

**Comment by gpacuilla-st** [comment]
We're having the same issue as described in OP - with ruby agent 4.7.0.

Using the default settings, the `http.request.cookies.CSRF-TOKEN` (for example) is `[FILTERED]` but the `http.request.headers.Cookie` still contains the complete raw value.

![image](https://github.com/elastic/apm-agent-ruby/assets/146100581/04b08c75-90d9-4b60-b1da-3f181253c214)
