### ISSUE TITLE
undefined method `cause' for #<ActionDispatch::ExceptionWrapper after Rails upgrade to 7.1.0

### ISSUE THREAD

**Issue by annieJL** [elastic/apm-agent-ruby#1430]
## Describe the bug
After upgrading to Rails 7.1.0, we are now seeing `ActionDispatch::ExceptionWrapper` objects coming out with this error in APM:

```NoMethodError (undefined method `cause' for #<ActionDispatch::ExceptionWrapper```

The 'CAUSED BY' displayed in the exception stack trace contains the actual error but this makes it difficult to sift through Rails errors in APM. This is being caused by this [line of code](https://github.com/elastic/apm-agent-ruby/blob/5467b318b9e6ca5cad7f1eb96fbbfdbb54de6d0f/lib/elastic_apm/error/exception.rb#L39C53-L39C53) in `apm-agent-ruby/lib/elastic_apm/error/exception.rb`.

## Steps to reproduce
1. Throw an exception with ActionDispatch::ExceptionWrapper where there is no cause method defined.
2. Review the log in APM and notice that "Error message and culprit" is no longer the expected error thrown but now `NoMethodError (undefined method `cause' for #<ActionDispatch::ExceptionWrapper`.

## Expected behavior
Expect to see exception message that is now displayed in "CAUSED BY" or from `@exception`.

## Environment

- **OS**: Linux
- **Ruby version**:  3.2.2
- **Framework and version**: Rails 7.1.2
- **APM Server version**: 8.11.3
- **Agent version**: 4.7.0

**Comment by xcskier56** [comment]
I saw this a while back in one of my apps and just again today, and had a feeling I had found a fix... turns out I think you just need to upgrade https://github.com/elastic/apm-agent-ruby/pull/1423

**Comment by annieJL** [comment]
> I saw this a while back in one of my apps and just again today, and had a feeling I had found a fix... turns out I think you just need to upgrade #1423

Thank you! We upgraded a few days ago and everything is back to normal! 😅 Appreciate your comment!
