### ISSUE TITLE
How can we configure the Ruby APM agent to set async=true when sending data to the APM Server

### ISSUE THREAD

**Issue by anoopprasad** [elastic/apm-agent-ruby#1482]
Hi Everyone,

I was reading through the [Elastic APM documentation](https://www.elastic.co/guide/en/observability/current/apm-api-events.html#apm-api-events-example) and found that starting from version 8.5.0, the APM Server supports asynchronous processing of batches. According to the documentation, you can request asynchronous processing by setting the `async` query parameter to `true` in the POST request to the `intake/v2/events` endpoint:
```
http(s)://{hostname}:{port}/intake/v2/events?async=true
```
My question is, how can we configure the Ruby APM agent to set `async=true` when sending data to the APM Server?

**Comment by estolfo** [comment]
Hi @anoopprasad what is your use case and ultimate goal of setting `async=true`? The requests to the APM server are done within the internal transport layer of the APM agent, in a background thread. It's not part of the public API of the APM agent so I'm wondering what you're trying to achieve. Let me know!

**Comment by estolfo** [comment]
Hi @anoopprasad Did you see my question above? I'm going to close this issue but you can reopen it if the request is still valid.
