### ISSUE TITLE
Configurable default context & tags for every transaction

### ISSUE THREAD

**Issue by brandonwestcott** [elastic/apm-agent-ruby#164]
Hello, our team has recently setup apm and we are really impressed. @mikker thanks for making the ruby agent a reality!

Wondering if there has been any discussion on setting default context and tags that would be added onto every transaction. In our typical usage of other agent beats, we end up utilizing that "fields" configuration option in order to add global metadata. For example, one common use case for us is to always add the "team/department" shipping the log because we shard our ELK indices by that field for retention / security.

Our first attempt to solve this was to just set those things inside rack middleware, but then once we added in sidekiq, we of course realized that wasn't sufficient for other spies.

Is this something you would be open to adding to the feature set? If so and you are short on time, I would be happy to submit a PR for review.

**Comment by brandonwestcott** [comment]
Yes, these are distinct teams that are "managing" the different apps. And thats just one of many examples too, others include propagating client name, blue/green identifier, and even things like aws_az, etc. 

Something inside config would be perfect. In fact, the middleware I attempted above was actually driven from an `config/elastic_apm_custom.yml`.

**Comment by mikker** [comment]
Kept it to tags in the PR. Tags differ from `custom` in that they are indexed by ES. To your use case I think this makes the most sense. Also lets the ENV-version be simpler in that tags are simple `string=string` pairs.

Hope it's sufficient? 😄

**Comment by brandonwestcott** [comment]
This is great, thank you!

**Comment by lrpauley** [comment]
was support for this feature [removed here](https://github.com/elastic/apm-agent-ruby/commit/13e2a024c3adbd330a2ce3f7685d3d3e5a39e055#diff-3ff0f7dfc745f9ac0268a337d9caf3e0), or maybe it was re-implemented another way?

**Comment by mikker** [comment]
It seems to have been removed by mistake. Total blunder, sorry. I'll re-add it.

**Comment by lrpauley** [comment]
no worries, thanks for getting back to me so quickly!
