### ISSUE TITLE
Faraday and net-http spy issue

### ISSUE THREAD

**Issue by Bugagazavr** [elastic/apm-agent-ruby#184]
Hello, when i use faraday ( which uses `net-http` as default adapter ), i got duplicated spans. But i can't reproduce this with pure `net-http`. It looks like spy catches same request twice when Faraday is used.

How to reproduce:

```rb
require 'elastic-apm'
require 'faraday'

ElasticAPM.start
ElasticAPM.transaction 'Rack', 'request'

conn = Faraday.new(:url => 'https://www.google.com')
response = conn.get '/'

puts ElasticAPM.current_transaction.spans.count
puts ElasticAPM.current_transaction.spans.map(&:inspect)

ElasticAPM.current_transaction.release

ElasticAPM.transaction 'Rack', 'request'

Net::HTTP.get(URI('https://www.google.com'))

puts ElasticAPM.current_transaction.spans.count
puts ElasticAPM.current_transaction.spans.map(&:inspect)
```

Result:

```sh
RACK_ENV=production ruby 1.rb
# 2
# <ElasticAPM::Span id:0 name:"GET www.google.com" type:"ext.net_http.GET">
# <ElasticAPM::Span id:1 name:"GET www.google.com" type:"ext.net_http.GET">
# 1
# <ElasticAPM::Span id:0 name:"GET www.google.com" type:"ext.net_http.GET">
```

**Comment by mikker** [comment]
Thank you for reporting this, @Bugagazavr. I'll see if I can reproduce. The thumb reactions tell me you aren't the only one 🙄

**Comment by mikker** [comment]
This should be solved in the `2.1.1` release from yesterday. Can you confirm?

**Comment by Bugagazavr** [comment]
@mikker Well i need some time to upgrade, thank you for reminder

**Comment by Bugagazavr** [comment]
Looks like APM server 6.5 required?

**Comment by mikker** [comment]
Yes, `gem 'elastic-apm', '~> 2'` is APM Server 6.5+ required.

**Comment by Bugagazavr** [comment]
Confirmed.
