### ISSUE TITLE
Implement Grape instrumentation using ActiveSupport::Notifications

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-ruby#206]
Follows up: https://github.com/elastic/apm-agent-ruby/pull/119

**Comment by n5ken** [comment]
Does 2.x support Grape for now?

**Comment by n5ken** [comment]
Oh, I can see the request from Rack :)

**Comment by mikker** [comment]
Yes, currently you'll have to include the middleware manually. You'll also want to update `transaction.name` at some point during the request.

There's no official way but here's a user submitted example https://github.com/kressh/apm-agent-ruby/blob/e1d8a6d3396021c16c0ca46f2f31c3d0362ac1f3/lib/elastic_apm/middlewares/grape.rb#L37-L54
