### ISSUE TITLE
Add support for Rails.credentials in elastic_apm.yml

### ISSUE THREAD

**Issue by mkemme** [elastic/apm-agent-ruby#212]
Configuration file `elastic_apm.yml `should support ERB expansion so that credentials could be stored in credential store (like in `database.yml`). For example:

`secret_token: <%= Rails.application.credentials.dig(:elastic_apm, :secret_token) %>`

**Comment by mikker** [comment]
Hi @mkemme! I've thought about this. I think you're right as this seems to be a pretty common pattern in yml-based configs.

If you're feeling adventurous PRs are of course welcome 😄

**Comment by mikker** [comment]
Closed by https://github.com/elastic/apm-agent-ruby/pull/288.
