### ISSUE TITLE
Avoid null for optional values in json payloads

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#216]
https://github.com/elastic/apm-server/issues/1410

**Comment by calvinxiao** [comment]
Here is quick fix in my project:

Add the following lines in **config/elastic_apm.yml**

```
framework_name: 'sinatra'
framework_version: '2.0.5'
service_version: '1.0.0'
```

P.S. I am using `gem 'elastic-apm', '2.1.2'`

**Comment by mikker** [comment]
Closing as no consensus was found.
