### ISSUE TITLE
Add sync property to spans

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#226]
https://github.com/elastic/apm-server/issues/1523

**Comment by simitt** [comment]
FYI - this is not yet implemented on the server.

**Comment by mikker** [comment]
Oh, didn't realize. I'll pull it again, I suppose.

**Comment by simitt** [comment]
It shouldn't crash anything, but simply be ignore server side, so you can leave it as is. Just wanted to let you know it is not stored atm, so maybe don't document yet.
