### ISSUE TITLE
Agent not working with rails 5, jruby 9.x and java >= 10

### ISSUE THREAD

**Issue by simitt** [elastic/apm-agent-ruby#250]
The current agent implementation does not work with rails on jruby with java >= 10. Events cannot be sent to the server. Depending on the concrete jruby version either only the sending fails or the app is prevented from starting.  

Tested with:
* `rails 5.2.1`, `jruby 9.1.17` and `java 10.0.2`: the 
```
I, [2018-11-22T12:42:27.118715 #18230]  INFO -- : [aff80606-6e90-4e3f-801b-6de69bf2dc85] [ElasticAPM] Booting 1 workers
W, [2018-11-22T12:42:27.293078 #18230]  WARN -- : [ElasticAPM] Worker died with exception: #<TypeError: illegal access on 'submit': class org.jruby.javasupport.JavaMethod cannot access a member of class java.util.concurrent.Executors$DelegatedExecutorService (in module java.base) with modifiers "public">
```

* `rails 5.2.1`, `jruby 9.2.4` and `java 10.0.2`: the rails app doesn't start at all:
```
LoadError: load error: childprocess/jruby -- java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.io.FileDescriptor sun.nio.ch.FileChannelImpl.fd accessible: module java.base does not "opens sun.nio.ch" to module org.jruby.dist
          require at org/jruby/RubyKernel.java:976
          require at /Users/simitt/.rvm/gems/jruby-9.2.4.0@rails-apm-test/bundler/gems/apm-agent-ruby-6fcf768822f2/lib/elastic_apm/spies.rb:74
```

* [update]: `sinatra 2.0.4`, `jruby 9.2.4`/`jruby 9.1.17`, `java 10.0.2`: 
```
NoMethodError: undefined method `run' for main:Object
                             <main> at /Users/simitt/coding/ruby/sinatra_test_app/app.rb:91
                            require at org/jruby/RubyKernel.java:976
                            require at /Users/simitt/.rvm/gems/jruby-9.2.4.0@apm-sinatra-app/bundler/gems/apm-agent-ruby-6fcf768822f2/lib/elastic_apm/spies.rb:74
```

Steps to fix and ensure java versions are supported
* Update to latest `concurrent-ruby` version after the Issue https://github.com/ruby-concurrency/concurrent-ruby/issues/758 is fixed. There is an open [PR](https://github.com/ruby-concurrency/concurrent-ruby/pull/780). OR
* Figure out which parts of the implementation using the concurrent-ruby gem fail and change implementation.
* Add 3rd dimension to test matrix with different java versions (oracle and openjdk). Adapt the Docker file to not use the default jruby docker images as those are all using java or openjdk 8.

**Comment by alvarolobato** [comment]
The PR https://github.com/ruby-concurrency/concurrent-ruby/pull/780 has been merged and released in 1.1.4, probably that would fix this issue.

Needs testing.
