### ISSUE TITLE
Ruby agent silently fails to deliver data when invalid config option is set.

### ISSUE THREAD

**Issue by simitt** [elastic/apm-agent-ruby#251]
When using an unknown config option in the `elastic_apm.yml` the ruby agent silently fails to deliver data to the APM Server. 
Behaviour exists in versions `1.x` and `2.x`. 

Log entry in a test rails app showed:
```
W, [2018-11-23T16:44:26.719814 #13640]  WARN -- : [f443a45b-1459-47c2-a8b5-42b5ade29815] DEPRECATION WARNING: Leaving `ActiveRecord::ConnectionAdapters::SQLite3Adapter.represent_boolean_as_integer`
set to false is deprecated. SQLite databases have used 't' and 'f' to serialize
boolean values and must have old data converted to 1 and 0 (its native boolean
serialization) before setting this flag to true. Conversion can be accomplished
by setting up a rake task which runs

  ExampleModel.where("boolean_column = 't'").update_all(boolean_column: 1)
  ExampleModel.where("boolean_column = 'f'").update_all(boolean_column: 0)

for all models and all boolean columns, after which the flag must be set to
true by adding the following to your application.rb file:

  Rails.application.config.active_record.sqlite3.represent_boolean_as_integer = true
 (called from require at /Users/simitt/.rvm/gems/ruby-2.5.0@rails-apm-test/bundler/gems/apm-agent-ruby-97a08dfe860c/lib/elastic_apm/spies.rb:74)
```

Expected behaviour would be to gracefully ignore such config options or log an error and stop the ruby agent.

**Comment by mikker** [comment]
Seems `Rails.logger` isn't printing to `$stdout` at this point: https://github.com/elastic/apm-agent-ruby/blob/97a08dfe860c3fe93bc8f5ef59e1687b2b6e0d57/lib/elastic_apm/railtie.rb#L29-L30 so the error and debug logs aren't shown to the terminal. They _are_ written to `log/development.log` though.

So, either we add another configurable `ExtraSpecialBootLogger`™ or we `puts`.
