### ISSUE TITLE
Sequel spy undefined method "log_connection_yield"

### ISSUE THREAD

**Issue by dpankros** [elastic/apm-agent-ruby#256]
When I use the ruby agent 2.0.1 with our rails app, if the sequel spy is enabled I get the following error at startup (e.g. `rails s`):
```
/...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:10: warning: already initialized constant ElasticAPM::Spies::SequelSpy::TYPE
/...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:10: warning: previous definition of TYPE was here
Exiting
/...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:27:in `block in install': undefined method `log_connection_yield' for class `Sequel::Database' (NameError)
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:26:in `class_eval'
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:26:in `install'
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies.rb:36:in `register'
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:45:in `<module:Spies>'
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:7:in `<module:ElasticAPM>'
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies/sequel.rb:5:in `<top (required)>'
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies.rb:74:in `require'
	from /...project-dir.../gems/elastic-apm-2.0.1/lib/elastic_apm/spies.rb:74:in `require'
```

agent is configured with environment variables:
```
ELASTIC_APM_SERVICE_NAME="our-service-name" 
ELASTIC_APM_SECRET_TOKEN="xxxxxxxxx" 
ELASTIC_APM_SERVER_URL="https://apm.our-domain.com:8200"
```

ruby: 2.4.1
rails: 4.2.8
sequel: 4.23.0

The workaround is:
```
ELASTIC_APM_DISABLED_SPIES="sequel,json" 
```

**Comment by mikker** [comment]
Hi @dpankros! Thank you for finding and reporting this. I will take a look at it when I'm back at my desk next week 👍

**Comment by mikker** [comment]
It looks like the Sequel spy is getting loaded twice? Are you loading anything manually? What's your APM config (without the server info of course 😉 )?

**Comment by alvarolobato** [comment]
Hi @dpankros is this issue still happening? can you give us some feedback?

**Comment by dpankros** [comment]
It is still happening if we have Sequel enabled.  I looked into it a couple weeks back and I believe our version of Sequel is old and doesn't include the method that is referenced in the error (`log_connection_yield`), but it does in a later release.  (It's been long enough that I don't remember all the details. sorry.)

Ultimately, I think the fix is to check for the existence of that method before attempting to instrument it or just to stop support for sequel at a newer version than we are using.

**Comment by mikker** [comment]
Hi @dpankros – I'm closing here now. We've decided not to support such old versions of Sequel. Official since https://github.com/elastic/apm-agent-ruby/commit/51ffd033e91f5b5448d486071b3072e8a9d85117. Thanks for trying out Elastic APM anyway!
