### ISSUE TITLE
What's the best way to disallow rails to connect to APM?

### ISSUE THREAD

**Issue by simoniong** [elastic/apm-agent-ruby#258]
as per "enabled_environments" option is removed, so what's the best and recommended way to disable/disallow agent to connect to APM in version 2.0?

**Comment by mikker** [comment]
Hi @simoniong! I suggest you use `disable_send`. That way all the parts of APM will be active and tested in development, so you can see that all the internals work. It just won't send anything to any server.

**Now**, I just yesterday discovered that I'd accidentally removed the actual implementation, so a PR is coming (#257) that re-enables it. I'll do a release today.

I suggest something like:
```ruby
# config/application.rb
  config.elastic_apm.disable_send = !Rails.env.production?
```

**Comment by simoniong** [comment]
Thanks @mikker  can't wait for it!

**Comment by mikker** [comment]
If you're too impatient, you can run it off `master` until the release 😄

**Comment by mikker** [comment]
Release is out – can you confirm that it fixed this for you?

**Comment by simoniong** [comment]
Ya, It works!

**Comment by mikker** [comment]
It is _a_ solution. This good thing about only disabling _send_ is that you have all the other parts running in dev and test and thereby knows if anything breaks.

I don't know your setup but from what you're describing, I think it should be

```ruby
config.elastic_apm.disable_send = !(Rails.env.production? && Socket.gethostname == ENV['ELASTIC_HOSTNAME'])
```

That resolves to only _send_ in production and if the hostname matches.

**Comment by mikker** [comment]
You could also set it via an ENV var that you only provide on the production server, eq `ELASTIC_APM_DISABLE_SEND=true`

**Comment by Kani999** [comment]
@mikker - `This good thing about only disabling send `

How can i turn off `elastic_apm` if the hostname is different then one in the ENV.

I would like to turn off it completely.

**Comment by mikker** [comment]
To turn it off completely, you can remove the gem from your Gemfile or only include it in say production, eq

```ruby
gem 'elastic-apm', group: :production
```

There's not really an easy way other than this to disable APM _completely_ based on the hostname.

**Comment by Kani999** [comment]
@mikker Thanks

We are currently testing this gem, so we want to use it only in development mode for specified hostname.

Thanks for your time and help.
