### ISSUE TITLE
If ElasticSearch is down, APM agent takes down Rails app

### ISSUE THREAD

**Issue by thatdom** [elastic/apm-agent-ruby#262]
We had to update our ElasticSearch server and got surprised that taking down ElasticSerarch will in effect take down our Rails app. App was not responsive, looked like it was waiting for connection on Elastic and each request just "hangs"

Is there any way we can configure APM agent (or APM server) to not take down Rails app? 

I was looking at config. variables, but coudn't find anything related to this.

**Comment by mikker** [comment]
I'm not sure how this could happen. The APM Agent reports to APM Server which then reports to Elasticsearch so there's no direct relation between the agent and ES.

What version of APM Server, the APM Agent, Ruby and Rails are you using?

**Comment by thatdom** [comment]
Thanks for quick response. We're using:
`Ruby: 2.5.3`
`Rails: 5.2.0`
`elastic-apm gem 1.1.0`
`apm-server version 6.5.1`

Let me know if you need anything else.

**Comment by mikker** [comment]
Are you using ES as a data source in your app?

Try updating the agent to the `2.x` series and see if that doesn't fix your problems.

**Comment by thatdom** [comment]
🤦‍♂️ we had logstash-logger and that caused issues. So sorry about this. Thanks again for quick response

**Comment by mikker** [comment]
Don’t be sorry! Glad you found out what it was 😊
