### ISSUE TITLE
Not seeing anything in errors tab

### ISSUE THREAD

**Issue by btoconnor** [elastic/apm-agent-ruby#264]
It's entirely possible I'm missing something really obvious, so if that's the case I apologize in advance.

I'm setting up the APM system on a new Rails 5.2 app.  I've got the APM agent running fine, it sends the spans and traces just fine.  I can view them all in Kibana / ES.  That works great.

The issue is that if I raise an unhandled exception in the code, it doesn't seem to trigger anything in the "Errors" tab in the APM interface like I'd expect.  I just always see "No errors were found".

I can see the erroneous request in the APM viewer itself, and it does see that the response code was "5XX", it just doesn't have any error data with it.

Is there something else that I need to setup in order to get this part of the APM integration working?

Thanks in advance.

**Comment by mikker** [comment]
Hi @btoconnor! Great to hear that APM is working at least 😄 

How are you raising that error? Are you in `production`?

**Comment by btoconnor** [comment]
I am not in production, no.  Just evaluating how these manifest in development to get a feel for the system.

I'm simply doing `raise "foobar"` in my application controller code and hitting the endpoint that generates it.

**Comment by mikker** [comment]
I could be misremembering but isn't Rails doing something in dev to provide it's own exception views? Not sure if it could be it but try settings `config.consider_all_requests_local = false` in your `config/environments/development.rb`.

**Comment by btoconnor** [comment]
Sigh, yep that did it.  Can't believe I didn't realize that :man_facepalming: 

Thanks for the prompt help!

**Comment by mikker** [comment]
I could’ve done the same 😅 so don’t sweat it. Hope you like Elastic APM!

**Comment by sharanraj124** [comment]
Hi @mikker I working in `Sinatra` application in development. we could try elastic ruby apm agent. Transactions and spans captured correctly but error is not captured. pls help for us.

```
D, [2019-10-11T15:10:12.356198 #21976] DEBUG -- :    (6.3ms)  COMMIT
0.5
ArgumentError - Argument is not numeric:
	/apple/development/git/ruby-testing/dbc-sinatra-crud-example/app/controllers/index.rb:16:in `inverse'
	/apple/development/git/ruby-testing/dbc-sinatra-crud-example/app/controllers/index.rb:20:in `block in <top (required)>'
```
