### ISSUE TITLE
bad argument with Faraday

### ISSUE THREAD

**Issue by btoconnor** [elastic/apm-agent-ruby#265]
Hello,

I upgraded to 2.1.1 today and I'm seeing some bizarre new behavior.  If I make a network request using Faraday to an external service, I get `ArgumentError (bad argument (expected URI object or URI string)):`.  I get this through a few separate gems, all the same error.

When I disable `elastic-apm` in the Gemfile, this issue goes away.

Here's an example controller action that I made to isolate the issue:
```ruby
def testapm
    conn = Faraday.new(url: 'https://www.google.com')
    r = conn.get
  end
```

With the apm gem enabled in the Gemfile, that action fails with the bad argument issue.
With the apm gem commented out in the Gemfile, that action proceeds as normal.

Let me know if there's any other information I can provide.

**Comment by btoconnor** [comment]
Sorry, I should have clarified.  This is on a Rails 5.2.1 application.  I see this behavior when navigating to a controller that makes an external request.  I'm not sure if this happens in other contexts as well.

**Comment by btoconnor** [comment]
Yep, master fixes it.

**Comment by kylejginavan** [comment]
Awesome. We are blocked by this issue as well. Any chance we get a gem release soon?

**Comment by mikker** [comment]
@kylejginavan `2.1.2` is out

**Comment by cpgo** [comment]
Hi, I still have this issue.
Using elastic-apm (2.1.2) and rails (5.1.1)

**Comment by mikker** [comment]
Hi @cpgo! Sorry to hear – can you provide more info about your setup? Anything in your `elastic_apm.yml`of note? Anything special in your usage of Faraday?

**Comment by cpgo** [comment]
The `elastic_apm.yml` has only the `service_name` and `server_url` configured.
Faraday error happens inside a spec where I use `Faraday::Adapter::Test::Stubs`

```ruby
let :stubs do
  Faraday::Adapter::Test::Stubs.new
end

def mock_proxy_deploy_service
  mock = Faraday.new do |builder|
    builder.adapter :test, stubs
  end
  allow(Faraday).to receive(:new).and_return(mock)
end

it "crashes" do  
  mock_proxy_deploy_service  
  stubs.delete("/my-api") { [200, {}, {}] }
end

**Comment by cpgo** [comment]
Hey @mikker, sorry to bother you again with this issue, but do you have any ideia of how I could work arround this issue?
I tried downgrading to 2.0.1 but im having issues with "queue is full" that apears to be resolved on newer versions.
