### ISSUE TITLE
Still Having 1024 error

### ISSUE THREAD

**Issue by victorlcampos** [elastic/apm-agent-ruby#266]
Hi People,

I'm sorry if its duplicated, but, even though i update gem to 2.1.1, I'm getting 1024 string error:

`[ElasticAPM] APM Server reponded with an error:
"Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#] S[#/allOf/0] allOf failed\n    I[#/context/request/url/search] S[#/allOf/0/properties/context/properties/request/properties/url/properties/search/maxLength] length must be <= 1024, but got 2173`

Could you help me?

**Comment by mikker** [comment]
Hi @victorlcampos! I seem to have missed a keyword field in the serializer. Will do a fix right away. Thanks for reporting this!

**Comment by victorlcampos** [comment]
Thanks =)

**Comment by victorlcampos** [comment]
Hi mikker,

Thanks for your help, but i thing url.full still not been trancate

`Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#] S[#/allOf/0] allOf failed\n    I[#/context/request/url/full] S[#/allOf/0/properties/context/properties/request/properties/url/properties/full/maxLength] length must be <= 1024, but got 1942`

**Comment by victorlcampos** [comment]
I can open pull request if you prefer

**Comment by victorlcampos** [comment]
My mistake, it's working =)

**Comment by mikker** [comment]
Great to hear!
