### ISSUE TITLE
Not reporting errors

### ISSUE THREAD

**Issue by victorlcampos** [elastic/apm-agent-ruby#268]
Hi guys,

Thanks for helping me with my other issues.

Buy now, i'm getting request with status 500, buy no error:

![image](https://user-images.githubusercontent.com/1539610/49654006-cae80900-fa1d-11e8-9357-60f24ef841b9.png)

![image](https://user-images.githubusercontent.com/1539610/49654019-d2a7ad80-fa1d-11e8-88c7-45b5ba1ac597.png)

**Comment by mikker** [comment]
Hi @victorlcampos – could it be this https://github.com/elastic/apm-agent-ruby/issues/264#issuecomment-444896336 ?

**Comment by alvarolobato** [comment]
Hi @victorlcampos, it's been a while since you created the issue and we haven't heard from you.  Let us know if this issue is still happening and reopen or comment.
