### ISSUE TITLE
Agent not running after httpd restart

### ISSUE THREAD

**Issue by RaphaelVasconcelos** [elastic/apm-agent-ruby#284]
Hi,
after restarting httpd on CentOS 7 the agent stop sending data. 

When I try to run "ElasticAPM.running?" I get "NameError: uninitialized constant ElasticAPM". 

I'm using Rails 4.2.5.2, Ruby 2.2.2, gem elastic-apm 0.7.4 and Passenger.

I appreciate any help

**Comment by mikker** [comment]
Hi @RaphaelVasconcelos! That sounds weird. I don't have much experience with running APM in Passenger but I suppose it should work fine. `0.7.4` is an old version – have you tried upgrading `elastic-apm`?

**Comment by RaphaelVasconcelos** [comment]
> Hi @RaphaelVasconcelos! That sounds weird. I don't have much experience with running APM in Passenger but I suppose it should work fine. `0.7.4` is an old version – have you tried upgrading `elastic-apm`?
> 
> If your APM Server is 6.4, then it's `gem 'elastic-apm', '~> 2'`
> and if it's < 6.4, then `gem 'elastic-apm', '~> 1'`

Hi @mikker! I updated the version to 1.1.0 but the error continues, it's as if the gem was not loaded.

My APM Server is 6.5.2, I have other applications and they are still working well after restarting the app server but they are using Puma

**Comment by mikker** [comment]
Thanks for the update! I'll have to do some poking around with a Passenger setup. I'll update here when I learn more.

**Comment by RaphaelVasconcelos** [comment]
> Thanks for the update! I'll have to do some poking around with a Passenger setup. I'll update here when I learn more.

Thank you for help @mikker ! We will update this troubled apps to puma!

**Comment by RaphaelVasconcelos** [comment]
Hi @mikker 

We found the issue. If you configure your Gemfile like this
```
group :production do
    gem "elastic-apm"
end
```
It's ok! But...this cause the error

```
group :apm do
    gem "elastic-apm"
end
```
The Elastic APM is not initialized

**Comment by mikker** [comment]
Got it! That makes sense. Thanks for getting back to me @RaphaelVasconcelos. Let me know if you run into any more problems.
