### ISSUE TITLE
[APM-CI][Integration test][Ruby] Improve testing framework for JRuby to include different JDKs

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-ruby#287]
After an issue found with JRuby 9.x and JDK >= 10 we should improve how we are testing the different version combination.

@kuisathaverat this is something to keep in mind when migrating to pipelines.

**Comment by alvarolobato** [comment]
@kuisathaverat we need to prioritize this when you have some time.

**Comment by kuisathaverat** [comment]
Which JDKs do we want to test? JDK 7+ to the latest?

**Comment by mikker** [comment]
7 or 8 is probably fine. If you ask me, we don't need every possible combination.

**Comment by kuisathaverat** [comment]
let's start with 7,8, latest-1 (11), latest (12)

**Comment by v1v** [comment]
I managed to create a rough implementation of the JRuby-JDK versions and also asked the owner of the JRuby docker images whether they are interested to use that approach:
- https://github.com/cpuguy83/docker-jruby/issues/50

Running some tests locally to ensure we could potentially create a Pipeline to generate and push those docker images to our internal docker registry.

**Comment by v1v** [comment]
Supported docker images

```
sh run.sh -e 1.7 -a build -r "docker.elastic.co/observability-ci"
 docker images
	Image docker.elastic.co/observability-ci/jruby:9.1-7-jdk           GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-11-jdk          GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-8-jdk           GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.1-7-jdk           GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-11-jdk          GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-12-jdk          GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-13-jdk          GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-8-jdk           GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.1-onbuild         GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-8-jre-alpine    GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.1-7-jre-alpine    GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.1-7-jdk-alpine    GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-13-jdk-alpine   GENERATED  
	Image docker.elastic.co/observability-ci/jruby:9.2-8-jdk-alpine    GENERATED 
```

**Comment by mikker** [comment]
This is really good although we probably don't want to run all of them on every CI build? Which version do you think would make a good default set?

**Comment by v1v** [comment]
That's a good point @mikker, I was not clear with my previous comment, those docker images are available but it doesn't mean the CI build should care about all of them. So far I just enabled:
-  jruby:9.2 with jdk 12
-  jruby:9.2 with jdk 1
-  jruby:9.2 with jdk 8
-  jruby:9.1 with jdk 7

Those details are within the PR: https://github.com/elastic/apm-agent-ruby/pull/403/files#diff-717ed0f3d1dc39a120894a819f9329fc

*NOTE*: jruby:9.2 doesn't support jdk 7

We could potentially include more versions as requested.

Quick update about the current status of this ticket: I'm still working on some Vault issues to pull those docker images from the internal docker registry within the APM-CI server, I'll update this ticket as soon as I get it done

**Comment by mikker** [comment]
Looks like a reasonable bunch 👍

**Comment by v1v** [comment]
Benchmarks for the `jruby:9.2` docker images seem to be failing in the `master` branch and therefore in the PR itself. What should we do?

**Comment by mikker** [comment]
That build is failing weirdly during the benchmarks script, so no worries. I've hit the rebuild button.
