### ISSUE TITLE
Ruby Agent not running in Redmine

### ISSUE THREAD

**Issue by LuanPeixotop** [elastic/apm-agent-ruby#292]
Hi,
I'm trying to run "Elastic APM" in my Redmine application but the gem does not start. I tried with several versions of Redmine / Ruby / Rails but without success.

I'm currently using version 2.1.2 of Elastic_APM; 6.5.2 of Elastic_APM server; Ruby 2.4.5; Rails 4.2.11; 3.4 Redmine; 1.12.2 of Nginx; 3.12.0 of Puma; 1.17.3 of the Bundler and 1.29.7 of the RVM.

When I start the application (either via the foreman, the rails s -e production command or the puma command) it seems that the elastic gem is not loaded with the application (since I can not use the ElasticAPM constant in the rails console (see in the print)).

I tried running with root or a regular user, but both did not work.

I disabled the firewalld and selinux but it did not work either.

Elastic apm is also not creating the logs even though the configuration is set.

And I have other Redmine applications in which ElasticAPM worked (ruby 2.2, rails 4 and passenger) and when the server restarted, Elastic APM stopped working.

I also have other redmine applications that APM is not working. (All with a ruby ​​/ rails version supported by Elastic APM)

I have been trying to solve these problems for weeks, I have already tested infinite configurations and possibilities but without success.

Could you help me?

OBS: My Gemfile, Gemfile.lock, elastic_apm.yml and a print of the problem is attached.

[elastic_apm.yml.txt](https://github.com/elastic/apm-agent-ruby/files/2780565/elastic_apm.yml.txt)
![elasticapm problem](https://user-images.githubusercontent.com/29344516/51500042-bdab9180-1db3-11e9-85fe-79af573e79cd.png)
[Gemfile.lock.txt](https://github.com/elastic/apm-agent-ruby/files/2780566/Gemfile.lock.txt)
[Gemfile.txt](https://github.com/elastic/apm-agent-ruby/files/2780567/Gemfile.txt)

**Comment by mikker** [comment]
Hi! This might be a Passenger and not Redmine issues as it sounds like it's the same as https://github.com/elastic/apm-agent-ruby/issues/284 ?

**Comment by LuanPeixotop** [comment]
I honestly do not know who the problem is, I had problems with ElasticAPM in Passenger and Puma, in different versions of APM, Ruby and Rails. I just talked about Redmine to be a bit more specific about the application I'm running.

**Comment by LuanPeixotop** [comment]
The problem has been resolved with the same solution of #284.
A custom gemfile group caused the error.
Thanks for the support!

**Comment by mikker** [comment]
Thanks for getting back to me on this, @LuanPeixotop! I might need to add a note to the installation docs about gem groups. I'm closing this 👍
