### ISSUE TITLE
Data from the created additional streams are not recorded.

### ISSUE THREAD

**Issue by danilvoe** [elastic/apm-agent-ruby#299]
When executed, the method creates multiple threads to speed up its work.

```
Rails.application.executor.wrap do
    threads << Thread.new do
        Rails.application.executor.wrap do
        Job1
        Job2
        end
    end
    threads << Thread.new do
        Rails.application.executor.wrap do
        Job3
        end
    end
end
```
 
If you record data like this

```
ElasticAPM.start_span('all')
Rails.application.executor.wrap do
    threads << Thread.new do
        Rails.application.executor.wrap do
        Job1
        Job2
        end
    end
    threads << Thread.new do
        Rails.application.executor.wrap do
        Job3
        end
    end
end
ElasticAPM.end_span
```

it turns out to keep the data general, about the time of work.

But if you wrap it like this

```
Rails.application.executor.wrap do
    threads << Thread.new do
        Rails.application.executor.wrap do
        ElasticAPM.start_span('Job1')
        Job1
        ElasticAPM.end_span
        ElasticAPM.start_span('Job2')
        Job2
        ElasticAPM.end_span
        end
    end
    threads << Thread.new do
        Rails.application.executor.wrap do
        ElasticAPM.start_span('Job3')
        Job3
        ElasticAPM.end_span
        end
    end
end
```

there is no data at all. I really want to somehow collect data on individual streams separately, preferably with details of what is happening inside.

Maybe I'm doing something wrong?

**Comment by mikker** [comment]
Hi @danilvoe! I have no experience with Rails' `executor` so I'll have to do some investigation before I can give you a good answer.

Please update this thread if you do any investigation yourself in the meantime.

**Comment by mikker** [comment]
APM's `current_transaction` and `current_span` are thread locals that are automatically inherited, so we'll probably have to do some fidgeting to arrange the parent-child relationships manually when making our own, additional threads.
