### ISSUE TITLE
Custom Instrumentation SpanHelper returns "NameError (uninitialized constant SpanHelpers)"

### ISSUE THREAD

**Issue by silvermind** [elastic/apm-agent-ruby#300]
Can someone verify that the `include SpanHelpers` is working as documented at
https://www.elastic.co/guide/en/apm/agent/ruby/2.x/custom-instrumentation.html

Trying to use the SpanHelper always results in: `NameError (uninitialized constant SpanHelpers)`

How is the SpanHelper suppose to work?
Is there a missing reference in https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm.rb

**Comment by mikker** [comment]
Hi @silvermind! You'll have to require the file with the helpers somewhere manually, eg.
```ruby
require 'elastic_apm/span_helpers'
```

That seems to be missing from the docs – I'll add a note about it. Thanks for finding this.

**Comment by mikker** [comment]
I changed my mind and added the require to the agent, so the helpers are always available as soon as the agent is.

https://github.com/elastic/apm-agent-ruby/commit/4e75e2880b7a14bab3ebc8142ac5753d559014ed
