### ISSUE TITLE
Allow Setting SSL CA Certificate

### ISSUE THREAD

**Issue by marothstein** [elastic/apm-agent-ruby#301]
Without the ability to provide a CA certificate file, the APM agent cannot verify a self-signed server certificate. Without verification, there isn't much point in using TLS at all.

HTTP.rb supports using CA certificates through OpenSSL::SSL::SSLContext, so all the agent needs is to take an `ssl_context` in as an optional parameter and pass it in to HTTP.rb.

**Comment by trojanc** [comment]
If only we got this for the java agent too...

**Comment by eyalkoren** [comment]
I believe https://github.com/elastic/apm-agent-java/issues/338 refers to this. It's on the radar...
