### ISSUE TITLE
Add CONTRIBUTING file

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-ruby#307]
Add a contributing.md file

**Comment by mikker** [comment]
Thanks @bmorelli25! To be clear: Will you add one or do you want me to?

**Comment by bmorelli25** [comment]
Sorry, should've added more context. I'll create an outline from what the other agents have done and I'll need you to add in a few Ruby specifics and edit it to how you prefer people to contribute

**Comment by mikker** [comment]
Sounds great – thanks!
