### ISSUE TITLE
ElasticAPM booting with disable_send true in Rails 4

### ISSUE THREAD

**Issue by marutinandanpandya** [elastic/apm-agent-ruby#311]
Hi, 
I have configured elastic_apm to run for rails, sending metrics only for the production environment and not for other (dev/test) environment.

config/elastic_apm.yml 
```
server_url: http://localhost:8200
secret_token: ''
```

config/environments/production.rb
```
Rails.application.configure do...
  config.elastic_apm.disable_send = false
end
```

config/environments/development.rb
```
Rails.application.configure do...
  config.elastic_apm.disable_send = true
end
```

Gemfile
```
ruby '2.3.5'
gem 'rails', '4.2.10'
gem 'elastic-apm', '2.3.1'
```

**My issue is that it is still trying to boot 1 worker process in development (as listed in logs). Is this an expected behaviour? Will it still prepare a worker even if it does not needs to send metrics?**

logfile  log/development.log
```
I, [2019-02-12T08:47:55.361841 #7833]  INFO -- : [ElasticAPM] [2.3.1] Starting agent, reporting to http://localhost:8200
I, [2019-02-12T08:48:09.393621 #8175]  INFO -- : [ElasticAPM] Booting 1 workers
I, [2019-02-12T08:48:09.900609 #8124]  INFO -- : [ElasticAPM] Booting 1 workers
I, [2019-02-12T08:48:13.661650 #8292]  INFO -- : [ElasticAPM] Booting 1 workers
I, [2019-02-12T08:48:25.406918 #7833]  INFO -- : [ElasticAPM] Booting 1 workers
I, [2019-02-12T08:48:27.921303 #8499]  INFO -- : [ElasticAPM] [2.3.1] Starting agent, reporting to http://localhost:8200
```

**Comment by mikker** [comment]
Yes, this is expected. `disable_send` only disables the _sending_ of events. They are still tracked and recorded. This is how I'd recommend doing it, as any errors (except connection errors) will pop up in dev and test before (hopefully) they reach production.

If you want to disable instrumenting there's also the option `instrument: false`.

**Comment by mikker** [comment]
An option to disable just the (system) metrics is in the works, if that's what you mean by metrics?

**Comment by marutinandanpandya** [comment]
Thanks, that answers the doubt.
