### ISSUE TITLE
Transactions may not be nested. Already inside #<ElasticAPM::Transaction:0x007f86f2dca688>

### ISSUE THREAD

**Issue by sudostack** [elastic/apm-agent-ruby#319]
Making attempts to utilize library with Grape (as you guys don't yet have support for it) and created a fork that updates the transaction name and contextualizes to Grape with an update to the middleware in this library. I kept getting the following error and assumed that it was an issue with the code that I've added and decide to just rollback all my changes and use the library as is, but the same exception is being raised. I feel like this is a deeper/existing issue with the library -- perhaps it's not updated to utilize the new APIs in the doc, but it's a little more burdensome for me to dig into right now to suss out the issue:

```ruby
Transactions may not be nested. Already inside #<ElasticAPM::Transaction:0x007f86f2dca688>
```

**screen**:
<img width="1036" alt="screen shot 2019-02-15 at 4 06 52 pm" src="https://user-images.githubusercontent.com/861147/52890909-30eabe00-313c-11e9-8d5f-c77ab0cc16c6.png">

**Comment by mikker** [comment]
If you are already using the middleware, then requests are already wrapped in transactions and that's why you get this error.

An approach you could take instead is to update the name of the current, already running transaction.

For example

```ruby
if (transaction = ElasticAPM.current_transaction)
  transaction.name = get_name_from_grape_somehow
end
```
