### ISSUE TITLE
Don't boot in Rails' console

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#329]
Should we perhaps try and detect when the app starts into a `rails console` and not boot?

The data isn't really useful nor representative of the app's health. I don't think anyone would actually want it running in consoles (?)

**Comment by simitt** [comment]
Are there any issues having the agent run in the console? I imagine this mostly happens in dev environment where the agent is probably deactivated anyways. If activated somebody might want to use it to try out performance of code snippets (purely an assumption).

**Comment by mikker** [comment]
I often have long-running consoles for my production apps too. Biggest issue is they pollute the output a bit with logs – and now they're also reporting metrics.

**Comment by simitt** [comment]
Is it possible to pass in an env variable to set [`disable_send=true`](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-disable-send) when starting the console? I think this would be the most flexible handling, as users could decide themselves if they want it to be monitored or not.

**Comment by mikker** [comment]
That wouldn't stop the logs.

Nothing get's tracked anyway because nothing is wrapped in Transactions.

I think we should just skip `ElasticAPM.start` if we detect console. If the user wants to test the agent in a console, they can easily just run that method themselves. Or have it run in an `.irbrc` or something if they want it on always.

**Comment by simitt** [comment]
oh ok, I thought everything would be inside a transaction. 

In that case, agree that it doesn't make sense to pollute the logs.

**Comment by mikker** [comment]
Apparently as easy as https://stackoverflow.com/a/4604079/291503
