### ISSUE TITLE
Custom Instrumentation returns "NameError (uninitialized constant SpanHelpers)"

### ISSUE THREAD

**Issue by slashd0t** [elastic/apm-agent-ruby#331]
Hi, I'm running a simple Rails application and try to add a custom instrumentation in my Dashboard class. See the code below.
My current setup:
Elastic Ruby APM version 1.0
Ruby 2.3
Rails version 4

I already add this line **require 'elastic_apm/span_helpers'** in application.rb, or in dashboard_controller.rb but the SpanHelpers is not called.

How should we use the SpanHelper for custom instrumentation ?
```
# require 'elastic_apm/span_helpers'  # <-- not working also
class Dashboard
  # include SpanHelpers  # <-- # error, will return NameError (uninitialized constant Dashboard::SpanHelpers):

  attr_reader :user, :posts, :tag, :filter

  def initialize(user: nil, posts: nil, tag: nil, filter: nil )
    @user = user
    @posts = posts
    @tag = tag
    @filter = filter
  end
  span_method :initialize

  def featured_tags
    Tag.where(featured: true)
  end

  def following_tags
    user.following_tags unless user.nil?
  end
end
```

**Comment by mikker** [comment]
The line should read

```ruby
extend ElasticAPM::SpanHelpers
```

This was missing from the docs – I've updated them in https://github.com/elastic/apm-agent-ruby/commit/942aed14f415cb0411ba4e946a5b548c40084640

Apologies and good luck with the dashboard 😊

**Comment by mikker** [comment]
Closing. If the above didn't fix your problem, feel free to open again.
