### ISSUE TITLE
ELASTIC_APM_ENABLED_ENVIRONMENTS is not working

### ISSUE THREAD

**Issue by jalberto** [elastic/apm-agent-ruby#333]
I am exporting `ELASTIC_APM_ENABLED_ENVIRONMENTS=production` and running `rails console` still I can see messages related to APM booting and logs polluting my console

**Comment by jalberto** [comment]
even if I add `group: :production` to the gemfile, it boots :/
 
`[app][development] main:0> [ElasticAPM] Booting 1 workers`

**Comment by mikker** [comment]
Hi @jalberto! `ELASTIC_APM_ENABLED_ENVIRONMENTS` was remove in version 2.0. 

The only way to completely disable booting the agent is to omit it from your Gemfile. I don't know why it boots anyway in your setup – are you requiring it manually anywhere?

With Metrics recently added this has become an issue and I've opened up a discussion to perhaps disable the agent completely in Rails' console (#329). Also I think we should change the log level of those worker logs to `DEBUG`.

What do you think?

**Comment by jalberto** [comment]
The doc needs to be updated then because still that environment var is mentioned.
You are right I found an explicit `include` in my code, still, I would expect a way to disable the agent (not the code), but after I added a conditional (using `#defined?`) still, have the same behaviour

IMHO:
- we should be able to decide in which environment the agent should boot (like mostly APM agents out there)
- it should never run in the console if not specified
- is a good idea to set the logs to `debug` but mostly dev envs are in `debug` by default anyway

**Comment by mikker** [comment]
I agree. I'll add an option `active` (to align with our other agents in other langs). If `false` it won't boot the agent automatically (like now).

Then, when that's in there we can use it and set it to false if we detect console.

Thanks for helping out 👍

**Comment by jalberto** [comment]
thank you for the quick help @mikker :)
