### ISSUE TITLE
Pass Web Transaction In Worker thread??

### ISSUE THREAD

**Issue by tmedford** [elastic/apm-agent-ruby#342]
We have an rails app with an sync api the creates background jobs lasting a few seconds in separate worker but is still part of the web request. We extract out the current transaction from the controller and pass that to worker via redis. We then try to restart the transaction in worker through the trace context from web, but we never see any of the worker tracer. So we get a big blank spot in tracelog. What is proper way to pass the transaction from the parent web process, to background worker?  

    context = ElasticAPM::TraceContext.parse(Redis.current.get('xxxxxx'))
    ElasticAPM.start_transaction '1111', '3333', trace_context: context
     worker code
    ElasticAPM.end_transaction 

![image](https://user-images.githubusercontent.com/4482381/53689587-4b6d8b80-3d27-11e9-9f28-76ccba2bfe28.png)

**Comment by prashantvithani** [comment]
@tmedford Did you find any workaround for this issue?

@mikker Is there any way to connect the `current_transaction` in the new threads spawned or in `Concurrent::Future` to instrument the code inside?

**Comment by prashantvithani** [comment]
Any update here?

**Comment by mikker** [comment]
No, sorry not yet. But this is something we should of course support. I'll create an issue.

**Comment by tmedford** [comment]
We extracted out the current transaction or current span context and pass it with worker args. Then in worker we start transaction like so. 
    ElasticAPM.start_transaction('WorkflowExecute', 'resque-worker', trace_context: ElasticAPM::TraceContext.parse(args['trace_context'])) if defined?(ElasticAPM) && ElasticAPM.running? && args['trace_context'].present?
