### ISSUE TITLE
setting `metrics_interval` to 0 causes failures during `at_exit` block

### ISSUE THREAD

**Issue by dunedain289** [elastic/apm-agent-ruby#346]
I've disabled the metrics because of other issues, but that causes my test suite to exit with an exception during an `at_exit` block and fail in my CI environment. I tracked it down to the Collector not skipping its shutdown steps in this case, so I fixed with the following Rails initializer monkey-patch temporarily:

```ruby
module DisableAPMMetrics
  def stop
    return unless running?

    super
  end
end

ElasticAPM::Metrics::Collector.send :prepend, DisableAPMMetrics
```

**Comment by mikker** [comment]
Hi @dunedain289. This looks like a legit bug. Thanks for reporting – I'll see what I can do.
