### ISSUE TITLE
Ruby agent is sending null value for system.memory.actual.free metric

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-ruby#348]
> Problem validating JSON document against schema: I[#] S[#] doesn't validate with "metricset#"\n I[#] S[#/allOf/0] allOf failed\n I[#/samples/system.memory.actual.free/value] S[#/allOf/0/properties/samples/patternProperties/%5E%5B%5E%2A%22%5D%2A$/properties/value/type] expected number, but got null [{"metricset":{"timestamp":1551731942101587,"tags":null,"samples":{"system.cpu.total.norm.pct":{"value":0.0036826247070639436},"system.memory.actual.free":{"value":null},"system.memory.total":{"value":3127721984},"system.process.cpu.total.norm.pct":{"value":0.0013391362571141614},"system.process.memory.size":{"value":360566784},"system.process.memory.rss.bytes":{"value":166002688}}}}]

OS is Debian, Wheezy. Wheezy has Linux kernel 3.2, which does not include `MemAvailable` in /proc/meminfo. The Go agent uses go-sysinfo, which caters for older kernels by substituting `free + buffers + cached` for `available` if the latter is unavailable.

**Comment by mikker** [comment]
Thanks for debugging, @axw! I'll add a fix first thing monday.

**Comment by Jack-Judge** [comment]
This was reported by a customer. If the fix is added Monday would they have to wait until it's incorporated into a general release ?

**Comment by mikker** [comment]
No, the agents can do releases independently of the common release schedule. I already had a release planned for Monday.

**Comment by mikker** [comment]
So to clarify: the customer would have to update their gem version Monday after the release is out. I’ll update this issue when it is.

**Comment by Jack-Judge** [comment]
@mikker Was this fixed in #351 ? Is the customer okay to run an update now ? Thanks

**Comment by mikker** [comment]
Yes it was! Sorry I forgot to notify you.
