### ISSUE TITLE
Add "Performance tuning" docs

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#350]
https://github.com/elastic/apm/issues/66

cc @bmorelli25 -- Is it correct that this is something I should write and not something you will do?

**Comment by bmorelli25** [comment]
Yes, you'll need to create the first draft for this doc. Even bulleted ideas would work, I can handle the formatting if you'd like.

**Comment by saviogl** [comment]
:+1:

**Comment by estolfo** [comment]
Some tips to add: 
- Try disabling stacktraces with span_frames_min_duration: 0
- Stacktraces are the most expensive thing the agent does, performance wise
- If you're doing custom span, you can also disable it with the argument include_stacktrace: false to keep them on for errors, auto-instrumented things, etc
