### ISSUE TITLE
BUG - APM Changing/Breaking WWW-Authenticate Response Headers 

### ISSUE THREAD

**Issue by tmedford** [elastic/apm-agent-ruby#353]
The Elastic APM is changing the response header of WWW-Authenticate. We can see this based on curl. This is breaking integrations
![image](https://user-images.githubusercontent.com/4482381/54572106-22522980-49bc-11e9-9c27-bfdbf9e773f8.png)

![image](https://user-images.githubusercontent.com/4482381/54572580-b8874f00-49be-11e9-823d-7184eebe564e.png)

**Comment by wxwang33** [comment]
+1

**Comment by inglemr94** [comment]
+1

**Comment by tmedford** [comment]
Confirmed, after removing APM headers are no longer altered giving correct prompts.

**Comment by mikker** [comment]
I think what it might actually be changing are form data?

Can you try the branch from my fork this PR https://github.com/elastic/apm-agent-ruby/pull/354 ?

On my phone right now. Will do some more testing in an hour or two.

Thank you for finding and reporting this!

**Comment by tmedford** [comment]
@mikker Bump release? Also the apm was not modifying form data. The test was a curl to a get endpoint with auth and apm was changing the returned headers.

**Comment by mikker** [comment]
Yes, I found that out later. Thanks again for reporting and using Elastic APM!
