### ISSUE TITLE
Change Defaults

### ISSUE THREAD

**Issue by tmedford** [elastic/apm-agent-ruby#355]
We are looking to add elastic apm into our base distributed gem for microservices and wanted to set defaults for applications. Applications could override the defaults our custom gem sets (that includes elastic apm). Not sure how to get this done given the 4 ways to set variables but the goal is that we dont have to go into each application to change 1 variable, it could be part of our normal distributed gem.

**Comment by mikker** [comment]
Hi @tmedford. There's no official way to do exactly what you are describing. If you're willing to add a little bit to every service you could come close with something like this:

Rails:
```ruby
# config/application.rb
module Whatever
  class Application < Rails::Application
    # ...
    config.elastic_apm.merge!(SharedGem.elastic_apm_defaults)
  end
end
```

Others:
```ruby
# where ever you do your ...
ElasticAPM.start(SharedGem.elastic_apm_defaults.merge(local_options: ...))
```

Would that work?
