### ISSUE TITLE
Environment variable ELASTIC_APM_CONFIG_FILE ignored?

### ISSUE THREAD

**Issue by ste26054** [elastic/apm-agent-ruby#362]
Hello,

The environment variable `ELASTIC_APM_CONFIG_FILE` is documented in https://github.com/elastic/apm-agent-ruby/blob/7f8063711822678b03df4b43cb7d2292ff71926a/docs/configuration.asciidoc, yet I can't find use for this variable anywhere in the code. 

Is this deprecated or not yet implemented?

Best regards

**Comment by mikker** [comment]
You're right! I'm sorry – a fix is underway. Thanks for reporting this.

**Comment by ste26054** [comment]
So fast, thanks!
