### ISSUE TITLE
Restart APM agent with different config after rails application has booted?

### ISSUE THREAD

**Issue by ste26054** [elastic/apm-agent-ruby#364]
Hello,

I am developping a module for a Rails application, where I have several constraints:
- `elastic_apm.yml` is in a custom location
- The module is loaded **after** rails initialization, so making changes to `config.elastic_apm` has no effect

So my plan was the following:
- Stop the running agent
- Change the configuration 
- Start the agent again

The thing is, as soon as I stop the agent, all of its configuration is "lost". When I start it again with the configuration file provided, Elastic receives correctly the data (so the configuration is read correctly), but the app appears as a generic `Rack` application, not as a Ruby on Rails one so I can't really use it easily in Kibana.

I tried the following:

```ruby
  ElasticAPM.stop
  ElasticAPM.start(config_file: '/custom/path/elastic_apm.yml',
                   framework_name: 'Ruby on Rails',
                   framework_version: Rails::VERSION::STRING,
                   logger: Rails.logger)
```

Is there a way to "restart" properly without loosing the initial configuration?

**Comment by ste26054** [comment]
So once https://github.com/elastic/apm-agent-ruby/issues/362 is resolved, I have a way to fix this 😄 
But I still would like to know if there is a workaround through code as well,

Thanks

**Comment by mikker** [comment]
The config object has a special initializer that sets a few service specific things during the Railtie: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/config.rb#L202-L211

So in your case you could include an `app: YourApp::Application` when you (re)start the agent.

**Comment by mikker** [comment]
Here are the two Rails-specific things that happen in the Railtie. This is what you're missing when you start the agent on your own: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/railtie.rb#L13-L18

**Comment by ste26054** [comment]
Awesome, thanks!

I also had to add the `attach_subscriber(agent)` from the Railtie to make it work properly

**Comment by mikker** [comment]
Good catch, yes! Thanks for using Elastic APM 🙌
