### ISSUE TITLE
Can we use a sidekiq job to send metric as alternative to threads? 

### ISSUE THREAD

**Issue by OpakAlex** [elastic/apm-agent-ruby#371]
I think it will be so good to have an alternative way to sends data to APM server. Just to use a sidekiq job. I think almost our issues in production env happens via threads. Ruby it's not a java or something which good works into threads. So can we do this? @mikker ?

**Comment by mikker** [comment]
There's no way to do this right now and my estimation is that it would be a large(ish) undertaking to add/change.

The APM Server API works via HTTP streaming which isn't necessarily easier to do via a background process.

**Comment by OpakAlex** [comment]
"The APM Server API works via HTTP streaming which isn't necessarily easier to do via a background process." - maybe only for your localhost project. But for our production and production ather guys it does't work like this. This is idea just to find good way, because our company so near to remove apm too. Same as another guys.
