### ISSUE TITLE
Agent configuration for Sneakers

### ISSUE THREAD

**Issue by lbernardelli** [elastic/apm-agent-ruby#373]
Hi there,

I have a particular case that is only running sneakers in spite of this is a rails project. So when I start sneakers by "bundle exec rake sneakers:run" the agent is not starting. Which is the best way to cover this case?

**Comment by mikker** [comment]
Hi!

I don't know Sneakers but it looks like something we'd be fine with supporting. I can't give you any tips on what to do, as I don't know the Sneakers internals but if you want to give it shot, you can peek at the Sidekiq and DelayedJob integrations for inspiration. PRs are always welcome if you get so far 😊

You're also very welcome to update this issue with whatever you might find out if you dig deeper.

It'll be a little while before I have time to look at it myself.

Thanks!

Sidekiq: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/spies/sidekiq.rb
DelayedJob: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/spies/delayed_job.rb

**Comment by estolfo** [comment]
Sneakers support was added in https://github.com/elastic/apm-agent-ruby/pull/676 so I'll close this.
