### ISSUE TITLE
Missing transactions on stopping

### ISSUE THREAD

**Issue by MMartyn** [elastic/apm-agent-ruby#374]
We've notice some transactions not getting reported and I believe I tracked it to this code snippet: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/transport/worker.rb#L45 where it doesn't attempt to clear out the queue prior to stopping. I am wondering should it, or was that intentional?

**Comment by mikker** [comment]
Indeed it looks like we could at least try to wait for an empty queue before shutting down. I'll look into it – PRs are welcome if you have anything in mind 😊

**Comment by MMartyn** [comment]
Alright cool, I’ll start mulling over how to go about it. Just wanted to make sure I wasn’t missing something that would make it infeasible.

**Comment by mikker** [comment]
Can I ask you to upgrade your agent to the most recent version (2.8.0 right now) and check if this still happens? I think this should be fixed. Thanks!

**Comment by mikker** [comment]
Closing this as I suspect it is fixed with the transport rewrite. Feel free to reopen if you see it happen again.
