### ISSUE TITLE
Agent should support setting Numeric and Boolean tags

### ISSUE THREAD

**Issue by loglesby** [elastic/apm-agent-ruby#377]
APM Server now supports adding Transaction tags that are numbers or bools - that agent should support this. For instance we are currently recording the amount of memory used in a transaction and taggging it, but these values are sent to ElasticSearch as Strings and thus we cannot perform numeric aggregations on them.

**Comment by mikker** [comment]
Hi @loglesby. Of course it should! I'll ask around about backwards and forwards compatibility, but sure! What a great use. If you can share, I'd love to see the code that makes it work?

**Comment by loglesby** [comment]
Yes, it's very crude actually... but it's much better than nothing! We're using Sinatra, so we just use the `schneems/get_process_mem` gem to get the process memory in our base controller's `before` hook, store it as a property, then get the value again in the `after` hook and subtract one from the other:

```ruby
class ApplicationController < Sinatra::Base
  before do
    # measure memory used by each request
    @get_mem = GetProcessMem.new
    @memory_bytes_initial = @get_mem.bytes
    @memory_mb_initial = @get_mem.mb
    ...
  end

  ...

  after do
    ElasticAPM.set_tag(:memory_bytes_used, (@get_mem.bytes - @memory_bytes_initial).round)
    ElasticAPM.set_tag(:memory_mb_used, (@get_mem.mb - @memory_mb_initial).round)
  end
end
```
