### ISSUE TITLE
NameError - uninitialized constant ElasticAPM::Spies::NetHTTPSpy

### ISSUE THREAD

**Issue by timogoebel** [elastic/apm-agent-ruby#381]
Because of #379, we have disabled the `NetHTTPSpy`. However, the APM code (I believe the Faraday Spy) still tries to resolve the constant. This causes a `NameError - uninitialized constant ElasticAPM::Spies::NetHTTPSpy` error.

**Comment by mikker** [comment]
Ah, gotcha. I'll see what I can do.
