### ISSUE TITLE
Capture Ruby runtime metrics

### ISSUE THREAD

**Issue by nehaduggal-zz** [elastic/apm-agent-ruby#387]
Ruby agent to capture runtime metrics to help visualize the impact of underlying infrastructure in context of the application.

Metrics to be captured by the Ruby agent: 
- Time in Garbage collection 
- Frequency of GC
- Memory usage
- Thread count
	

APM Meta issue: https://github.com/elastic/apm/issues/73

There should be a dashboard for all these metrics in apm-contrib repo.

**Comment by mikker** [comment]
Closed by #487
