### ISSUE TITLE
[docs] Remove duplicate context section

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-ruby#388]
There's a duplicate context section at the end of `api.asciidoc`. Opening this in case someone is looking for a good first issue. If not, I'll fix this when I have some downtime later in the week.

**Comment by michal-granec** [comment]
Hi, if you haven't fix it already, I would gladly help with this issue 👍

**Comment by bmorelli25** [comment]
👋@michal-granec, that'd be awesome!

For extra clarification, this is the section I'm talking about: https://www.elastic.co/guide/en/apm/agent/ruby/current/api.html#api-context

Let me know if you have questions

**Comment by michal-granec** [comment]
I have created PR #405, so you can have a look :)
