### ISSUE TITLE
Remove `root.span` from the span payload

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-agent-ruby#39]
We want to not show the `root.span` "app" as a span in the Timeline view in the Elastic APM UI. Here's a current example;

![screenshot 2018-01-15 11 27 57](https://user-images.githubusercontent.com/4104278/34938130-71f81a10-f9e7-11e7-973f-1e26ae27b7b5.png)

**Comment by mikker** [comment]
So there's no `span` covering the entire transaction?

**Comment by mikker** [comment]
:+1:

**Comment by mikker** [comment]
This isn't actually a root span as much as it is how Rails works. So the only way to remove that one giant span is to avoid instrumenting controller actions which I don't think we want.

Depending on how much you want to get rid of that bar I'm not sure it's the right choice to remove it?

**Comment by mikker** [comment]
I'll experiment a bit. But it seems like a weird choice.

**Comment by formgeist** [comment]
The reason we've opted to not show it in the UI is because it's superfluous, also never carries any detail information. The length of the root span is the same as the transaction itself (which is clearly indicated in the x-axis), while most other spans will carry detail information and be more interesting to look at. It just nags us/me that we leave space for something that's clear repeated. But then again, my knowledge on the instrumentation and how Rails should show up is very sparse - so I'd leave it if you feel strongly about keeping it in. It's just the only agent that does it compared to Node, Python and JS.

**Comment by mikker** [comment]
I get it. Sound like a good point. Not sure how removing it will affect everything else. I'll look into it 👍

**Comment by mikker** [comment]
Closing as these aren't actually root spans in the original sense.
