### ISSUE TITLE
Default port mismatch between agent and APM Server

### ISSUE THREAD

**Issue by moarpheus** [elastic/apm-agent-ruby#402]
Hello gents,

Can you kindly look into why the agent defaults to port 8100 and APM Server to 8200 please?

**Comment by mikker** [comment]
Hi! I don't understand – the agent defaults to `8200`? https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/config.rb#L20

**Comment by moarpheus** [comment]
Oh my bad! I mean that documentation to use the gem has apm server config pointing to 8100. And you would expect people ( like myself just do a typical copy pasta )

https://www.elastic.co/guide/en/apm/agent/ruby/current/getting-started-rails.html

**Comment by mikker** [comment]
Oh, that's very weird. Must be a typo. Thanks!

**Comment by mikker** [comment]
https://github.com/elastic/apm-agent-ruby/commit/82190d1a9ba22af3b2c2c6fe6d23cc471f2e7ff6
