### ISSUE TITLE
How to initialize APM dynamically in Rails

### ISSUE THREAD

**Issue by slayer** [elastic/apm-agent-ruby#404]
Hi

I want pass parameters dynamically via initializers, so I mark gem as `require: false` in `Gemfile`
and add `config/initializer/elastic_apm.rb` with

```
# ELK stack APM server configuration
if Settings.fetch('elastic_apm.enabled')
  require 'elastic_apm'

  ElasticAPM.start(
    app: MySuperApp,
    service_name: Settings.get('app.host') ,
    server_url: Settings.get('elastic_apm.server') ,
  )
  at_exit { ElasticAPM.stop }
  Rails.application.config.middleware.insert_before 0, ElasticAPM::Middleware
end
```

But there is no deep integration with Rails, such as ActiveRecord tracing and etc

How I can initialize APM with full features support ?

Thanks

**Comment by mikker** [comment]
Hi @slayer! You need two more things that are loaded in the Railtie: The [ActionDispatch](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/railtie.rb#L28) spy and the [ActiveSupport::Notifications subscriber](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/railtie.rb#L64).

**Comment by slayer** [comment]
Thanks @mikker your answer helps.

What do you think about making method `ElasticAPM::Railtie#start` public to be able call it from initializers and hide APM logic inside that class ?

**Comment by mikker** [comment]
Yes, good idea 👍

**Comment by estolfo** [comment]
Closed by https://github.com/elastic/apm-agent-ruby/pull/522
