### ISSUE TITLE
rails console detection 

### ISSUE THREAD

**Issue by gyevgeny** [elastic/apm-agent-ruby#421]
Morning,

In the case, if you have a module with the name Console in the project, you will not be able to start an agent because of 

```
module ElasticAPM
  class Railtie
    def should_skip?(_config)
      if Rails.const_defined? :Console
        return 'Rails console'
      end

      nil
    end
  end
end
```

It will find `::Console` instead of `::Rails::Console`

`Rails.const_defined?('Console', false)` can help here.
 
 Evgeny

**Comment by mikker** [comment]
Nice find! Thank you for reporting and providing a solution 🙏

**Comment by silvermind** [comment]
Does this still work with Rails 6?
In my app using Puma `[ElasticAPM] Skipping because: Rails console. Start manually with `ElasticAPM.start'` is always shown.

**Comment by gyevgeny** [comment]
I'm using following monkey patch right now.

```
application.rb
module ElasticAPM
  class Railtie < Rails::Railtie
    def should_skip?(_config)
      if Rails.const_defined?('Console', false)
        return 'Rails console'
      end
    end
  end
end
```

Working well for me.
