### ISSUE TITLE
Add transaction.type to errors

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-ruby#428]
When an error occurs within a sampled transaction, error.transaction.type should be set.

**Comment by mikker** [comment]
There's https://github.com/elastic/apm-agent-ruby/pull/323 that I have postponed for a while, because it alters the `name` of the errors and as errors are grouped by name in Kibana, I've deemed it a breaking change. _WDYT_?

**Comment by axw** [comment]
Isn't that a different issue? This one is not to do with the _exception_ type, but about adding the _transaction_ type to the error event.

**Comment by mikker** [comment]
Kind of different. Currently `message` holds both `type` and `message` so if I just add `type`, it'll be listed twice per row. Not necessarily a problem.
