### ISSUE TITLE
Filter session id stored in cookies

### ISSUE THREAD

**Issue by timogoebel** [elastic/apm-agent-ruby#447]
The apm agent currently does not filter the session id from the request `Cookie` header or the response `Set-Cookie` header. For security reasons, this information should be filtered by default.

Please find below some sample data:

Request:
```
timezone=Europe%2FBerlin; _session_id=2e50ed79c9edfefddaae4ec28041462c
```

Response:
```
_session_id=2e50ed79c9edfefddaae4ec28041462c; path=/; expires=Tue, 18 Jun 2019 14:28:01 -0000; HttpOnly; secure; SameSite=Lax
```

**Comment by mikker** [comment]
Definitely! Would you suggest stripping the Set-Cookie completely?

**Comment by timogoebel** [comment]
@mikker: As cookies are probably used in a lot of web applications, I think it's reasonable to add a dedicated filter mechanism. I believe you probably want the APM to store cookies in general (as they can be invaluable for debugging), but filter out sensitive data (i can only think of the session id for now, but there may be more).

**Comment by mikker** [comment]
The PR above does two things:

1. Strips `Cookie` and `Set-Cookie` from `headers`.
2. Saves cookies in the appropriate `request.cookies` field and filters sensitive-looking information from them.

Do you think that's a sensible approach?

**Comment by timogoebel** [comment]
Makes sense.

> 2\. filters sensitive-looking information from them.

I don't see a test for this. Does this use the common filter key list?
