### ISSUE TITLE
Problem validating JSON

### ISSUE THREAD

**Issue by lxbrito** [elastic/apm-agent-ruby#45]
I'm getting the following error from the Elastic-Apm-Server, both with the released gem and master:

** [ElasticAPM] Flushing transactions
** [ElasticAPM] POST returned an unsuccessful status code (400)
** [ElasticAPM] {"error":"Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#] S[#/required] missing properties: \"app\""}

My app is a simple Hello World to play around with Elastic-Apm using Rails 5.2 and Ruby 2.5.0. The Elastic stack is at version 6.1.2 on a Ubuntu box.

**Comment by mikker** [comment]
This is a version mismatch. The Ruby agent requires `apm-server` version `6.2` which isn't released yet. That should of course have been noted somewhere in the documentation.

`apm-server 6.2` isn't out yet but you can basically get it by running `master` -- with all the usual caveats of running pre-releases.

**Comment by mikker** [comment]
Thanks for reporting – I'll add a note about versions to the README.
