### ISSUE TITLE
can't modify frozen ElasticAPM::Config

### ISSUE THREAD

**Issue by lxbrito** [elastic/apm-agent-ruby#46]
It seems that commit dfc64b7 (pull request #42 ) introduced a bug that prevents, at least Rails apps, from starting.

	 2: from /lib/ruby/gems/2.5.0/bundler/gems/apm-agent-ruby-38fd266dc376/lib/elastic_apm/railtie.rb:15:in `block in <class:Railtie>'
	 1: from /lib/ruby/gems/2.5.0/bundler/gems/apm-agent-ruby-38fd266dc376/lib/elastic_apm/railtie.rb:15:in `each'
/lib/ruby/gems/2.5.0/bundler/gems/apm-agent-ruby-38fd266dc376/lib/elastic_apm/railtie.rb:16:in `block (2 levels) in <class:Railtie>': can't modify frozen ElasticAPM::Config (FrozenError)

I removed the offending line ( elastic_apm/railtie.rb:16 ) and could start again, only getting the "Problem validating JSON document" error again.

**Comment by mikker** [comment]
Hi @lxbrito! We're looking into this. Thanks for trying out Elastic APM!

**Comment by mikker** [comment]
Can I make you see if running `master` will fix your problem? https://github.com/elastic/apm-agent-ruby/pull/47 should fix this.

**Comment by lxbrito** [comment]
@mikker Sure, as soon as I can.

**Comment by lxbrito** [comment]
@mikker Apparently fixed, I'm still with Apm-server 6.1.2 :(, but the app is booting properly. 

Thanks!
