### ISSUE TITLE
[Automation][Ruby] Release process

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-ruby#461]
add something like we've made on the Python or .NET agents to release the Ruby binaries.

**Comment by mikker** [comment]
Right now the process consists of running `rake release` on a machine with Rubygems authenticated as someone who's an owner of the gem.

**Comment by kuisathaverat** [comment]
it is something similar we have with .NET on Nuget, we have a CI account to make the thing

**Comment by mikker** [comment]
Not familiar with Nuget, but if we can create an account for the CI bot on Rubygems then the rest should be easy. What's the trigger? A commit message matching `vX.Y.Z`?

**Comment by kuisathaverat** [comment]
On Python and .NET, the release stage is run only when you create a tag vX.X.X, when it happens the build is triggered as a usual branch but would execute this new stage, it will wait for an approval for an hour (it is configurable) then if you approve the release is send to the packages repository

**Comment by v1v** [comment]
I've just created an account in Rubygems, login details in the central pass service under the `rubygems.org observability` item
