### ISSUE TITLE
Add log/trace correlation API

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#462]
The agent should provide an easy to use API for putting its Trace/Transaction IDs in the common logs of the application.

My thinking was something like `ElasticAPM.log_ids # => "transaction.id=abc123 span.id=xyx456"`.

That means it can be added to for example Rails with something like ...

```ruby
config.log_tags = [:subdomain, :uuid, lambda { ElasticAPM.log_ids }]
# or if you're into that sort
config.log_tags = [:subdomain, :uuid, ElasticAPM.method(:log_ids)]
```

Maybe support [Lograge](https://github.com/roidrage/lograge)

**Comment by estolfo** [comment]
How likely is it that a user would want only one id?

And how likely is it that a user would want to format the log ids differently? If the answer is "not so likely", I would argue that we should enforce a standard format when the `#log_ids` method is called, especially in light of the fact that the user can construct their own string using `ElasticAPM.current_transaction&.id` and friends. We can always add support for custom formats later.

**Comment by estolfo** [comment]
todo: 
1) end-to-end testing
2) documentation review/updates.
