### ISSUE TITLE
NoMethodError: undefined method `function' for nil:NilClass

### ISSUE THREAD

**Issue by julsemaan** [elastic/apm-agent-ruby#476]
I've recently stumbled on an issue with the latest version of the agent (2.9.1) where there seems to be an error in the agent itself when reporting an error to the APM server.

The error seems to be in add_stacktrace in lib/elastic_apm/error_builder.rb where the stacktrace object doesn't have a first frame.

It doesn't seem to be causing issues to the application itself and the agent does report the metrics and other errors (app related) to the APM server

The stacktrace of this error is available here:
https://pastebin.com/rWwCxhE7

Let me know if I should provide additional information/data

Thanks!

**Comment by julsemaan** [comment]
I was able to pinpoint this to the fact that the error the agent is catching doesn't have a backtrace.

More precisely, its this error: https://www.rubydoc.info/gems/unicorn/2.0.0/Unicorn/ClientShutdown

Using the following commit will omit setting the culprit if there is no backtrace that is set:
https://github.com/julsemaan/apm-agent-ruby/commit/3de79da48a517d3f018d4bc468f9e2d1001f8275

I tested and the error still appears in APM with the other information properly from what I can tell

**Comment by mikker** [comment]
Hi @julsemaan! Thanks for reporting this and doing some great debugging. I'll take a look 👍
