### ISSUE TITLE
Closing request with reason timeout

### ISSUE THREAD

**Issue by SemionPar** [elastic/apm-agent-ruby#506]
*Versions*
```
elastic-apm (2.9.1)
rails (5.0.0.1)
ruby (2.3.4)
cloud es stack v6.7.1
```

*Problem*
ES index is created, but metrics don't come through.
Boot logs are ok:
```
[ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::CpuMem'
[ElasticAPM] [2.9.1] Starting agent, reporting to https://xxx.apm.us-east-1.aws.cloud.es.io:443
[ElasticAPM] [PID:13506]: Starting Transport
[ElasticAPM] [PID:13506]: Booting worker...
[ElasticAPM] Starting instrumenter
[ElasticAPM] Starting metrics
[ElasticAPM] Requiring spy: delayed_job
[ElasticAPM] Requiring spy: elasticsearch
[ElasticAPM] Collecting metrics
[ElasticAPM] Requiring spy: faraday
[ElasticAPM] Requiring spy: http
[ElasticAPM] Requiring spy: mongo
[ElasticAPM] Requiring spy: net_http
[ElasticAPM] Requiring spy: redis
[ElasticAPM] Requiring spy: sequel
[ElasticAPM] Requiring spy: sidekiq
[ElasticAPM] Requiring spy: sinatra
[ElasticAPM] Requiring spy: tilt
[ElasticAPM] Requiring spy: rake
[ElasticAPM] Registering subscriber
```
But then I start getting:
```
[ElasticAPM] Collecting metrics
[ElasticAPM] [THREAD:43251960]: Opening new request
[ElasticAPM] [THREAD:49882160]: Closing request with reason timeout
[ElasticAPM] Closing writer with reason timeout
[ElasticAPM] APM Server responded with status 202
```

Any idea what might be an issue here?

**Comment by danielschlegel** [comment]
I have the same issue and don't find any hints. I already got through all documentation about configuring apm server and elastic.

**Comment by mikker** [comment]
Hi there! The _timeout_ is actually a good thing here, as it is a planned flush on the long-running request to APM Server. I can see how the choice of word can be confusing as timeouts are usually a bad thing. I'll consider whether we ought to call it something else.

What platform are you running your Ruby app on?

**Comment by SemionPar** [comment]
Hey @mikker!

> The timeout is actually a good thing here, as it is a planned flush on the long-running request to APM Server. I can see how the choice of word can be confusing as timeouts are usually a bad thing.

Good to know. Something along the lines of what you said about flushing would be less confusing, +1 to that!

Problem occurs on amazon linux 1 box running on ec2.
```
$ uname -a
Linux amzn1.x86_64 #1 SMP Wed May 10 01:58:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Let me know if you need more information.

**Comment by SemionPar** [comment]
Updated `elastic-apm` to `3.1.0` and everything works as expected now. Have you been able to  solve your problem, @danielschlegel?

**Comment by danielschlegel** [comment]
@SemionPar no and i did not have time to upgrade. Will try.

**Comment by mikker** [comment]
Closing this. Feel free to reopen if the issue wasn't resolved.

**Comment by mpokale** [comment]
I have installed `elastic-apm` version 3.5 but see the same logs`Collecting metrics
09 Mar 2020 15:04:53.241[IQ62EA][ElasticAPM] [THREAD:40011920]: Opening new request
09 Mar 2020 15:04:54.840[GEMH70][ElasticAPM] [THREAD:57403320]: Closing request with reason timeout
09 Mar 2020 15:04:54.963[08R9ZY][ElasticAPM] Closing writer with reason timeout
09 Mar 2020 15:04:54.963[Z7V1TH][ElasticAPM] APM Server responded with status 202`

**Comment by mikker** [comment]
@mpokale As mentioned above, that message is actually a good thing:

> The timeout is actually a good thing here, as it is a planned flush on the long-running request to APM Server. I can see how the choice of word can be confusing as timeouts are usually a bad thing. I'll consider whether we ought to call it something else.

Are you experiencing any problems otherwise with Elastic APM?

**Comment by balusarakesh** [comment]
@mikker  We are also seeing the same errorv and the graphs for `Time spent by span type` are empty
```
[ElasticAPM] Closing writer with reason timeout
[ElasticAPM] APM Server responded with status 202
[ElasticAPM] [THREAD:47339104767800]: Opening new request
[ElasticAPM] [THREAD:47339104771180]: Closing request with reason timeout
```

**Comment by balusarakesh** [comment]
<img width="1626" alt="Screen Shot 2020-03-13 at 1 42 13 PM" src="https://user-images.githubusercontent.com/17168699/76658086-8c9a9d00-6530-11ea-94c7-cdaceaf8a3f8.png">

**Comment by balusarakesh** [comment]
CPU metrics are also not consistent
<img width="1753" alt="Screen Shot 2020-03-13 at 1 43 37 PM" src="https://user-images.githubusercontent.com/17168699/76658149-af2cb600-6530-11ea-8aac-e6cd3d297479.png">

**Comment by mikker** [comment]
Hi @balusarakesh! If only the metrics are missing/inconsistent, it's likely due to using a forking server? What's your server setup?

This can be solved by calling [`ElasticAPM.restart`](https://www.elastic.co/guide/en/apm/agent/ruby/current/api.html#api-agent-restart) after the process forks. There are usually APIs to do something like that.
