### ISSUE TITLE
Error [400] /properties/process/properties/pid/type expected number, but got null

### ISSUE THREAD

**Issue by CypressXt** [elastic/apm-agent-ruby#51]
Hi, 
I'm having some trouble using Elastic APM ruby agent on a Rails app hosted using puma (`3.11.2 (ruby 2.4.1-p111)`) in production environment (not really a production app, but hosted like so ;) ).
I get errors like (agent side):
```
[ElasticAPM] {"error":"Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/process/pid] S[#/properties/process/properties/pid/type] expected number, but got null"}
```

Occuring only in production mode, when using the `rails s` in DEV env mode it works like a charm (also using puma as dev server when running `rails s` also`). 

Here is the full apm rails agent output:
```
D, [2018-02-07T01:11:58.377672 #7856] DEBUG -- : ** [ElasticAPM] Flushing transactions
E, [2018-02-07T01:11:59.144111 #7856] ERROR -- : ** [ElasticAPM] POST returned an unsuccessful status code (400)
D, [2018-02-07T01:11:59.144372 #7856] DEBUG -- : ** [ElasticAPM] {"error":"Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/process/pid] S[#/properties/process/properties/pid/type] expected number, but got null"}
```

And here are the apm-server logs:
```
2018-02-07T01:11:15.732+0100    INFO    [request]       beater/handlers.go:150  handled request {"request_id": "c426b616-b81c-404e-8431-2e0ee8768008", "response_code": 400, "method": "POST", "URL": "http://livia.cypressxt.net:8200/v1/trans
actions", "content_length": 94047, "remote_address": "192.168.1.106", "user_agent": "elastic-apm/ruby 0.3.0"}
2018-02-07T01:11:44.152+0100    INFO    [monitoring]    log/log.go:124  Non-zero metrics in the last 30s        {"monitoring": {"metrics": {"apm-server":{"processor":{"transaction":{"validation":{"count":1,"errors":1}}},"server":{"requests
":{"counter":1},"response":{"errors":1}}},"beat":{"cpu":{"system":{"ticks":210,"time":216},"total":{"ticks":1250,"time":1260,"value":1250},"user":{"ticks":1040,"time":1044}},"info":{"ephemeral_id":"feabd8ce-1786-47a7-b306-1d430a4c8dcb","up
time":{"ms":3240010}},"memstats":{"gc_next":4194304,"memory_alloc":2640816,"memory_total":146758632}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"load":{"1":0.03,"15":0.09,"5":0.0
8,"norm":{"1":0.015,"15":0.045,"5":0.04}}}}}}
2018-02-07T01:11:59.113+0100    ERROR   [request]       beater/handlers.go:384  error handling request  {"request_id": "2bec79d8-1bc8-4aa8-8fc8-a5ac2430059f", "error": "Problem validating JSON document against schema: I[#] S[#] doesn't val
idate with \"transaction#\"\n  I[#/process/pid] S[#/properties/process/properties/pid/type] expected number, but got null"}
```
And last, here is my puma configuration file used:
```
#!/usr/bin/env puma

directory '/var/www/myapp/current'
rackup "/var/www/myapp/current/config.ru"
environment 'preproduction'
daemonize true
pidfile "/var/www/myapp/shared/tmp/pids/puma.pid"
state_path "/var/www/myapp/shared/tmp/pids/puma.state"
stdout_redirect '/var/www/myapp/shared/log/puma_access.log', '/var/www/myapp/shared/log/puma_error.log'
threads 5,5
bind 'unix:///var/www/myapp/shared/tmp/sockets/puma.sock'
workers 0
prune_bundler
```

Don't know exactly why but the agent seems to parse the pid type as null in this configuration.

**Comment by mikker** [comment]
Hi! I'm not sure why there sometimes aren't a pid but my colleague's seen this before and already fixed it in #48 . Can I make you try `master`? That'll give you an empty pid value but at least, hopefully, no errors.

**Comment by CypressXt** [comment]
Hi @mikker, ok I'm checking this tonight, will keep you informed. Thx !

**Comment by CypressXt** [comment]
Working fine using the `master` release, Thanks 👍 !

Here is my Gemfile
```
gem 'elastic-apm', :git => 'https://github.com/elastic/apm-agent-ruby.git', :branch => 'master'
```

**Comment by mikker** [comment]
Very good! Thanks for letting me know. (FYI as long as the branch you want is master, you can omit it in the Gemfile 😉 )

**Comment by CypressXt** [comment]
noticed thx ☺️!

**Comment by larseen** [comment]
@CypressXt I had the exact same issue as you, instead I was running `rails server` instead. The error went away when I pulled from the new gem from master, however now it doesnt send any data to the APM server at all. 
Do you get any data when running `rails-server` ?

**Comment by mikker** [comment]
@larseen You should see errors in your logs right after `Flushing transactions` if there's an error in sending to APM Server.

If not that then there's also a short period between APM server receiving the data and it showing up in ES/Kibana. And lastly; have you remembered to create an `apm-` index pattern?

**Comment by CypressXt** [comment]
Hi @larseen, same here. I'll investigate tomorrow and keep you guys informed.

**Comment by mikker** [comment]
Can you please write your app's and APM server specs? Are you both using Rails? And APM Server 6.2?

**Comment by CypressXt** [comment]
Sure, here are my app's specs:
Rails `5.1.4`
Puma `3.11.2`
apm-server `6.2.0 (amd64), libbeat 6.2.0`

The last APM entry is dated from yesterday @ ~11h30. Just before a `bundle install` made during the last app deployement process.

**Comment by mikker** [comment]
I found a few bugs and fixed them – can you try either `master` or `0.4.0` from Rubygems?

**Comment by larseen** [comment]
Pulled latest and now the agent is flushing and the APM server it receiving the spans/transactions!
I can see the result in the visualizer tab, and Kibana detects both the APM server and Agent. However there is no data in the APM tab just a blank screen and the text `No apps with data in the selected time range.`

**Comment by larseen** [comment]
Seems to work fine now!

**Comment by CypressXt** [comment]
Yep, fixed for me too !

**Comment by mikker** [comment]
Great! Thanks for reporting. I'd love to get any and all feedback that you might have 😃
