### ISSUE TITLE
Cannot change config path via ELASTIC_APM_CONFIG_FILE environment variable

### ISSUE THREAD

**Issue by kowalskey** [elastic/apm-agent-ruby#517]
Hello,
Looks like it is impossible to change default config file path via `ELASTIC_APM_CONFIG_FILE` environment variable. 
I confirmed that environment variable is correctly passed to process via inspecting it  via `/proc/<PID>/environment`.

Instrumented application is more or less standard rails 5.2 app.

**Comment by kowalskey** [comment]
Expected behavior is:
Setting ELASTIC_APM_CONFIG_FILE=/some/path/to/config.yml  makes `elastic-apm` load settings from that config file.

Observed behavior is:
Setting  ELASTIC_APM_CONFIG_FILE=/some/path/to/config.yml to existing, valid YAML file does not change `elastic-apm` settings. They are set to their defaults.

**Comment by mikker** [comment]
Hi @kowalskey. I was able to reproduce this. Taking a look what might go wrong. Thanks for reporting it 👍
