### ISSUE TITLE
Increase JRuby spec reliability

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#523]
The JRuby branches of the CI test runs fail too often.

My current best theory is that the specs start throwing requests at the test apps before the testapp's agent has fully booted, thereby, sometimes, missing the first request.

But we should investigate more.

**Comment by estolfo** [comment]
`NotMethodError` on `enqueue` called from block created in `initialize`: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-downstream/detail/PR-525/39/pipeline/
  - Issue opened with JRuby: https://github.com/jruby/jruby/issues/5881

**Comment by estolfo** [comment]
Update on JSON schema error after investigating: It seems unlikely it would be a network failure when fetching the schema from github, as you would see a `JSON::Schema::ReadFailed` error.
