### ISSUE TITLE
Include number of `rows_affected` if available

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#574]
https://github.com/elastic/apm/issues/112
APM Server issue: https://github.com/elastic/apm-server/pull/3095 (✅ merged!)

Have not investigated whether this is something we can get easily or at all, so I suppose that will be the first step.

**Comment by estolfo** [comment]
The `sequel` gem returns the number of rows affected from `delete` and `update` operations: https://github.com/jeremyevans/sequel/blob/master/doc/sql.rdoc#insert-update-delete

**Comment by estolfo** [comment]
The MongoDB driver reports the `modified_count`/`deleted_count` from [update](https://docs.mongodb.com/ruby-driver/master/tutorials/ruby-driver-crud-operations/index.html#updating) and [delete](https://docs.mongodb.com/ruby-driver/master/tutorials/ruby-driver-crud-operations/index.html#deleting) operations.

**Comment by estolfo** [comment]
Waiting for server to release https://github.com/elastic/apm-server/pull/3095
