### ISSUE TITLE
Path for agent configuration api is incorrect

### ISSUE THREAD

**Issue by mchakradeo** [elastic/apm-agent-ruby#577]
According to these docs: https://www.elastic.co/guide/en/apm/server/current/agent-configuration-api.html, the endpoint to change the agent configuration is `/config/v1/agents`.

In `perform_request` method https://github.com/elastic/apm-agent-ruby/blob/3803a9a159a9bab032368cf0a4626c1aa1bf8fc1/lib/elastic_apm/central_config.rb#L126, the path is set to `'/agent/v1/config/'`. This should be `'/config/v1/agent/'`.

For reference, the `apm-agent-python` agent has the right path set: https://github.com/elastic/apm-agent-python/blob/e15bc80a9a475869fca311f17688cec4ff8d5359/elasticapm/conf/constants.py#L35

**Comment by mikker** [comment]
Well that's just terribly embarrassing. Thank you for reporting – I'll get a release out as soon as possible.
