### ISSUE TITLE
Ruby Sintra error is not captured in elastic ruby agent?

### ISSUE THREAD

**Issue by sharanraj124** [elastic/apm-agent-ruby#591]
Hi I working in `Sinatra` application in development. we could try elastic ruby apm agent. Transactions and spans captured correctly but error is not captured. pls help for us.

```
D, [2019-10-11T15:10:12.356198 #21976] DEBUG -- :    (6.3ms)  COMMIT
0.5
ArgumentError - Argument is not numeric:
	/apple/development/git/ruby-testing/dbc-sinatra-crud-example/app/controllers/index.rb:16:in `inverse'
	/apple/development/git/ruby-testing/dbc-sinatra-crud-example/app/controllers/index.rb:20:in `block in <top (required)>'
```

**Comment by mikker** [comment]
Hi! I'll look into this – are you catching errors in your app with something like
```ruby
error do
  # ...
end
```

**Comment by estolfo** [comment]
Hi @sharanraj124 has this issue been resolved? If not, can you tell us if you're catching the error like in the example above? Thanks!

**Comment by estolfo** [comment]
I'm going to close this issue. Please reopen it if you're able to provide more information. Thanks!
