### ISSUE TITLE
Rails' template view paths are broken in master

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#598]
Just noticed this is one of my apps; Somehow we've broken view paths since the last version (3.1.0). They are all just called `Absolute path` currently. My guess, without investigating, is that it's related to the changes to the Railtie.

**Comment by estolfo** [comment]
Can you indicate how the error manifests? I tried starting the app via apm-integration-testing with the agent as master and saw this:
```

**Comment by mikker** [comment]
Yes, here's how views look in an app on master:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/2819/68334008-b5ed7d00-00a7-11ea-9860-8e00864785dd.png">

And here's one for 3.1.0:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/2819/68334217-2a282080-00a8-11ea-9cad-a78ff5eb6251.png">

It might be the `set_rails` part not setting `__view_paths` correctly?

**Comment by estolfo** [comment]
Thanks for the extra info, I'll look into it.
