### ISSUE TITLE
SecretsFilter replacing values (ActionCable)

### ISSUE THREAD

**Issue by Cervenka** [elastic/apm-agent-ruby#614]
Hello

We need access to our session data in ActionCable, so we do this in ApplicationCable::Connection#connect:
`session = cookies.encrypted[SESSION_STORE_KEY] || {}`

The value is intermittently being returned as null, so we decided to try this:
`session = cookies[SESSION_STORE_KEY]`

The result is that we sometimes get the actual encrypted string, but other times we receive the string “[FILTERED]”
We need access to this data, so this is a problem for us. On the other hand we want the value to be filtered.

It seems as if SecretsFilter is replacing the actual values. I think the a deep copy should be filtered instead.

**Comment by mikker** [comment]
This sounds like a bug. What version of the Agent are you using? I seem to recall fixing something like this at one point.

**Comment by mikker** [comment]
Indeed this looks like a bug. It should be fixed in the referenced PR. Can you test if it fixes your issue @Cervenka?
