### ISSUE TITLE
Add gRPC support

### ISSUE THREAD

**Issue by lreuven** [elastic/apm-agent-ruby#628]
placeholder,TBD

**Comment by mikker** [comment]
https://github.com/grpc/grpc/tree/master/src/ruby is the canonical implementation, it seems.

**Comment by axw** [comment]
https://www.rubydoc.info/gems/grpc/GRPC/Interceptor should be used for injecting/extracting trace-context metadata (headers). If it's helpful, the Go agent's implementation is here: https://github.com/elastic/apm-agent-go/tree/master/module/apmgrpc - there are separate interceptors for client and server.
