### ISSUE TITLE
Documentation on set_tag is outdated

### ISSUE THREAD

**Issue by slhck** [elastic/apm-agent-ruby#644]
The use of `set_tag` is still widely documented, and according to what was mentioned in #543, shouldn't this method have been deprecated instead of removed completely?

I'm getting:

```
*** NoMethodError Exception: undefined method `set_tag' for ElasticAPM:Module
Did you mean?  set_label
```

with version 3.2.0 of this Gem.

The [documentation](https://www.elastic.co/guide/en/apm/agent/ruby/current/context.html#_adding_tags) is outdated and still lists this method:

> ### Adding tags
> 
> Tags are special in that they are indexed in your Elasticsearch database and therefore searchable.
> 
>     ElasticAPM.set_tag(:company_name, 'Acme, Inc.')

Also, there is a [blog entry](https://www.elastic.co/blog/how-to-instrument-your-ruby-app-with-the-elastic-apm-ruby-agent) that needs to be updated.

**Comment by mikker** [comment]
Sorry about this – I'll update it right away 👍

**Comment by mikker** [comment]
Thanks @slhck for reporting this and sorry for the confusion 🙏

**Comment by slhck** [comment]
Awesome, thanks for the quick response!
