### ISSUE TITLE
Rename server_ca_cert config to server_ca_cert_file

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-ruby#650]
The Ruby agent is currently the only one defining this config attribute, [server_ca_cert](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-ssl-ca-cert):

> The path to a custom CA certificate for connecting to APM Server.

The agents have some other config which accept file paths, such as `log_file` and `config_file`. We should be consistent to avoid confusion, so I suggest we rename this one to `server_ca_cert_file`.

We could either deprecate the existing config name, and or keep it but repurpose it to accept the CA cert contents _contents_. For backwards compatibility we would do this if we detect the cert PEM header (`-----BEGIN`), and otherwise treat it as a file path.

**Comment by mikker** [comment]
I think we should deprecated in a similar fashion to how we've done it with config options before; Redirect the old option to the new one and log a deprecation notice.

As it's always been meant to be used with file paths I don't think there's any need to add new functionality to parse inline certs.
