### ISSUE TITLE
Ruby 2.7.0: LoadError: cannot load such file -- thwait

### ISSUE THREAD

**Issue by olegantonyan** [elastic/apm-agent-ruby#662]
In Ruby 2.7.0 `thwait` is no longer bundled https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
```
The following libraries are no longer bundled gems. Install corresponding gems to use these features.

    CMath (cmath gem)
    Scanf (scanf gem)
    Shell (shell gem)
    Synchronizer (sync gem)
    ThreadsWait (thwait gem)
    E2MM (e2mmap gem)
```

**Comment by mikker** [comment]
I didn't find the agent needing this gem with 2.7. Are you sure it's not another dependency that's depending on it?

**Comment by olegantonyan** [comment]
Here's stack trace:
```        13: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler.rb:4:in `<top (required)>'
        12: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler.rb:4:in `require_relative'
        11: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq/scheduler.rb:1:in `<top (required)>'
        10: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
         9: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
         8: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
         7: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/elastic-apm-3.3.0/lib/elastic_apm/spies.rb:73:in `require'
         6: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/elastic-apm-3.3.0/lib/elastic_apm/spies.rb:73:in `require'
         5: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/scheduler.rb:2:in `<top (required)>'
         4: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
         3: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
         2: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
         1: from /home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/elastic-apm-3.3.0/lib/elastic_apm/spies.rb:73:in `require'
/home/oleg/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/elastic-apm-3.3.0/lib/elastic_apm/spies.rb:73:in `require': cannot load such file -- thwait (LoadError)
```

**Comment by mikker** [comment]
Due to the nature of how the agent inserts itself into other libraries and wraps many things with itself, it shows up in (unrelated) stacktraces a lot. Thanks for reporting anyway!
