### ISSUE TITLE
Coerce HTTP headers to string before reporting HTTP requests to APM Server

### ISSUE THREAD

**Issue by greyblake** [elastic/apm-agent-ruby#672]
Hi. Thanks for the nice product.
I'd like to report an error that we just experienced, and IMHO could be easily fixed.

### Environment
Ruby apm-agent: `3.2.0`
Ruby version: `2.5.7`
APM Server:  7.3.2
Rails: 5.2.4

### How to reproduce

In rails controller set a header that is an integer. E.g.

```ruby
response.set_header('foobar', 123)
```

Rails app & Rack work as expected.

However ElasticAPM client writes an error. 
I am not able to share the original error for security issues, but it looks similar to this one:

```
"{"accepted":51,"errors":[{"message":"error validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"\\n I[#] S[#/allOf/3] allOf failed
  I[#/context/response/headers/expiry] S[#/allOf/3/properties/context/properties/response/properties/headers/patternProperties/%5B.%2A%5D%2A$/type] expected string or array or null, but got number","document":
```

### How it should be fixed (proposal)

So it looks like the request that APM client sends to the APM server does not pass JSON schema validation and gets rejected. The schema does not allow schema property to be a number (what seems to be reasonable).

I would propose to insure that in this case values (unless they're array or null) get explicitly coerced into string.

Thanks in advance.

**Comment by mikker** [comment]
This does sound like a bug, I agree. Thanks for the thorough report. I'll take a look 👍

**Comment by greyblake** [comment]
Thanks!
