### ISSUE TITLE
Discussion for enriching the Github templates

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-agent-ruby#689]
We'd like to enrich the existing PR template adding a few sections that we consider helpful during the review process for a PR, making it even better.

>One **important** thing for us is not to overwhelm whoever is filling out this template, so please feel free to discuss about removing parts of it if that's the case. In fact we received very positive feedback from the Java team to adapt to their needs. The same applies here 😄 

In this template, besides the checklist that we already have, we'd like to define the following structure, where:
- each section is a H2 element
- the mandatory/recommended/optional keyword goes in an HTML comment (so won't appear in the end description)
- **the description texts go in an HTML comment** (so won't appear in the end description)

You could see examples for [Beats](https://github.com/elastic/beats/pull/15388), and [APM Agent Java](https://github.com/elastic/apm-agent-java/pull/994)

We will also use this markdown format (H2 and HTML comments) for the other templates you already have.

The initial template: ⬇️⬇️⬇️⬇️ 

A few suggestions about filling out this PR

1. Use a descriptive title for the PR.
2. If this pull request is work in progress, create a draft PR instead of prefixing the title with WIP.
3. Please label this PR at least one of the following labels, depending on the scope of your change:
- feature request, which adds new behavior
- bug fix
- enhancement, which modifies existing behavior
- breaking change
4. Remove those recommended/optional sections if you don't need them. Only "What does this PR do" and "Checklist" are mandatory.
5. Submit the pull request: Push your local changes to your forked copy of the repository and submit a pull request (https://help.github.com/articles/using-pull-requests).
6. Please be patient. We might not be able to review your code as fast as we would like to, but we'll do our best to dedicate to it the attention it deserves. Your effort is much appreciated!

>Do you see any other type?

## What does this PR do? _(Mandatory)_
Explain here the changes you made on the PR. Please explain the WHAT: patterns used, algorithms implemented, design architecture, message processing, etc.

## Why is it important? _(Mandatory)_
Explain here the WHY, or the rationale/motivation for the changes.

## Checklist _(Mandatory)_
Add a checklist of things that are required to be reviewed in order to have the PR approved
List here all the items you have verified BEFORE sending this PR. Please DO NOT remove any item, striking through those that do not apply.

>Here we have a default list, based on Java agent:

List here all the items you have verified BEFORE sending this PR. Please DO NOT remove any item, striking through those that do not apply. (Just in case, strikethrough uses two tildes. ~~Scratch this.~~)
- [ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/). 
- [ ] My code follows the style guidelines of this project
- [ ] I have rebased my changes on top of the latest master branch
Update your local repository with the most recent code from the main repo, and rebase your branch on top of the latest master branch. We prefer your initial changes to be squashed into a single commit. Later, if we ask you to make changes, add them as separate commits. This makes them easier to review.
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-ruby/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
Run the test suite to make sure that nothing is broken. See https://github.com/elastic/apm-agent-ruby/blob/master/CONTRIBUTING.md#testing for details.
- [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- [ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced
- [ ] Added an instrumentation plugin? How did you make sure that old, non-supported versions are not instrumented by accident?

## Author's Checklist _(Recommended)_
Add a checklist of things that are required to be reviewed in order to have the PR approved

## How to test this PR locally _(Recommended)_
Explain here how this PR will be tested by the reviewer: commands, dependencies, steps, etc.

## Related issues _(Recommended)_
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.
- Closes #ISSUE_ID
- Relates #ISSUE_ID
- Requires #ISSUE_ID
- Superseds #ISSUE_ID

## Use cases _(Recommended)_
Explain here the different behaviors that this PR introduces or modifies in this project, user roles, environment configuration, etc.
If you are familiar with Gherkin test scenarios, we recommend its usage: https://cucumber.io/docs/gherkin/reference/

## Logs _(Recommended)_
Paste here output logs discovered while creating this PR, or any other output you consider important to be shared with the team. It could be a stacktrace coming from an application server, or a Ruby framework/library, database logs...

## Screenshots _(Optional)_
Add here screenshots about how the project will be changed after the PR is applied. They could be related to web pages, terminal, etc, or any other image you consider important to be shared with the team.

**Comment by mdelapenya** [comment]
@estolfo @mikker Could you take a look to this? We'd like to see progress here 🙏

**Comment by estolfo** [comment]
Thanks for this, @mdelapenya 
It's definitely quite thorough. My only fear is that it's so thorough that people aren't likely to actually read more than a small portion of it. Have people filled out the entire template for beats and the java agent?

**Comment by mdelapenya** [comment]
The idea is to start from this template in this discussion and adapt to your team's needs. Java & Beats reduced a few of them. On the same topic, most of the sections are optional, so they can be removed by senders.

**Comment by mikker** [comment]
I share Emily’s concern. We are so lucky that we already get pretty high quality issues and PRs, so I also worry we could turn users away with a huge up-front extra burden.

_Just enough_ process is the right amount of process 😊

In that spirit I think we should only add things that have been problems before and, as far as I remember, we haven’t had any problems like the ones your proposal tries to preempt.

**Comment by mdelapenya** [comment]
I really loved your input:
>We are so lucky that we already get pretty high quality issues and PRs

Is there anything in the structured sections and the checklist you would like to give it a try?

**Comment by estolfo** [comment]
I think having a short checklist is useful. From my experience, users don't always add tests and/or run the tests when they make a change. I think it would be worthwhile to have a short checkilst of the basic requirements for a PR so as to minimize the back-and-forth with users about non-code related points.

A small note about signing the CLA might be useful. See this back-and-forth about the CLA: https://github.com/elastic/apm-agent-ruby/pull/653

**Comment by mdelapenya** [comment]
Do you mind if I send a PR and we adapt the template to your needs? I'll take this feedback as input for it.

**Comment by estolfo** [comment]
Sure!
