### ISSUE TITLE
I don’t understand why there is no data - Time spent by span type

### ISSUE THREAD

**Issue by danilvoe** [elastic/apm-agent-ruby#696]
In the development environment, data is displayed, but in the staging environment there is no data. Settings are confined only to the name of the service.

I can’t repeat the problem in the development environment.

- OS: Debian 8.3
- Ruby version: 2.6.5
- Framework and version : Rails 5.1 
- APM Server version: 7.5.0
- Agent version: 3.4.0

![Выделение_770](https://user-images.githubusercontent.com/15100792/73053049-cab40280-3e97-11ea-8e1a-94f595179bf9.png)
![Выделение_769](https://user-images.githubusercontent.com/15100792/73053050-cab40280-3e97-11ea-87c4-6f0fd0fff9be.png)

**Comment by mikker** [comment]
Hi! Nothing comes to mind. Perhaps try setting the agent log level to _debug_ (`0`) and see if that gives us any clues.

```yaml
log_level: 0
```

**Comment by danilvoe** [comment]
According to the logs, it’s not clear what the problem is. But another oddity was revealed. For sidekiq there is data, not only for requests

Maybe something from the index template or something similar?

**Comment by estolfo** [comment]
Hi @danilvoe 
Are there any messages in the logs that might indicate something is not right? Even just a few warning messages might help.
Sorry, I'm not understanding what you mean about sidekiq. Is there data showing up for sidekiq in the staging environment?

**Comment by danilvoe** [comment]
> Sorry, I'm not understanding what you mean about sidekiq. Is there data showing up for sidekiq in the staging environment?

meaning - Transaction type

at request type:

![Выделение_783](https://user-images.githubusercontent.com/15100792/73243877-b0409880-41b9-11ea-98a1-4759fd3d0329.png)

with sidekiq type

![Выделение_784](https://user-images.githubusercontent.com/15100792/73243923-ca7a7680-41b9-11ea-8fa0-8848155da855.png)

> Are there any messages in the logs that might indicate something is not right?

there are no errors related to data loading. There is an error about accessing /agent/v1/config/, but this problem is not related to sending data.

**Comment by danilvoe** [comment]
@estolfo sorry, I did not immediately realize to see the logs on the side of the agent. There is such an error:

`
E, [2020-01-28T10:29:12.525976 #50346] ERROR -- : [ElasticAPM] [THREAD:17981460]: APM Server not responding in time, terminating request`

**Comment by estolfo** [comment]
Hi @danilvoe thanks for sending that error! As the message suggests, it indicates your app can't connect to the APM server. Is there a difference between how your development and staging environments connect to the APM server that might explain this?

**Comment by vidok** [comment]
Hello, 

I have a similar issue. No data for `Time spent by span type` in my staging environment which is running on a Kubernetes cluster. Everything looks fine in development environment on my local machine. 

![image](https://user-images.githubusercontent.com/314956/73531397-a9649080-441a-11ea-87a4-29c4ef102a18.png)

At the same time I see a transaction list, distributed tracing, transaction duration. Only `Time spent by span type` is missing. 

The app sends events to the same ElasticAPM server. I think I checked everything for both envs: 
1. Agents connections - OK (no errors)
2. Events payloads - OK (contain span types and durations)
3. Elastic indexes - OK (everything looks good from Kibana Discover perspective) 

Ruby version: 2.6.5
Framework and version : Rails 5.1/Grape 
APM Server version: 7.5.2
Agent version: 3.4.0

but http://myhost/api/apm/services/Buyer/transaction_groups/breakdown?start=2020-01-31T10%3A05%3A09.815Z&end=2020-01-31T10%3A20%3A09.815Z&transactionName=GET%20%2F%3Aversion%2Flots%2F%3Alot_id%2Fdetail&transactionType=request&uiFilters=%7B%22environment%22%3A%22staging%22%7D always returns 
```
{"kpis":[],"timeseries":[]}
```

is there anything else I can check? 

Thanks in advance

**Comment by vidok** [comment]
Okay, I found the issue. 

I'm running my app using `unicorn`, so the apm agents run only in master process and that why it doesn't collect breakdown metrics. 

I added a hook into `after_fork` block and it started working. 

I think the current issue can be closed, I will open a PR with fix.

**Comment by mikker** [comment]
Good news! A PR is very appreciated. Yes, there seem to be some complications when pre-loading the app and then forking (like I assume you Unicorn is set up?)

**Comment by danilvoe** [comment]
I am using a Passenger

**Comment by estolfo** [comment]
@vidok Out of curiosity, what did you add into the `after_fork` hook?

**Comment by vidok** [comment]
@estolfo 
```Ruby
after_fork do |server, worker|
  ##
  # Unicorn master loads the app then forks off workers - because of the way
  # Unix forking works, we need to make sure we aren't using any of the parent's
  # sockets, e.g. db connection
  ElasticAPM.stop

  sleep(2)

  ElasticAPM::Rails.start(server_url:'localhost', service_name:'Service'...)
  ActiveRecord::Base.establish_connection
end
```
Technically, I restart the agent's workers. I know it looks silly, but there is no other way to solve it. The current design doesn't allow to start workers in child processes.

**Comment by estolfo** [comment]
@vidok thanks! I've opened an issue for this, by the way: https://github.com/elastic/apm-agent-ruby/issues/724

**Comment by vidok** [comment]
@estolfo Cool! Let's close this issue and jump into a new one.
