### ISSUE TITLE
Error accessing /agent/v1/config/

### ISSUE THREAD

**Issue by danilvoe** [elastic/apm-agent-ruby#701]
An error appears in the logs of the APM server

`2020-01-28T09:04:05.199+0300	ERROR	[request]	middleware/log_middleware.go:74	404 page not found	{"request_id": "b64c9aab-d750-42a4-84a2-b817728a2fa4", "method": "POST", "URL": "/agent/v1/config/", "content_length": 68, "remote_address": "10.132.21.11", "user-agent": "http.rb/4.1.1", "response_code": 404, "error": "404 page not found"}`

According to the documentation get request should come.

https://www.elastic.co/guide/en/apm/server/7.5/agent-configuration-api.html#agent-config-endpoint

 -   OS: Debian 8.3
 -   Ruby version: 2.6.5
 -   Framework and version : Rails 5.1
 -   APM Server version: 7.5.0
 -   Agent version: 3.4.0

**Comment by lewiseason** [comment]
This is happening for me also:

```Jul 22 15:43:14 redacted apm-server[2235]: 2020-07-22T15:43:14.385+0100        ERROR        [request]        middleware/log_middleware.go:74        404 page not found        {"request_id": "88e9ac18-a217-4f8a-99ca-aab75dff4583", "method": "POST", "URL": "/agent/v1/config/", "content_length": 57, "remote_address": "redacted", "user-agent": "http.rb/4.1.1", "response_code": 404, "error": "404 page not found"}```

* OS: RHEL7
* Ruby: 2.6.3
* Framework and version: Rails 6.0.3.2
* APM Server version: 7.4.0
* Agent version: 3.7.0

I see my apm-server is older, but my agent is newer than danilvoe's.

This isn't an issue for me since we don't use agent configurations, but hopefully another data point is helpful to you.

**Comment by danilvoe** [comment]
> Hi @danilvoe, is this still an issue?

After switching to one of the APM server versions, the error disappeared. Version 7.8 is currently in use.

**Comment by mikker** [comment]
This comes from the Central Config feature. See the option `central_config` for an explanation and way to turn it off in your app if you want to: https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-central-config
