### ISSUE TITLE
How to disable in a single controller?

### ISSUE THREAD

**Issue by rtymchyk** [elastic/apm-agent-ruby#703]
Rails integration automatically enables transaction recording around every controller method. This is frustrating if I want to override that behaviour, because right now transactions cannot be nested.

**Comment by estolfo** [comment]
Hi @rtymchyk thanks for your question! What behavior are you looking for instead? Would you like to only create transactions for certain controller methods?

**Comment by rtymchyk** [comment]
@estolfo The use case is that I have a controller in my Rails app that handles GraphQL requests. Automatic instrumentation for that controller is more or less useless because graph queries can be anything, so instead I have to add custom instrumentation (transactions based on query names provided by the client). 

I found out I can use `ignore_url_patterns` config, which functionally does what I want, so we could close the ticket. It would be a nice-to-have something more Rails friendly though, e.g. ignore `graphql#execute` vs. `^/graph`

**Comment by estolfo** [comment]
Thanks for the feedback! We are planning on adding support for GraphQL in the future, so that might be another way to get the specific instrumentation you're interested in.

**Comment by rtymchyk** [comment]
Yes, would love to see built-in graphql support :)

**Comment by mikker** [comment]
@rtymchyk We just released initial GraphQL support and would love to get some feedback: https://github.com/elastic/apm-agent-ruby/blob/master/docs/graphql.asciidoc

**Comment by rtymchyk** [comment]
Will give it a shot, thanks!

**Comment by rtymchyk** [comment]
@mikker I've installed the GraphQL tracer but I see no record of Graph transactions in my `[AMP] Transactions` dashboard. Is there something else I need to configure?
