### ISSUE TITLE
Allow custom data on ElasticAPM::Span::Context

### ISSUE THREAD

**Issue by bilby91** [elastic/apm-agent-ruby#705]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a tracer for [GraphQL]().

I'm sending the data to Elastic using the `ElasticAPM.with_span` API. So far the only problem that I've found is that any custom context that I add to my Span::Context is not serialized in the JSON.

**Describe the solution you'd like**
I would like to be able to specify custom data in my Span::Context that will be forwarded to the Elastic.

**Describe alternatives you've considered**
Another approach would be to build the GraphQL tracer in the gem. 

**Example Code**

```
class ElasticAPMTracking < GraphQL::Tracing::PlatformTracing
  TYPE = 'graphql'

  self.platform_keys = {
    'lex' => 'lex.graphql',
    'parse' => 'parse.graphql',
    'validate' => 'validate.graphql',
    'analyze_query' => 'analyze.graphql',
    'analyze_multiplex' => 'analyze.graphql',
    'execute_multiplex' => 'execute.graphql',
    'execute_query' => 'execute.graphql',
    'execute_query_lazy' => 'execute.graphql',
  }

  class GraphQLContext < ElasticAPM::Span::Context
    include ElasticAPM::NaivelyHashable

    attr_accessor :graphql

    def initialize(graphql: nil, **kargs)
      super(kargs)

      @graphql = ExecuteQueryContext.new(graphql) if graphql
    end
  end

  class ExecuteQueryContext
    include ElasticAPM::NaivelyHashable
    attr_accessor :selected_operation_name, :selected_operation_type, :query_string

    def initialize(selected_operation_name:, selected_operation_type:, query_string:)
      @selected_operation_name = selected_operation_name 
      @selected_operation_type = selected_operation_type
      @query_string = query_string
    end
  end

  def platform_trace(platform_key, key, data, &block)
    if key == 'execute_query'
      context = GraphQLContext.new(
        graphql: {
          selected_operation_name: data[:query].selected_operation_name,
          selected_operation_type: data[:query].selected_operation.operation_type,
          query_string: data[:query].query_string,
        }
      )
    end

    ElasticAPM.with_span(
      key, 
      TYPE, 
      context: context, 
      include_stacktrace: false, 
      &block
    )
  end
end
```

**Comment by mikker** [comment]
You could send it as `custom_context` or `label`s, eg https://www.elastic.co/guide/en/apm/agent/ruby/current/context.html#context.

The main difference between the two is that the first supports any JSON-like structure, but is _not_ indexed in ES. Meaning that it isn't queryable. Labels are queryable but are restricted to strings (max 1024 chars), numbers and booleans.

Do you think that could work?

**Comment by bilby91** [comment]
I think that can work out for the moment! 

Side question, is there any plan on supporting a better visualization on APM side for GraphQL metrics ?  

Thanks!

**Comment by bilby91** [comment]
@mikker Based on this #703, is there any ETA for native support for GraphQL ? We would love to see that :)

**Comment by mikker** [comment]
No ETA, sorry. I'm starting to look into it now, that's all I can say 😊

**Comment by mikker** [comment]
Hey @bilby91! We just released initial GraphQL support and would love to get some feedback: https://github.com/elastic/apm-agent-ruby/blob/master/docs/graphql.asciidoc
