### ISSUE TITLE
Investigate support for web servers with master/worker architecture

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-agent-ruby#724]
Web servers such as `puma` in "clustered mode" and `unicorn` fork workers from the main (master) process. This leads to undesired behavior, for example: https://github.com/elastic/apm-agent-ruby/issues/696

We should come up with a way to detect forking and adapt.

**Comment by mikker** [comment]
Could potentially also be the missing link to make Resque integration easier. Saying that with only a hunch 😅

**Comment by estolfo** [comment]
For research: https://github.com/elastic/apm-agent-python/pull/636

**Comment by vidok** [comment]
I also think that this method 
https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/agent.rb#L59 doesn't answer the question. It just checks an object, I assume it should be something like 
```Ruby
def running?
  central_config.running? &&\
  metrics.running? &&\ 
  instrumenter.running? &&\
  transport.running?
end
```
It would be check everything that should be up and running.

**Comment by vidok** [comment]
Anyway, we should find a simple way to start threads in child processes because `fork` doesn't copy running threads.

**Comment by estolfo** [comment]
yes, indeed. Thanks for your feedback. I'll ping you when we start working on this!

**Comment by vidok** [comment]
@estolfo I would be happy to help. I already started working on it :). I'm also okay if you implement this. 

Thank you.

**Comment by estolfo** [comment]
We always welcome pull requests! Please do open one if you find a solution :)

**Comment by mikker** [comment]
> Anyway, we should find a simple way to start threads in child processes because fork doesn't copy running threads.

Definitely. Restarting the whole agent is also not very expensive and perhaps that could simplify things.

**Comment by phlegx** [comment]
Hi Guys! Is someone already working on this? Will it be in 7.7?

**Comment by estolfo** [comment]
@phlegx Yes, we are working on this and hope to have it in the next release. In the meantime, can you tell us more about your setup? What web server are you using and with what configuration?

Depending on the web server you are using, you might be able to resolve any issues by using the `ElasticAPM.restart` method in an after fork hook. [That is what we do for `Resque`](https://github.com/elastic/apm-agent-ruby/blob/460c14201bbaf71500897449d88d56dfabb3b239/lib/elastic_apm/spies/resque.rb#L16-L18), for example.

**Comment by phlegx** [comment]
Hi @estolfo! Thanks a lot for the info. 

We are currently using Unicorn, but maybe switch soon to Puma. I saw some hack in the other thread to make it work with Unicorn. 

For me it is ok if it is working in the next release, so I didn't apply the hack on my side atm.

**Comment by HenriqueKraemer** [comment]
Same issue here! I have _Transaction duration_ and _RPM_ but no _Time spent by span type_.

Im running on Passenger as a Nginx module setup (https://www.phusionpassenger.com/library/config/nginx/intro.html) .

![Screenshot from 2020-04-27 19-44-27](https://user-images.githubusercontent.com/822026/80428727-f0024380-88c0-11ea-8b1c-642126ac176f.png)

- **OS:** Linux/Mac OS
- **Ruby version:** 2.3.8
- **Framework and version:** Rails 4.2.11.1
- **Agent version:** 3.6
- **Phusion Passenger:** 6.0.4
- **Nginx:** 1.14.0

**Comment by estolfo** [comment]
Hi @vidok, @HenriqueKraemer, and @phlegx, I have a draft PR to automatically detect forking and restart the agent's threads. It would be wonderful if you could try it in your testing environments and let me know if it works for you. You can find the PR [here](https://github.com/elastic/apm-agent-ruby/pull/783). Thanks!

**Comment by HenriqueKraemer** [comment]
It worked 👍, I tested locally with Phusion Passenger (6.0.4) on multi-process mode (using nginx and builtin engines) and DelayedJob (4.1.7).

**Gemfile**
`gem 'elastic-apm', :git => "git@github.com:estolfo/apm-agent-ruby.git", :branch => "forking-2"`

**Phusion Passenger**
![Captura de Tela 2020-05-04 às 16 46 07](https://user-images.githubusercontent.com/822026/81007179-2858d300-8e27-11ea-8b6f-42fc9b56c822.png)

**DelayedJob**
![Captura de Tela 2020-05-04 às 17 08 19](https://user-images.githubusercontent.com/822026/81008918-19275480-8e2a-11ea-9f70-a1fa3446ef65.png)

**Comment by HenriqueKraemer** [comment]
> Hi @vidok, @HenriqueKraemer, and @phlegx, I have a draft PR to automatically detect forking and restart the agent's threads. It would be wonderful if you could try it in your testing environments and let me know if it works for you. You can find the PR [here](https://github.com/elastic/apm-agent-ruby/pull/783). Thanks!

It worked 👍, I tested locally with Phusion Passenger (6.0.4) on multi-process mode (using nginx and builtin engines) and DelayedJob (4.1.7).

**Gemfile**
`gem 'elastic-apm', :git => "git@github.com:estolfo/apm-agent-ruby.git", :branch => "forking-2"`

**Phusion Passenger**
![Captura de Tela 2020-05-04 às 16 46 07](https://user-images.githubusercontent.com/822026/81007179-2858d300-8e27-11ea-8b6f-42fc9b56c822.png)

**DelayedJob**
![Captura de Tela 2020-05-04 às 17 08 19](https://user-images.githubusercontent.com/822026/81008918-19275480-8e2a-11ea-9f70-a1fa3446ef65.png)

**Comment by estolfo** [comment]
That's great news, @HenriqueKraemer! Thank you for testing it.

**Comment by HenriqueKraemer** [comment]
> That's great news, @HenriqueKraemer! Thank you for testing it.

Also tested against puma and worked too!

Puma clustered mode:
`puma -t 8:32 -w 3 -p 3000`

![Captura de Tela 2020-05-05 às 16 45 59](https://user-images.githubusercontent.com/822026/81109258-33c40100-8ef0-11ea-91f0-aed12e9794cc.png)

Any prediction when this change will be available on "master"?

**Comment by estolfo** [comment]
@HenriqueKraemer thank you for testing! I'm hoping to get a few more users to test it before merging into master. But it won't be long before this is released. 
I'd also like Resque to be tested by someone because these changes affect our support for that gem as well. Any chance you use Resque?

**Comment by HenriqueKraemer** [comment]
> @HenriqueKraemer thank you for testing! I'm hoping to get a few more users to test it before merging into master. But it won't be long before this is released.
> I'd also like Resque to be tested by someone because these changes affect our support for that gem as well. Any chance you use Resque?

I can try to put something to work on Resque (but I never used before). I'll make some tests and report back.

We are currently switching from DJ to Sidekiq..

**Comment by cernyjakub** [comment]
I can confirm it works on Debian 10 with Apache + Passenger 5.0.30 combo (both from standard Debian repos).

Looking forward for a merge ;)

**Comment by estolfo** [comment]
wooohoo, thanks for testing, @cernyjakub !
