### ISSUE TITLE
Add Sidekiq instrumentation and error reporting

### ISSUE THREAD

**Issue by mikker** [elastic/apm-agent-ruby#73]

**Comment by assembler** [comment]
Any docs on how to use sidekiq integration?

**Comment by mikker** [comment]
Hi @assembler! It should _just work_. Are you experiencing something else?

**Comment by assembler** [comment]
Thanks @mikker! I thought i need to register middleware or something to make it work. Cheers

**Comment by brightredchilli** [comment]
This has been answered for a while, but I'm a little confused about how this should 'just work'.

The instrumentation [here](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/spies/sidekiq.rb) spies on Processor, and attaches itself to the Sidekiq middleware chain. Ruby apps using sidekiq interface with Sidekiq::Worker, which, afaik, only writes an entry into the redis cache, which the sidekiq process polls.

This sidekiq process is often run separately from the main app - in our case, on a separate kubernetes pod. In this situation, the elasticapm library needs to be included when running the sidekiq server process. Does that sound right, or am I missing something?

**Comment by brightredchilli** [comment]
actually, i think i answered my own question >.< sidekiq loads rails and that should load the apm gem. However I'm not seeing any traces from my sidekiq instances, so ill have to dive deeper...

**Comment by mikker** [comment]
Feel free to update here if you come any closer to a solution!

**Comment by agriffin-indigo** [comment]
> actually, i think i answered my own question >.< sidekiq loads rails and that should load the apm gem. However I'm not seeing any traces from my sidekiq instances, so ill have to dive deeper...

I'm not seeing this work either. We're launching sidekiq with `bundle exec sidekiq` and it's not getting instrumented.

Relevant application config: 
```ruby
module SettlementApi
  class Application < Rails::Application
    ...
    
    # Elastic APM setup
    config.elastic_apm.service_name = ENV['IA_PROJECT_NAME'] || 'settlement-api'
    config.elastic_apm.environment = ENV['IA_BALER_ENV'] || ENV['IA_ENV'] || ENV['RAILS_ENV']
    config.elastic_apm.enabled = ENV['IA_APM_ACTIVE'] || false
  end
end
```

**Comment by mikker** [comment]
I haven't dug deep on this, but it might be due to Sidekiq starting before loading Rails or somehow Rails' config phase isn't being run. Could you try moving your config to `config/elastic_apm.yml` instead and see it changes anything? It supports ERB, so with your setup above could be like

```yml
service_name: <%= ENV['IA_PROJECT_NAME'] || 'settlement-api' %>
# ... and so on
```
