### ISSUE TITLE
License headers and other legal stuff

### ISSUE THREAD

**Issue by lreuven** [elastic/apm-agent-ruby#744]
missing the last mile  - https://github.com/elastic/open-source/issues/39

**Comment by estolfo** [comment]
*Product build produces a list of dependencies included both in source code and in the product distribution*:
- Dependencies are listed in the [`.gemspec`](https://github.com/elastic/apm-agent-ruby/blob/master/elastic-apm.gemspec#L21-L22) file. (namely, `concurrent-ruby` and `http`). They also appear on the rubygems page for the gem under [`RUNTIME DEPENDENCIES`](https://rubygems.org/gems/elastic-apm)

*For each dependency, contents of dependency's NOTICE.txt*
- Does not exist for either runtime dependency (`concurrent-ruby` and `http`)
