### ISSUE TITLE
CentralConfig stops fetching entirely when there's a network error

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-agent-ruby#771]
If a network error is encountered when fetching the remote config (i.e. a `HTTP::ConnectionError`), a bug in `CentralConfig#schedule_next_fetch` will skip scheduling the next fetch. Fetches are always scheduled by the last fetch in a chain, so as soon as a fetch has not been scheduled, the chain is broken and no future fetches will occur.

The culprit is in [this line](https://github.com/elastic/apm-agent-ruby/blob/v3.6.0/lib/elastic_apm/central_config.rb#L154). When a network error is encountered, `headers` will be `nil`. An error would then be raised and the new `@scheduled_task` [here](https://github.com/elastic/apm-agent-ruby/blob/v3.6.0/lib/elastic_apm/central_config.rb#L160) will never be created.

Looking at the big picture, it might be safer and more efficient to use a `TimerTask` so a new `ScheduledTask` object is not created each time a config needs to be fetched and so that the "chain" dependency is avoided.\

Agent version is `3.6.0`

**Comment by gaurav6192** [comment]
@estolfo is it resolved? In which version?

**Comment by estolfo** [comment]
Hi @gaurav6192 This is resolved as of agent version 3.7.0. Are you observing an issue with central config?
