### ISSUE TITLE
GraphQL Tracer: transactions are all unnamed

### ISSUE THREAD

**Issue by rtymchyk** [elastic/apm-agent-ruby#779]
## Describe the bug
All transactions that are recorded with the GraphQL tracer are bucketed into `GraphQL: [unnamed]`.

## Steps to reproduce
Fire any query to the backend such as `query HelloWorld { viewer { user { id } } }`

## Expected behavior
Should see a transaction `GraphQL: HelloWorld`

## Actual behavior
Should see a transaction `GraphQL: [unnamed]`

## Environment
- **OS**: Linux
- **Ruby version**: 2.5.7
- **Framework and version**: 5.1.6.2
- **APM Server version**: ?
- **Agent version**: 3.6.0

## Additional context
I don't think this is the correct way to extract the operation name: https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/graphql.rb#L60

If you look at any of the other custom tracers, such as Datadog, https://github.com/rmosolgo/graphql-ruby/blob/1a9a20f3da629e63ea8e5ee8400be82218f9edc3/lib/graphql/tracing/data_dog_tracing.rb#L32, the correct method is `query.selected_operation_name` as indicated by https://github.com/rmosolgo/graphql-ruby/blob/1a9a20f3da629e63ea8e5ee8400be82218f9edc3/lib/graphql/query.rb#L61

**Comment by estolfo** [comment]
Hi @rtymchyk 
Thanks for your question. We chose to use `query.operation_name` for the Transaction name and from the example you've provided, the transaction should have the name `HelloWorld`. We test the name [here](https://github.com/elastic/apm-agent-ruby/blob/master/spec/integration/graphql_spec.rb#L182-L200). Do you see a difference between how we are testing for the name and what you have in your code?

**Comment by rtymchyk** [comment]
> Hi @rtymchyk 
> Thanks for your question. We chose to use `query.operation_name` for the Transaction name and from the example you've provided, the transaction should have the name `HelloWorld`. We test the name [here](https://github.com/elastic/apm-agent-ruby/blob/master/spec/integration/graphql_spec.rb#L182-L200). Do you see a difference between how we are testing for the name and what you have in your code?

I tried to take a stab at doing this fix myself. Your tests pass with existing state and with the proposed fix, but I wasn't able to get a failing test with the current state. I admit I don't know much about the internals of graphql-ruby, that's why I've referenced the other APM's tracers as good examples (I've used them before as well). 

The only difference I can see in my code is we handle batching/multiplexing for Apollo specifically (it sends queries slightly differently) but I don't see how it can make a difference since you already test for batching in a slightly different format.

**Comment by estolfo** [comment]
@rtymchyk Thanks for looking into this. So does the example you cited in the description (`query HelloWorld { viewer { user { id } } }`) show `GraphQL: [unnamed]` or `GraphQL: HelloWorld` when you test it?

**Comment by rtymchyk** [comment]
> @rtymchyk Thanks for looking into this. So does the example you cited in the description (`query HelloWorld { viewer { user { id } } }`) show `GraphQL: [unnamed]` or `GraphQL: HelloWorld` when you test it?
> 

Yes unnamed, and every real query that is fired from a production Apollo server backend is reported as unnamed as well.

**Comment by mikker** [comment]
Closing because Elastic APM wasn't the culprit ([#](https://github.com/elastic/apm-agent-ruby/pull/807#issuecomment-634776553))
