### ISSUE TITLE
Couldn't establish connection to APM Server: "#<NoMethodError: undefined method `flush' for nil:NilClass>"

### ISSUE THREAD

**Issue by Ingstrup** [elastic/apm-agent-ruby#792]
## Describe the bug
The apm agent log says:

`Couldn't establish connection to APM Server:` 
with the following two messages:
`<NoMethodError: undefined method 'flush' for nil:NilClass>`
and sometimes I see 
`#<Errno::ESPIPE: Invalid seek>`

With loglevel 0 I see 
`Closing request with reason timeout` and 
`Closing writer with reason timeout`

I have had this problem on and off for some time. 
It works on our staging environment. It used to work in production as well but stopped a few days ago, just like that. In Kibana I can see the graph drop to zero and then silence.

Edit: I just noticed our staging machine's apm data also took a nosedive yesterday. I'll spare you the screen shots. Unless you want them.

## Environment

- **OS**: Alpine on Docker on Debian 9 
- **Ruby version**: 2.5.8
- **Rails**: 4.2.11
- **APM Server version**: 7.6.1
- **Agent version**: 3.6.0 (tried with several others too)
- **Http Gem version**: 4.4.1

## Additional context

- The resources on the server look just fine.

- I am able to reach the apm_server by curl from anywhere I try. I even tried using sending a GET with HTTParty from a controller to apm_server.

- A strange thing is that if I change the service_name in elastic_apm.yml and start the app (in docker), the new servicename shows up in kibana. So something comes through.

- I see three spikes in yesterdays Requests per minute graph where a single transaction seems to have made it through. This could have happened after app restarts. 

- Currently a few other rails (5) apps and a sinatra app reports to the apm_server with no issues.

- I got the full queue message and remedied that by increasing the pool size. This did not fix the failing connection issue, however. 
Now I'm seeing the `Queue is full (256 items)` message again though. Maybe that's because it doesn't connect to the server and empty the queue. I don't know.

I think it's the flush call in lib/elastic_apm/transport/connection/http.rb in the method `request(method, url, body: nil, headers: nil)` that throws the NoMethodError. On my local machine I added a `try` for the flush call. That stopped the error, but of course didn't fix the issue.

I don't know if this helps, but I wanted to be thorough:

```
   39:         def request(method, url, body: nil, headers: nil)
   40:           byebug
=> 41:           @client.send(
   42:             method,
   43:             url,
   44:             body: body,
   45:             headers: (headers ? @headers.merge(headers) : @headers).to_h,
(byebug) method
:post
(byebug) url
"http://myserver:8200/intake/v2/events"
(byebug) body
#<IO:fd 10>
(byebug) headers
{:"User-Agent"=>"elastic-apm-ruby/3.6.0 http.rb/4.4.1 ruby/2.5.1", "Content-Type"=>"application/x-ndjson", "Transfer-Encoding"=>"chunked", "Content-Encoding"=>"gzip"}
```

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    service_name: 'MyApp'
    
    server_url: "http://myserver:8200"
    
    breakdown_metrics: true
    
    capture_body: 'all'
    
    instrumented_rake_tasks: ['mytask:task1']
    
    log_level: 1
    log_path: 'log/elastic_apm.log'
    logger: <%= Logger.new('log/elastic_apm.log') %>
    
    pool_size: 4
    ```
  </details>

**Comment by mikker** [comment]
Hi @Ingstrup! Sounds to me like it could be an issue with Rails 4.2? I'll investigate a bit and see if I can dig something up.

What server lib are you using? Puma? Passenger?

**Comment by Ingstrup** [comment]
puma (4.3.3) I believe. According to my Gemfile.lock

The thing about it that bugs me, is that it used to work fine. Then nothing changes, and it stops.

I appreciate anything you can do about it.

**Comment by mikker** [comment]
The `Queue is full` message suggests that the worker that should pull from that queue has somehow died and is apparently not restarting. The on/off behaviour also supports that theory.

Now, why does it die? The undefined `flush` or the `ESPIPE` exception might be clues. The timeout messages are expected and good signs. The wording really needs to be changed as they are confusing everyone 😊

Could you try upgrading to 3.7 and run the agent with `debug_level: 0` for a bit to see if we get more clues?

**Comment by Ingstrup** [comment]
> Could you try upgrading to 3.7 and run the agent with `debug_level: 0` for a bit to see if we get more clues?

Will do.

**Comment by Ingstrup** [comment]
Sadly nothing new that I can see.

```
D, [2020-05-25T09:47:21.506917 #7] DEBUG -- : [ElasticAPM] Collecting metrics
D, [2020-05-25T09:47:21.541222 #7] DEBUG -- : [ElasticAPM] [THREAD:47382001570440]: Opening new request
D, [2020-05-25T09:47:21.542359 #7] DEBUG -- : [ElasticAPM] [THREAD:47382001571700]: Opening new request
D, [2020-05-25T09:47:21.543032 #7] DEBUG -- : [ElasticAPM] [THREAD:47382001571080]: Opening new request
E, [2020-05-25T09:47:21.584658 #7] ERROR -- : [ElasticAPM] Couldn't establish connection to APM Server:
"#<NoMethodError: undefined method `flush' for nil:NilClass>"
E, [2020-05-25T09:47:21.595304 #7] ERROR -- : [ElasticAPM] Couldn't establish connection to APM Server:
"#<NoMethodError: undefined method `flush' for nil:NilClass>"
E, [2020-05-25T09:47:21.601458 #7] ERROR -- : [ElasticAPM] Couldn't establish connection to APM Server:
"#<NoMethodError: undefined method `flush' for nil:NilClass>"
D, [2020-05-25T09:47:22.708187 #238] DEBUG -- : [ElasticAPM] [THREAD:47039796377180]: Opening new request
E, [2020-05-25T09:47:22.748387 #238] ERROR -- : [ElasticAPM] Couldn't establish connection to APM Server:
"#<NoMethodError: undefined method `flush' for nil:NilClass>"
D, [2020-05-25T09:47:23.299435 #238] DEBUG -- : [ElasticAPM] [THREAD:47039796461300]: Opening new request
E, [2020-05-25T09:47:23.341755 #238] ERROR -- : [ElasticAPM] Couldn't establish connection to APM Server:
"#<NoMethodError: undefined method `flush' for nil:NilClass>"
D, [2020-05-25T09:47:25.184228 #246] DEBUG -- : [ElasticAPM] [THREAD:47039797363340]: Closing request with reason timeout
D, [2020-05-25T09:47:25.184374 #246] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:25.278985 #246] DEBUG -- : [ElasticAPM] [THREAD:47039797363340]: Closing request with reason timeout
D, [2020-05-25T09:47:25.279079 #246] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:25.340410 #246] DEBUG -- : [ElasticAPM] [THREAD:47039797363340]: Closing request with reason timeout
D, [2020-05-25T09:47:25.340545 #246] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:25.377854 #246] DEBUG -- : [ElasticAPM] [THREAD:47039797363340]: Closing request with reason timeout
D, [2020-05-25T09:47:25.378250 #246] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:25.911193 #238] DEBUG -- : [ElasticAPM] [THREAD:47039796575480]: Closing request with reason timeout
D, [2020-05-25T09:47:25.911317 #238] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:25.929032 #238] DEBUG -- : [ElasticAPM] [THREAD:47039796575480]: Closing request with reason timeout
D, [2020-05-25T09:47:25.929105 #238] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:26.298787 #7] DEBUG -- : [ElasticAPM] [THREAD:47382002534420]: Closing request with reason timeout
D, [2020-05-25T09:47:26.298920 #7] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:26.497859 #250] DEBUG -- : [ElasticAPM] [THREAD:47039797074680]: Closing request with reason timeout
D, [2020-05-25T09:47:26.497987 #250] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:26.513771 #250] DEBUG -- : [ElasticAPM] [THREAD:47039797074680]: Closing request with reason timeout
D, [2020-05-25T09:47:26.513845 #250] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:26.525571 #250] DEBUG -- : [ElasticAPM] [THREAD:47039797074680]: Closing request with reason timeout
D, [2020-05-25T09:47:26.525670 #250] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:26.557240 #250] DEBUG -- : [ElasticAPM] [THREAD:47039797074680]: Closing request with reason timeout
D, [2020-05-25T09:47:26.557361 #250] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:29.572974 #258] DEBUG -- : [ElasticAPM] [THREAD:47039797407680]: Closing request with reason timeout
D, [2020-05-25T09:47:29.573105 #258] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:29.612655 #258] DEBUG -- : [ElasticAPM] [THREAD:47039797407680]: Closing request with reason timeout
D, [2020-05-25T09:47:29.612759 #258] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:29.622993 #258] DEBUG -- : [ElasticAPM] [THREAD:47039797407680]: Closing request with reason timeout
D, [2020-05-25T09:47:29.623079 #258] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-05-25T09:47:29.650979 #258] DEBUG -- : [ElasticAPM] [THREAD:47039797407680]: Closing request with reason timeout
D, [2020-05-25T09:47:29.651054 #258] DEBUG -- : [ElasticAPM] Closing writer with reason timeout

```

**Comment by franee** [comment]
Hello, 

I can confirm I am getting more or less the same thing, apm server is up but the agent can't seem to connect to it:
```
I, [2020-11-18T22:48:57.493372 #66156]  INFO -- : [3.12.1] Starting agent, reporting to http://127.0.0.1:8200
D, [2020-11-18T22:48:57.493546 #66156] DEBUG -- : [ElasticAPM] Starting CentralConfig
D, [2020-11-18T22:48:57.494000 #66156] DEBUG -- : [ElasticAPM] [PID:66156]: Starting Transport
D, [2020-11-18T22:48:57.494064 #66156] DEBUG -- : [ElasticAPM] [PID:66156]: Booting worker...
D, [2020-11-18T22:48:57.494801 #66156] DEBUG -- : [ElasticAPM] Starting instrumenter
D, [2020-11-18T22:48:57.497776 #66156] DEBUG -- : [ElasticAPM] Starting metrics
D, [2020-11-18T22:48:57.498446 #66156] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::CpuMemSet'
W, [2020-11-18T22:48:57.498588 #66156]  WARN -- : [ElasticAPM] Unsupported platform 'darwin' - Disabling system metrics
D, [2020-11-18T22:48:57.498673 #66156] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::VMSet'
D, [2020-11-18T22:48:57.498803 #66156] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::BreakdownSet'
D, [2020-11-18T22:48:57.498910 #66156] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::TransactionSet'
D, [2020-11-18T22:48:57.499722 #66156] DEBUG -- : [ElasticAPM] Collecting metrics
D, [2020-11-18T22:48:57.594343 #66156] DEBUG -- : [ElasticAPM] Registering subscriber
D, [2020-11-18T22:49:04.920154 #66156] DEBUG -- : [ElasticAPM] [THREAD:70143546875080]: Opening new request
D, [2020-11-18T22:49:14.899519 #66156] DEBUG -- : [ElasticAPM] [THREAD:70143551541060]: Closing request with reason timeout
D, [2020-11-18T22:49:14.901012 #66156] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
E, [2020-11-18T22:49:19.902857 #66156] ERROR -- : [ElasticAPM] [THREAD:70143551541060]: APM Server not responding in time, terminating request
D, [2020-11-18T22:49:27.503914 #66156] DEBUG -- : [ElasticAPM] Collecting metrics
D, [2020-11-18T22:49:27.527075 #66156] DEBUG -- : [ElasticAPM] [THREAD:70143546875080]: Opening new request
^AnD, [2020-11-18T22:49:49.596489 #66156] DEBUG -- : [ElasticAPM] [THREAD:70143551541060]: Closing request with reason timeout
D, [2020-11-18T22:49:49.597456 #66156] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
E, [2020-11-18T22:49:53.941510 #66156] ERROR -- : [ElasticAPM] APM Server responded with an error:
"{\"accepted\":0,\"errors\":[{\"message\":\"EOF\"}]}\n"
D, [2020-11-18T22:49:57.506150 #66156] DEBUG -- : [ElasticAPM] Collecting metrics
D, [2020-11-18T22:49:57.529295 #66156] DEBUG -- : [ElasticAPM] [THREAD:70143546875080]: Opening new request
D, [2020-11-18T22:50:07.512714 #66156] DEBUG -- : [ElasticAPM] [THREAD:70143551541060]: Closing request with reason timeout
D, [2020-11-18T22:50:07.512941 #66156] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
```

apm-server is running via docker and I can telnet to it.

```
      apm-server -e
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
````

**Comment by mikker** [comment]
Hi @franee! I don't think that this issue and yours are the same.
Could you please provide your APM Server, ElasticAPM, Ruby and Rails versions?

**Comment by franee** [comment]
@mikker, using latest elastic 7.10.0 releases.
```
docker.elastic.co/apm/apm-server:7.10.0
docker.elastic.co/elasticsearch/elasticsearch:7.10.0
Rails 5.2.4.4
```

**Comment by gowthamgts** [comment]
facing the same issue

**Comment by mikker** [comment]
@gowthamgts The one with `[ElasticAPM] APM Server responded with an error:
"{\"accepted\":0,\"errors\":[{\"message\":\"EOF\"}]}\n"`? Are you using the same versions as @franee?

**Comment by gowthamgts** [comment]
@mikker - I'm getting this:
```
D, [2020-11-23T23:06:13.426512 #15922] DEBUG -- : [ElasticAPM] Collecting metrics
D, [2020-11-23T23:06:13.437730 #15922] DEBUG -- : [ElasticAPM] [THREAD:47004306301520]: Opening new request
D, [2020-11-23T23:06:17.494900 #16022] DEBUG -- : [ElasticAPM] [THREAD:47004305832360]: Opening new request
D, [2020-11-23T23:06:18.033031 #16025] DEBUG -- : [ElasticAPM] [THREAD:47004306196260]: Closing request with reason timeout
D, [2020-11-23T23:06:18.033538 #16025] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-11-23T23:06:18.040036 #16025] DEBUG -- : [ElasticAPM] APM Server responded with status 202
D, [2020-11-23T23:06:18.176922 #16022] DEBUG -- : [ElasticAPM] Collecting metrics
D, [2020-11-23T23:06:19.153574 #16025] DEBUG -- : [ElasticAPM] [THREAD:47004305827940]: Opening new request
D, [2020-11-23T23:06:23.432989 #15922] DEBUG -- : [ElasticAPM] [THREAD:70309554263560]: Closing request with reason timeout
D, [2020-11-23T23:06:23.433534 #15922] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-11-23T23:06:23.437012 #15922] DEBUG -- : [ElasticAPM] APM Server responded with status 202
D, [2020-11-23T23:06:27.488519 #16022] DEBUG -- : [ElasticAPM] [THREAD:47004306201000]: Closing request with reason timeout
D, [2020-11-23T23:06:27.488869 #16022] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-11-23T23:06:27.493793 #16022] DEBUG -- : [ElasticAPM] APM Server responded with status 202
D, [2020-11-23T23:06:29.061371 #16022] DEBUG -- : [ElasticAPM] [THREAD:47004305832360]: Opening new request
D, [2020-11-23T23:06:29.146924 #16025] DEBUG -- : [ElasticAPM] [THREAD:47004306196260]: Closing request with reason timeout
D, [2020-11-23T23:06:29.147185 #16025] DEBUG -- : [ElasticAPM] Closing writer with reason timeout
D, [2020-11-23T23:06:29.155172 #16025] DEBUG -- : [ElasticAPM] APM Server responded with status 202
```

I was able to get response from the apm-server by issuing curl get:
```
{
  "build_date": "2020-11-09T18:38:48Z",
  "build_sha": "d5f4e01307540517d964edfe4af9d31227e0ce91",
  "version": "7.10.0"
}
```

I was able to see the data on APM server on kibana, but not sure why I'm seeing this error though. Let me know if you need any more info.

**Comment by mikker** [comment]
@gowthamgts That's not an error. That's the expected behaviour. However, you are not the first person to read it as an error, so we'll change the wording of the message in a future version. Sorry for the confusion.

**Comment by mikker** [comment]
@Ingstrup, did you discover anything new here? Is this still an issue?

**Comment by Ingstrup** [comment]
> @Ingstrup, did you discover anything new here? Is this still an issue?

I did not discover anything new. I expect it still is a problem, but I have been away on paternity leave for several months and have been busy with other tasks.

Has there been any updates recently? I know rails 4 is nearing end of life, if it isn't already, so I get if this is not high priority.

**Comment by mikker** [comment]
There have been some updates, but I'm not sure they'll change anything around your `undefined method 'flush' for nil:NilClass` error. Not really sure where to look next.

**Comment by bv-ritesh** [comment]
Sorry, I am unable to open a new issue so I am posting it here.

## Describe the bug
Seeing errors in my production logs.
Error backtrace:
3 2021-03-19 04:51:48 +0100 XXXX 20330 : 47250358893000 : ERROR - NoMethodError - undefined method `outcome=' for false:FalseClass - ["/home/bvserver/.rvm/gems/ruby-2.3.3/gems/elastic-apm-3.13.0/lib/elastic_apm/spies/mongo.rb:54:in `succeeded'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/monitoring.rb:288:in `block in succeeded'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/monitoring.rb:288:in `each'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/monitoring.rb:288:in `succeeded'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/monitoring/publishable.rb:72:in `command_succeeded'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/monitoring/publishable.rb:67:in `command_completed'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/server/connection_base.rb:179:in `block in deliver'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/server/connection_common.rb:124:in `ensure_connected'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/server/connection_base.rb:155:in `deliver'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/server/connection.rb:300:in `block in deliver'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/server/connection.rb:306:in `handle_errors'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/server/connection.rb:299:in `deliver'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/server/connection_base.rb:145:in `dispatch'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/operation/shared/executable.rb:63:in `dispatch_message'", "/home/bvserver/.rvm/gems/ruby-2.3.3/gems/mongo-2.13.0/lib/mongo/operation/insert/op_msg.rb:35:in `get_result'",

## Steps to reproduce
1. install and setup elastic APM on rails
2. use mongo db create query.
3. I made the transaction_max_spans: 100 then we started seeing errors.

## Expected behavior
No error should come and block the normal workflow of servers

## Environment
- **OS**: Ubuntu 18.04 
- **Ruby version**: 2.3.3
- **Framework and version**: 5.2.2.1
- **APM Server version**: 7.11.2
- **Agent version**: elastic-apm-3.13.0

## Additional context
The issue seems to be here in lib/elastic_apm/spies/mongo.rb 
```

def succeeded(event)
          span = pop_event(event)
          span&.outcome = Span::Outcome::SUCCESS
          span
        end
def pop_event(event)
          span = @events.delete(event.operation_id)
          return unless (curr = ElasticAPM.current_span)

          curr == span && ElasticAPM.end_span
        end
```
Now pop_event can give three values false, nil and event.

In case false is returned our **span&.outcome** becomes invalid.

**Comment by mikker** [comment]
@bv-ritesh I think #937 fixed this, included in 3.14.0. Update the agent gem and it's hopefully fixed.

**Comment by bv-ritesh** [comment]
@mikker thanks a lot.

**Comment by mikker** [comment]
No problem 😊 Thanks for using Elastic APM!
