### ISSUE TITLE
Views provided by engines appear in trace samples as "Absolute Path"

### ISSUE THREAD

**Issue by f-mer** [elastic/apm-agent-ruby#822]
## Describe the bug
The problem is `self.__view_paths = app.config.paths['app/views'].existent` in `config.rb`. This only adds paths of the main application. I could not figure out a way to configure this variable and hence the underscores i guess it is not meant to be configurable :sweat_smile: 

For the time being I just patched it like this

```rb
initializer 'patch_elastic_apm', before: 'elastic_apm.initialize' do
  ::ElasticAPM::Config.prepend(Module.new do
    def set_rails(app)
      super
      self.__view_paths = ::ActionController::Base.view_paths.map(&:to_s)
    end
  end)
end
```

## Steps to reproduce

Mount a rails engine.

## Expected behavior

Partials of the engine show up.

## Environment

- **OS**: Linux
- **Framework and version**: Rails 5.2.4
- **APM Server version**: 7.8.0
- **Agent version**: elastic-apm (3.8.0)

**Comment by mikker** [comment]
This is wonderful! Have you confirmed that your patch fixes the paths?

**Comment by f-mer** [comment]
Yes, booted up a [local installation](https://www.elastic.co/guide/en/apm/get-started/current/quick-start-overview.html) and pointed the application to it.

**Comment by mikker** [comment]
Great! Would you like to submit a PR and get the credit?

**Comment by mikker** [comment]
I'm having some second thoughts about this. Can you tell me more about how you're using engines? Do you have them bundled inside your app?

**Comment by mikker** [comment]
Something along the lines of what is described here https://www.hocnest.com/blog/creating-local-rails-engine/
