### ISSUE TITLE
Disabling metrics via metrics_interval is not working without disabling breakdown_metrics

### ISSUE THREAD

**Issue by danielfariati** [elastic/apm-agent-ruby#823]
## Describe the bug
`metrics_interval: 0` does not work unless `breakdown_metrics` is also set to `false`.

## Expected behavior
When disabling all metrics (with `metrics_interval: 0`), breakdown metrics should also be disabled (or, at least, work without having to change other parameters).

## Environment
- **OS**: Linux
- **Ruby version**: 2.5.8
- **Framework and version**: Rails 5.2.4.3
- **Agent version**: 3.8.0

## Partial Stacktrace

```
NoMethodError (undefined method `fetch' for nil:NilClass):
elastic-apm (3.8.0) lib/elastic_apm/metrics.rb:108:in `get'
elastic-apm (3.8.0) lib/elastic_apm/instrumenter.rb:311:in `update_span_metrics'
elastic-apm (3.8.0) lib/elastic_apm/instrumenter.rb:225:in `end_span'
elastic-apm (3.8.0) lib/elastic_apm/agent.rb:215:in `end_span'
elastic-apm (3.8.0) lib/elastic_apm.rb:240:in `end_span'
elastic-apm (3.8.0) lib/elastic_apm.rb:292:in `ensure in with_span'
elastic-apm (3.8.0) lib/elastic_apm.rb:292:in `with_span'
elastic-apm (3.8.0) lib/elastic_apm/spies/redis.rb:34:in `call'
```

**Comment by mikker** [comment]
This does sound like a bug. I'll take a look!
