### ISSUE TITLE
ActiveJob with delayed_job queue adapter not showing individual jobs

### ISSUE THREAD

**Issue by hashwin** [elastic/apm-agent-ruby#833]
## Describe the bug

Individual job details not showing up when using delayed job with activejob.
Simply shows up as 
```ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper```

## Steps to reproduce

Set ```config.active_job.queue_adapter = :delayed_job``` in application.rb
Create a few jobs and enqueue them using JobClass.perform_later

## Expected behavior

Individual job details should show up in APM. Instead, all jobs show up as ```ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper```

## Environment

- **OS**: Linux
- **Ruby version**: 2.6.6
- **Framework and version**: Rails 6.0.3.2
- **APM Server version**: 7.8.0
- **Agent version**: 3.8.0

**Comment by mikker** [comment]
I tried to simplify our name lookup a bit. Could you try my branch in the PR and see if it's any better: https://github.com/elastic/apm-agent-ruby/pull/843

**Comment by hashwin** [comment]
Sorry for the late reply, hadn't got a chance to test this till now.

Still seeing the problem, no change in behavior:
<img width="1204" alt="Transactions___O3Crm___Services___APM" src="https://user-images.githubusercontent.com/406115/91008045-1af46e00-e5fb-11ea-8af0-ee917efb2a06.png">

**Comment by mikker** [comment]
Can you provide an example job class?

**Comment by hashwin** [comment]
Delayed job v4.1.8

Just normal active jobs, eg.

```
# frozen_string_literal: true

require 'net/http'
require 'uri'

class GravatarJob < ApplicationJob
  queue_as :import

  def perform(user_id:)
    user = User.find(user_id)
    gravatar_url = user.gravatar_url
    uri = URI(gravatar_url)
    Net::HTTP.start('secure.gravatar.com', 443, use_ssl: true) do |http|
      request = Net::HTTP::Get.new uri
      res = http.request request
      if res.code == '200'
        user.metadata ||= {}
        user.metadata['avatar'] = { url: gravatar_url }
        user.save!
      end
    end
  end
end


```

**Comment by hashwin** [comment]
@mikker FYI I solved it by adding this to the APM:

https://github.com/hashwin/apm-agent-ruby/commit/d869dc1f6086482910fca066b48feda0957ff3a5

**Comment by mikker** [comment]
Wonderful! Thanks a bunch for that.

Make a PR and I'll merge it right away, then you can get the contribution credit as deserved 😊
