### ISSUE TITLE
Ruby metrics not found after APM Setup

### ISSUE THREAD

**Issue by jasonlake11** [elastic/apm-agent-ruby#836]
We have setup the Ruby apm-agent and the agent can be loaded in Kibana.
But for the metrics, we only see the CPU usage and System memory usage, cannot find any Ruby metrics listed here:
https://www.elastic.co/guide/en/apm/agent/ruby/current/metrics.html

From the document, only parameters of disabling metrics are mentioned, so I assumed all these metrics should be show if available. May I know any perquisites for the Ruby Metrics. Thank you!

**Comment by mikker** [comment]
Hi @jasonlake11. The APM UI for the language specific metrics aren't done yet. Until they are, this set of visualizations and a dashboard is provided https://github.com/elastic/apm-contrib/tree/master/apm-agent-ruby/dashboards.

Let me know how it works for you!

**Comment by estolfo** [comment]
@jasonlake11 were you able to make use of the visualizations and dashboard mentioned in the previous comment? Can we close this issue?

**Comment by estolfo** [comment]
I'm going to close this issue, please reopen it if you have further questions or trouble.
