### ISSUE TITLE
Deprecation warning after adding elastic-apm: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper

### ISSUE THREAD

**Issue by weilandia** [elastic/apm-agent-ruby#848]
## Describe the bug

Deprecation warning after adding elastic-apm:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.
```
There is a similar issue highlighted in this repo: https://github.com/JangoSteve/remotipart/issues/207, but I didn't seeing anything that stood out as the culprit in elastic-apm

## Steps to reproduce
```
rails new test_app
cd test_app
rails g model test_model
rails db:migrate
bundle add  elastic-apm
rails test
```

## Expected behavior

No deprecation warning

## Environment

- **OS**: macos
- **Ruby version**: 2.6.6
- **Framework and version**: Rails 6.0.3.2
- **APM Server version**: 7.8.1
- **Agent version**: 3.9

## Additional context

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    remember to mask any sensitive fields like tokens
    ```
  </details>

**Comment by mikker** [comment]
I don't see how the agent could cause this. We have nothing to do with ActionText.

**Comment by weilandia** [comment]
@mikker you can try it for yourself on a new rails app here: https://github.com/weilandia/es-apm-deprecation

Run the tests with and without the apm.

I'm guessing it has to do with how the railtie initializes, but again, not immediately clear.

**Comment by pzac** [comment]
I believe this commit https://github.com/elastic/apm-agent-ruby/commit/0a62cd9c0cb0ea99c4003184475f15eae374eae9 introduced the issue. elastic-apm 3.8.0 works fine, 3.9.0 triggers the deprecation warning

**Comment by mikker** [comment]
That definitely sounds plausible. I was already planning on reverting that change and I guess this just puts another nail in the coffin.

Marking this as closed as the Revert is merged. Feel free to re-open if the problem persists anyway. Thanks for reporting and helping out with the debugging!
