### ISSUE TITLE
The agent continuously calls system's hostname command

### ISSUE THREAD

**Issue by toncid** [elastic/apm-agent-ruby#860]
## Describe the bug

It seems that the APM is calling `hostname` constantly, causing an `auditd` log entries on our instances and flooding SIEM tools.

The likely problem is in the `ElasticAPM::Metadata::SystemInfo` class:

```ruby
hostname = @config.hostname || `hostname`.chomp
```

## Steps to reproduce

1. Run the app with minimum configuration (do not set the `hostname`).
2. Observe how often `hostname` is called.

## Expected behavior

Have the gem code cache the `hostname` result after the first run.

This can be circumvented in the app code, by setting the config explicitly - I need some confirmation.

## Environment

- **OS**: Amazon Linux 1
- **Ruby version**: 2.4.5
- **Framework and version**: 5.2.4.3
- **APM Server version**: 7.8.0
- **Agent version**: 3.8.0

## Additional context

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    config.elastic_apm.enabled = Settings.elastic_apm.server_url.present?
    config.elastic_apm.secret_token = Settings.elastic_apm.secret_token
    config.elastic_apm.server_url = Settings.elastic_apm.server_url
    config.elastic_apm.log_level = Rails.env.production? ? Logger::INFO : Logger::DEBUG
    ```
  </details>

**Comment by mikker** [comment]
Hi @toncid! Thank you for discovering and reporting this. I was able to confirm it and have fixed in a PR. Will release a new version tomorrow morning (CET).
