### ISSUE TITLE
Errors with delayed_job spy

### ISSUE THREAD

**Issue by Matt-Yorkley** [elastic/apm-agent-ruby#881]
## Describe the bug

The delayed_job spy doesn't seem to pick up configs from `config/elastic_apm.yml` but instead uses the defaults. I have a domain set in `config/elastic_apm.yml`, eg: `server_url: 'https://my-elasticstack-domain:8200'` but all delayed_job related traces fail and generate this error in the logs:
```
[ElasticAPM] Couldn't establish connection to APM Server:
"#<HTTP::ConnectionError: failed to connect: Connection refused - connect(2) for \"localhost\" port 8200>"
```

Regular traces for Rails are going through to the correct domain at the same time as these delayed_job traces are failing.

## Expected behavior

delayed_job spy works

## Environment

- **OS**: Ubuntu
- **Ruby version**: 2.3.7
- **Framework and version**: Rails 4.2
- **APM Server version**: 7.9
- **Agent version**: 3.10.1

## Additional context

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    # config/elastic_apm.yml
    service_name: 'rails'
    secret_token: 'xxxxxxxxxxxxx'
    server_url: 'https://my-elasticstack-domain:8200'
    ```
  </details>

**Comment by Matt-Yorkley** [comment]
In my Rails log I see these errors:
```
I, [2020-10-19 11:00:05#19366]  INFO -- : [3.10.1] Starting agent, reporting to http://localhost:8200
E, [2020-10-19 11:00:05#19366] ERROR -- : [ElasticAPM] Couldn't establish connection to APM Server:
"#<HTTP::ConnectionError: failed to connect: Connection refused - connect(2) for \"localhost\" port 8200>"
```
The PID after the timestamp matches my delayed_job PID.

If I enable the agent logging (log/elastic_apm.log) I see this:
```
[3.10.1] Starting agent, reporting to https://<my-rails-apm-domain>:8200
```

**Comment by mikker** [comment]
Hi @Matt-Yorkley! 

Sure sounds weird. Just asking some _maybe dumb_ questions to get the thoughts going:

How are you starting delayed? Could be that it's run with a working directory other than Rails.root? Are you sure the process has access to the config file?

**Comment by Matt-Yorkley** [comment]
It's started by a startup script which is installed by the delayed_job gem. It runs inside the Rails root. I'm using a standard setup from the docs: https://github.com/collectiveidea/delayed_job

**Comment by Matt-Yorkley** [comment]
Ah I had to be more explicit with the working directory. I think it's solved :+1:

**Comment by mikker** [comment]
Great! Thanks for updating. Would you mind sharing the change here?

**Comment by Matt-Yorkley** [comment]
Delayed job was separately being invoked from a systemd unit, and it didn't specify the `WorkingDirectory` property explicitly. I think the delayed_job gem used to change to the Rails root when it started, but maybe that behavior was changed recently?
