### ISSUE TITLE
sanitizer breaks my elasticsearch query

### ISSUE THREAD

**Issue by Leihb** [elastic/apm-agent-ruby#893]
I have an elasticsearch query like this
```
{
  "aggs": {
    "type_count": {
      "cardinality": {
        "field": "type"
      }
    }
  }
}
```

before i install this agent, it works well.

and now the es server return a 400 bad request with this message

> Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"Expected [START_OBJECT] under [cardinality], but got a [VALUE_STRING] 

when i configure the option 'capture_elasticsearch_queries' to false,  the query gets fine

**Comment by Leihb** [comment]
It seems that the  word 'cardinality'  hits the WildcardPattern *card*, and this method "ElasticAPM::Spies::ElasticsearchSpy.sanitizer.strip_from!"  alters the original query body.

**Comment by mikker** [comment]
ugh, but it should not touch the original query. Taking a look!
