### ISSUE TITLE
ElasticAPM::Sql module breaks when a sql string contains a binary column value

### ISSUE THREAD

**Issue by albert-2020** [elastic/apm-agent-ruby#895]
## Describe the bug
I add apm-agent-ruby into my rails application. In most cases, apm-agent can correctly capture SQL of ActiveRecord. However, when a SQL string contains a  binary column value,  apm-agent raises an error (ArgumentError: invalid byte sequence in UTF-8), which breaks my application.

## Steps to reproduce
1. an example raw SQL string
```
sql_str =<<EOF
 INSERT INTO "checksums" ("checksum") VALUES ( ",&\xB4kh\xFF\xC6\x8F\xF9\x9BE<\x1D0A4\x13B-pd\x83\xBF\xA0\xF9\x8A^\x88bf\xE7\xAE")
EOF
```

2. apm-agent tries to capture this SQL string

```
# https://github.com/elastic/apm-agent-ruby/blob/a958ef697bd93eed2c242aa92e65bb290713b128/lib/elastic_apm/sql/tokenizer.rb#L46

# same as the following code

SPACE = /[[:space:]]+/.freeze
scanner = StringScanner.new(input)
scanner = scanner.Scan(SPACE)  # raise a error

```

## Expected behavior

apm-agent correctly captures that raw SQL string 

## Current behavior

apm-agent raises an error 
```
ArgumentError: invalid byte sequence in UTF-8
  from elastic_apm/sql/tokenizer.rb:47:in `skip'
  from elastic_apm/sql/tokenizer.rb:47:in `scan'
  from elastic_apm/sql/signature.rb:44:in `parse'
  from elastic_apm/sql/signature.rb:57:in `parse'
```

## Environment

- **OS**: linux
- **Ruby version**: 2.5.0
- **Framework and version**: e.g. Rails 5.0.2
- **Agent version**: 3.11.0

**Comment by estolfo** [comment]
@albert-2020 Thank you for reporting this and sorry for the trouble. We'll have an update soon!

**Comment by estolfo** [comment]
@albert-2020 I merged a fix for this into master, if you'd like to test it. Otherwise, it'll be available in the next release. Thanks again for opening the issue!

**Comment by albert-2020** [comment]
> @albert-2020 I merged a fix for this into master, if you'd like to test it. Otherwise, it'll be available in the next release. Thanks again for opening the issue!

commit: 9d19e6c
It works now. Thank you.
