### ISSUE TITLE
Central config fails to fetch with service names that contain spaces

### ISSUE THREAD

**Issue by invke** [elastic/apm-agent-ruby#911]
## Describe the bug

It seems that requests to the APM metrics server fail when the server name contains non URL safe characters, like spaces. Only the projects in our setup with no spaces in the names seem to successfully make requests through to the APM metrics server to retrieve the central config. Projects with service names that contain spaces error when attempting to fetch the central config. All normal events post fine. It is only the `GET /config/v1/agents?service.name=SomeSweetService` requests that this issue appears in. 

I noticed this when setting up the central config for our various projects. Once Kibana and metrics servers were successfully communicating, it still failed to apply the config.

I first got the rails server & `apm-agent-ruby` logging at the debug level. Then found the `apm-agent-ruby` was logging `Failed fetching config: , trying again in 300 seconds`.

I then searched the gem to find the [source of the message](https://github.com/elastic/apm-agent-ruby/blob/d1e3513d38b181ff9dddc9d32d1ba33eb77b5a24/lib/elastic_apm/central_config.rb#L150). It at that point it could either of been a server returned error code or a client-side request issue.

To work out if it was a server returned error, I checked the APM server logs and also the ingress and found out at this stage that only one of the projects was even making `/config/v1/agents` requests to the APM server. The project had identical (and minimal) config, the only difference being the project name. Eliminating it as server response error issue.

So I hopped onto a staging pod and ran the rails console and replicated the `@http.get` call to try work out if I could get more information directly, since the debug log didn't mention the error code, or if it managed to make a request. You can see my command in the attached details. During this, I got a 400 bad request when manually performing the request, but when I escaped the spaces with `%20`, it succeeded.

## Steps to reproduce

1. Set up a Rails application w/ client configured with a service name containing spaces.
2. Set up an Elasticsearch, APM metrics server and Kibana stack.
3. Configure APM server connection w/ Kibana.
4. Run your client application with `ELASTIC_APM_LOG_LEVEL` set to `0` (debug).
5. You will notice it logs `Failed fetching config: , trying again in 300 seconds`.
6. This repeats every 300s / 5 minutes.

## Expected behavior

The central config successfully is pulled and applied, instead of an empty failure and standoff.

## Environment
- **OS**: Docker alpine 3.10 (specifically `ruby:2.7.1-alpine3.10`)
- **Ruby version**: 2.7.1
- **Framework and version**: Rails 6.0.3
- **APM Server version**: 7.9.1 (via [Elastic provided Helm charts](https://github.com/elastic/helm-charts))
- **Agent version**: 3.10.1

## Additional context

- The debug logs during the startup of the rails server.

  <details>
    <summary>Click to expand</summary>
    
    ```
    I, [2020-12-02T16:12:27.378375 #226]  INFO -- : [3.10.1] Starting agent, reporting to https://apm-server.cloud.boost.co.nz
    D, [2020-12-02T16:12:27.378492 #226] DEBUG -- : [ElasticAPM] Starting CentralConfig
    D, [2020-12-02T16:12:27.379071 #226] DEBUG -- : [ElasticAPM] [PID:226]: Starting Transport
    D, [2020-12-02T16:12:27.379142 #226] DEBUG -- : [ElasticAPM] [PID:226]: Booting worker...
    D, [2020-12-02T16:12:27.379862 #226] DEBUG -- : [ElasticAPM] Starting instrumenter
    D, [2020-12-02T16:12:27.379967 #226] DEBUG -- : [ElasticAPM] Starting metrics
    D, [2020-12-02T16:12:27.380046 #226] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::CpuMemSet'
    D, [2020-12-02T16:12:27.390733 #226] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::VMSet'
    D, [2020-12-02T16:12:27.448569 #226] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::BreakdownSet'
    D, [2020-12-02T16:12:27.448795 #226] DEBUG -- : [ElasticAPM] Adding metrics collector 'ElasticAPM::Metrics::TransactionSet'
    D, [2020-12-02T16:12:27.457074 #226] DEBUG -- : [ElasticAPM] Collecting metrics
    D, [2020-12-02T16:12:27.473918 #226] DEBUG -- : [ElasticAPM] [THREAD:20280]: Opening new request
    D, [2020-12-02T16:12:27.475745 #226] DEBUG -- : [ElasticAPM] Failed fetching config: , trying again in 300 seconds
    D, [2020-12-02T16:12:27.478311 #226] DEBUG -- : [ElasticAPM] Registering subscriber
    ```
  <details>

- My final attempt at getting a detailed error was manually performing the get on my staging environments rails console. Here is a copy of the output.

  <details>
    <summary>Click to expand</summary>
    
    ```
    irb(main):012:0> config = ElasticAPM::Config.new(Rails.application.config.elastic_apm)
    [DEPRECATED] The option ignore_url_patterns is being removed. Consider using transaction_ignore_urls instead.
    irb(main):013:0> http = ElasticAPM::Transport::Connection::Http.new(config)
    irb(main):014:0> server_url = config.server_url + '/config/v1/agents?service.name=FinCap Client Voices'
    irb(main):015:0> http.get(server_url)
    => #<HTTP::Response/1.1 400 Bad Request {"Content-Length"=>"0", "Connection"=>"Close"}>
    irb(main):016:0> server_url = config.server_url + '/config/v1/agents?service.name=FinCap%20Client%20Voices'
    irb(main):017:0> http.get(server_url)
    => #<HTTP::Response/1.1 200 OK {"Access-Control-Expose-Headers"=>"Etag", "Cache-Control"=>"max-age=30, must-revalidate", "Content-Type"=>"text/plain; charset=utf-8", "Date"=>"Wed, 02 Dec 2020 22:01:04 GMT", "Etag"=>"\"-\"", "Server"=>"nginx/1.17.8", "X-Content-Type-Options"=>"nosniff", "Content-Length"=>"3", "Connection"=>"Close"}>
    ```
  <details>

Let me know how I can help, cheers.

**Comment by mikker** [comment]
This sounds like a bug, yes. I'll take a look 👍
