### ISSUE TITLE
NoMethodError: undefined method `outcome=' for false:FalseClass in Mongo

### ISSUE THREAD

**Issue by wibicms** [elastic/apm-agent-ruby#936]
## Describe the bug
The issue raised when running a query (in my case insert into MongoDB). It said 
`NoMethodError: undefined method `outcome=' for false:FalseClass
from /Users/xxx/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elastic-apm-3.13.0/lib/elastic_apm/spies/mongo.rb:54:in `succeeded'`. 
## Steps to reproduce
1. add gem elastic-apm to Gemfile
2. Insert Data To Mongo

## Expected behavior
Query run successfully and elastic-apm listen catch event.

## Environment

- **OS**: MacOS Catalina
- **Ruby version**: 2.6.0
- **Framework and version**:  Rails 6.0
- **APM Server version**: 7.10.2
- **Agent version**: 3.13

**Comment by mikker** [comment]
Thank you for reporting this. I think I've found the error. Will push a release if so.

**Comment by mikker** [comment]
@wibicms Can you perhaps try `master` and confirm or deny that this fixes the problem?

**Comment by wibicms** [comment]
Thank you @mikker I've tried and it works.
