### ISSUE TITLE
Docker container id is not published

### ISSUE THREAD

**Issue by bmmchugh** [elastic/apm-agent-ruby#941]
## Describe the bug

Docker container id is not published to the APM server.

## Steps to reproduce

1. Run a Rails application in a Docker container with ElasticAPM enabled.

## Expected behavior

The `container.id` field should be published with the metadata to allow transactions to be filtered by container.

## Environment

- **OS**: Linux (Docker image `ruby:2.7.2`)
- **Ruby version**: 2.7.2
- **Framework and version**: Rails 6.1.1
- **APM Server version**: 7.9.3
- **Agent version**:  3.13.0

## Additional context

I was able to verify the `container.id` is published after building container info in the [MetadataSerializer](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/transport/serializers/metadata_serializer.rb)
```ruby
          def build_system(system)
            {
              hostname: keyword_field(system.hostname),
              architecture: keyword_field(system.architecture),
              platform: keyword_field(system.platform),
              kubernetes: keyword_object(system.kubernetes),
              container: keyword_object(system.container)
            }
          end

```
- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    config.elastic_apm.enabled = true
    config.elastic_apm.service_name = 'service-name'
    config.elastic_apm.server_url = ENV['ELASTIC_APM_SERVER_URL']
    config.elastic_apm.environment = ENV['ENVIRONMENT']
   ```
  </details>

**Comment by estolfo** [comment]
@bmmchugh thanks for opening this issue! Would you like to open a PR to add in the container id? Otherwise, we are happy to add it.

**Comment by bmmchugh** [comment]
Thanks, I can open a PR.
