### ISSUE TITLE
[META 408] Instrumentation for DynamoDB

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-ruby#943]
Provide instrumentation support for DynamoDB.

Meta issue: https://github.com/elastic/apm/issues/408
SPEC: https://github.com/elastic/apm/issues/409

**Comment by estolfo** [comment]
Already done via a [community PR](https://github.com/elastic/apm-agent-ruby/pull/827)

**Comment by estolfo** [comment]
I'm going to reopen this because the spec may require some extra info to be captured.
