### ISSUE TITLE
Failed with NoMethodError undefined method `method_name' for Delayed::PerformableMethod

### ISSUE THREAD

**Issue by BuffaloWill** [elastic/apm-agent-ruby#951]
## Describe the bug

When running one of our applications with elastic-apm installed I see the following error returned in the logs:

```
Failed with NoMethodError [undefined method `method_name' for #<Delayed::PerformableMethod:0x000000001542e090>] (0 attempts)
```

This also looks to be breaking some of our functionality (i.e. rolling back the changes by removing the gem and Elastic APM configuration fix the issue). I am receiving APM data for this application at the APM server.

## Environment

- **OS**: Linux, K8S
- **Ruby version**: ruby 2.4.3p205
- **Framework and version**: Phusion Passenger
- **APM Server version**: 7.9.2
- **Agent version**: 3.13.0

**Comment by mikker** [comment]
Thanks for reporting this. What version of DelayedJob are you using?

**Comment by BuffaloWill** [comment]
Thank you for the quick patch!

I am having some trouble finding what version of DelayedJob we are using. I ran `gem list --all` and I don't see it listed. Could it be packaged as part of a different gem?

**Comment by estolfo** [comment]
Hi @BuffaloWill are you using a Gemfile and bundler? If so, you can run `bundle list` and it should show the version of DelayedJob you have. Let us know if that works!

**Comment by BuffaloWill** [comment]
Thank you for the help @estolfo. Yes, we are using Gemfile and bundler in the container. I don't see DelayedJob listed when I run `bundle list`.

**Comment by estolfo** [comment]
@BuffaloWill, you could also check the `Gemfile.lock` to see what version of DelayedJob you have. If you find it in there, you should be able to determine which gem installed it as a dependency as well.
