### ISSUE TITLE
log_path config not working 

### ISSUE THREAD

**Issue by HimanshuLakra** [elastic/apm-agent-ruby#964]
Ruby: 2.6.2
Elastic Apm Gem Version: 3.13.0
Rails: 5.1.4

I have added log_path config in config/elastic_apm.yml as mentioned in 
https://www.elastic.co/guide/en/apm/agent/ruby/3.x/configuration.html#config-log-path

config/elastic_apm.yml
```
 server_url: <%= Settings.ELASTIC_APM.SERVER_URL %>
 secret_token: <%= Settings.ELASTIC_APM.SECRET_TOKEN %>
 enabled: <%= Settings.ELASTIC_APM.ENABLE %>
 log_path: 'log/elastic_apm.log'
```

There is problem in assignment of log_path config with logger object. 
Rails console output
```
2.6.2 :001 > ElasticAPM.agent.config.log_path
 => "/Users/himanshulakra/Desktop/workspace/elastic-apm-demo/log/elastic_apm.log"

2.6.2 :002 > ElasticAPM.agent.config.logger
 => #<ActiveSupport::Logger:0x00007f91a05892e0 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007f91a05891f0 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x00007f91a413c2b0 @datetime_format=nil, @thread_key="activesupport_tagged_logging_tags:70131749871960">, @logdev=#<Logger::LogDevice:0x00007f91a0589178 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/Users/himanshulakra/Desktop/workspace/elastic-apm-demo/log/development.log>, @mon_mutex=#<Thread::Mutex:0x00007f91a0588430>, @mon_mutex_owner_object_id=70131718572220, @mon_owner=nil, @mon_count=0>, @local_levels=#<Concurrent::Map:0x007f91a0588228 entries=0 default_proc=nil>>
```
As you can see above logger object has file path of development.log instead of log_path config value.

While debugging I saw that build_logger function lib/elastic_apm/config.rb is not called from initialize method since logger is already set with ActiveSupport::Logger instance.
Also do let me know if you need any more information.

**Comment by estolfo** [comment]
Hi @HimanshuLakra, thanks for opening this issue. We set the elastic apm agent logger to the Rails logger, unless you specify a different one explicitly. Simply providing a different `log_path` doesn't create a new logger for the agent.
What behavior did you expect? Perhaps we need to clarify the existing behavior in our documentation or consider changing the agent behavior if it's unexpected.

**Comment by HimanshuLakra** [comment]
@estolfo I want to move elastic_apm logs to a different file location('log/elastic_apm.log'). According to the documentation it seems, we only require to provide the file path and the current logger output location will be changed to the config log_path. Could you please specify what changes are required in the config file to implement this requirement? 
As I have tried the below configuration also, it is not working.
`
 server_url: <%= Settings.ELASTIC_APM.SERVER_URL %>
 secret_token: <%= Settings.ELASTIC_APM.SECRET_TOKEN %>
 enabled: <%= Settings.ELASTIC_APM.ENABLE %>
 logger: <%= Logger.new('log/elastic_apm.log') %>
`
(Specifying logger in the config file with the destination path.)

**Comment by bv-ritesh** [comment]
@HimanshuLakra thanks for raising this issue. I have faced the same issue. @estolfo +1 for this issue

**Comment by estolfo** [comment]
Hi @HimanshuLakra thanks for the extra information. Setting a ruby `Logger` object in the yaml file wouldn't work because the yaml file can only load string values. The only way to override the Rails logger is to provide a ruby `Logger` object to the agent or set it on the config. Nevertheless, I agree that it's confusing that providing a `log_path` as an agent config doesn't result in a separate logger from the Rails logger and the behavior should be changed.
We'll consider it a bug and work on it for the next patch release. Thanks again for opening this issue!

**Comment by bv-ritesh** [comment]
@estolfo can you share one example on how to pass logger. I am facing a serious issue while running the APM agent in production. 
we are seeing our resque workers are getting stuck in between after running for some time. We are trying to debug it.

**Comment by HimanshuLakra** [comment]
Hi @estolfo, Thanks for picking this up as a bug. And my bad logger config object needs to be set up in the application.rb as
`config.elastic_apm.logger = Logger.new('log/elastic_apm.log')` and its working fine. When can we expect the next release?

**Comment by mikker** [comment]
@bv-ritesh in `config/application.rb`

```ruby
  config.elastic_apm.logger = Logger.new(File.open('log/elastic_apm.log'))
```
