### ISSUE TITLE
Kubernetes pod name and service_node_name not showing

### ISSUE THREAD

**Issue by pbstriker38** [elastic/apm-agent-ruby#972]
## Describe the bug
The UI is not listing any pods or node names for our ruby apps. This info shows for our Node.js apps which are deployed in the same environment. I'm not sure why this is the case since the serialized metadata does contain this info.

```ruby
JSON.fast_generate(ElasticAPM::Transport::Serializers::MetadataSerializer.new(config).build(metadata))
=> "{\"metadata\":{\"service\":{\"name\":\"service-name\",\"environment\":\"staging\",\"version\":\"fbbd2c9\",\"agent\":{\"name\":\"ruby\",\"version\":\"3.13.0\"},\"framework\":{\"name\":null,\"version\":null},\"language\":{\"name\":\"ruby\",\"version\":\"3.0.0\"},\"runtime\":{\"name\":\"ruby\",\"version\":\"3.0.0\"}},\"process\":{\"pid\":4329,\"title\":\"irb\",\"argv\":[]},\"system\":{\"hostname\":\"pod-name-5d79fc8c66-9pt7t\",\"architecture\":\"x86_64\",\"platform\":\"linux\",\"kubernetes\":{\"namespace\":null,\"node\":{\"name\":null},\"pod\":{\"name\":null,\"uid\":\"32797627-7b31-4bb1-a6b4-aa66458c49da\"}}},\"labels\":null,\"cloud\":{\"provider\":\"provider\",\"account\":{\"id\":\"99999\"},\"availability_zone\":\"zone\",\"instance\":{\"id\":\"i-99999\"},\"machine\":{\"type\":\"type\"},\"region\":\"region\"}}}"
```

I did notice that `system.hostname` is deprecated in the [metadata schema](https://github.com/elastic/apm-server/blob/v7.11.1/docs/spec/v2/metadata.json#L388) in favor of `detected_hostname` or `configured_hostname`. Not sure if this is the issue because I'm pretty sure the Node.js agent is also using `hostname`.

![image](https://user-images.githubusercontent.com/5264240/108577383-b7ab7600-72d5-11eb-9ee9-07ac8477c137.png)
![image](https://user-images.githubusercontent.com/5264240/108577395-c134de00-72d5-11eb-8cbb-bc7839023f6c.png)

Adding these ENV vars to our kubernetes deployment fixed the issue.
https://www.elastic.co/guide/en/apm/server/current/metadata-api.html#kubernetes-data <- **This doc needs to be easier to find**

I would still expect the pod name to be automatically populated though since kubernetes sets the hostname to the pod name.

## Expected behavior

Kubernetes pod name should be automatically configured from hostname.

## Environment

- **OS**: Linux
- **Ruby version**: 2.7 and 3.0
- **Framework and version**: Grape 1.5.1 and 1.5.2
- **APM Server version**: 7.11.1
- **Agent version**: 3.13.0

**Comment by estolfo** [comment]
Hi @pbstriker38, thanks for reporting this. We'll look into it and have an update soon!
