### ISSUE TITLE
Per request Transaction data not recorded

### ISSUE THREAD

**Issue by xcskier56** [elastic/apm-agent-ruby#990]
## Describe the bug
Request data is either not being sent, or not showing up in kibana. From the console, I'm able to manually track a transaction using the following code and it shows up successfully in Kibana.

```
ElasticAPM.start(
  app: Rails.application,
  server_url: 'http://localhost:8200',
  log_level: 0
)

ElasticAPM.start_transaction('Name')
sleep 1
ElasticAPM.end_transaction('result')
# This will show up in ElasticSearch/Kibana
```

I am using an initializer instead of the yaml config. My initializer looks like this:

```
require 'elastic-apm'

ElasticAPM::Rails.start(
  app: Rails.application,
  server_url: ENV['APM_SERVER_ADDRESS'],
  log_level: 0
)
```

## Steps to reproduce
1. Start the server
2. Make a request

## Expected behavior
I expect that the request data shows up in elastic search. Nothing does

## Environment

- **OS**: Mac & Ubuntu 18.04
- **Ruby version**: 2.6.6
- **Framework and version**: Rails 6.0.1
- **APM Server version**: 7.11.1
- **Agent version**: 3.15.0

## Additional context

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    apm-server:
    image: docker.elastic.co/apm/apm-server:7.11.1
    restart: always
    ports:
      - 8200:8200
    command: >
       apm-server -e -d "*"
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=https://<redacted>
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=https://<redacted>:443
         -E apm-server.kibana.username="apm_internal"
         -E apm-server.kibana.password=${APM_INTERNAL_PASSWORD}
         -E output.elasticsearch.hosts=["https://<redacted>:443"]
         -E output.elasticsearch.username="apm_internal"
         -E output.elasticsearch.password=${APM_INTERNAL_PASSWORD}
    ```
  </details>

**Comment by xcskier56** [comment]
And, as usual, I solved the problem right after opening the issue. I added `require: false` to the gemfile so as to not load the gem in environments that I don't want it running in. This seems to have been the issue.

**Comment by mikker** [comment]
Glad you figured it out! 😊
