### ISSUE TITLE
S3 spy incompatible with Shrine S3 storage

### ISSUE THREAD

**Issue by krisrang** [elastic/apm-agent-ruby#997]
## Describe the bug

Elastic APM agent 3.15.0 causes all [Shrine](https://shrinerb.com/) S3 storage file downloads to be empty.

I traced this far as the Shrine S3 storage `get` method always hitting StopIteration when the S3 spy is enabled: https://github.com/shrinerb/shrine/blob/c195329ab48d011010b06a6062d888744ceb3be0/lib/shrine/storage/s3.rb#L287

I believe it should be fixed by passing any received block on to the original method call in the S3 spy.

## Steps to reproduce
1. Set up a new app with Shrine using S3 storage and Elastic APM 3.15
2. Upload file with Shrine
3. Try to download uploaded file using Shrine
4. Resulting Tempfile is empty.

## Expected behavior

Tempfile should contents of uploaded file.

## Environment
- **Ruby version**: 3.0.0
- **Framework and version**: Rails 6.1.3.1
- **Agent version**: 3.15.0

**Comment by mikker** [comment]
This does look like a bug. Fixing it right away, thanks!

**Comment by mikker** [comment]
The fix was just merged into master, the upcoming 4.0.0 release, and also included in 3.15.1.

**Comment by mikker** [comment]
Thank you for reporting this!

**Comment by krisrang** [comment]
Thank you for the fix!
